@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "it.brunasti.java.diagrammer.ClassDiagrammer#main(String[])",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "it.brunasti.java.diagrammer.ClassDiagrammer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_547127440 { 
   	label=brunasti
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1168587968 { 
   	label=java
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1828387995 { 
   	label=Utils
	labeljust=l
	fillcolor=white
	style=filled
   
   Utils1748953464XXXlistDirectories1808118735[
	label="+ listDirectories()"
	style=filled
	fillcolor=white
	tooltip="Utils

null"
	fontcolor=darkgreen
];

Utils1748953464XXXlistFilesUsingFilesList1808118735[
	label="+ listFilesUsingFilesList()"
	style=filled
	fillcolor=white
	tooltip="Utils

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_991314135 { 
   	label=ClassDiagrammer
	labeljust=l
	fillcolor=white
	style=filled
   
   ClassDiagrammer1748953464XXXmain1859653459[
	label="+ main()"
	style=filled
	fillcolor=white
	tooltip="ClassDiagrammer

null"
	penwidth=4
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ClassDiagrammer1748953464XXXmain1859653459 -> Utils1748953464XXXlistDirectories1808118735;
ClassDiagrammer1748953464XXXmain1859653459 -> Utils1748953464XXXlistFilesUsingFilesList1808118735;
    
}
@enduml