@startuml
'https://plantuml.com/class-diagram


'!include OCTA-labelscout-class-diagram.puml
!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_ASPECT
!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_DOMAIN
!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!PACKAGE2
'!includesub OCTA-labelscout-class-diagram.puml!PACKAGE3
'!includesub OCTA-labelscout-class-diagram.puml!PACKAGE4
''!includesub OCTA-labelscout-class-diagram.puml!PACKAGE5
'!includesub OCTA-labelscout-class-diagram.puml!PACKAGE6
'!includesub OCTA-labelscout-class-diagram.puml!PACKAGE7
''!includesub OCTA-labelscout-class-diagram.puml!PACKAGE8

'!includesub OCTA-labelscout-class-diagram.puml!USES
!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_ASPECT


'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS





hide member
hide circle
'hide *repo*
hide *web*
''nl.crolox.labelscout.helper.Product$ProductPrice ------- nl.crolox.labelscout.domain.AuditLog
@enduml
