@startuml
'https://plantuml.com/class-diagram

' GENERATE PAGES DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.spring.web.WebFlowAnalyser
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/pisend/src/main/java/]
' Configuration   : [./docs/config.json]
' Generated at    : Thu Jan 15 11:56:46 CET 2026
'
'   Pages infos    :
class "GET /api/v1/bvgorder/check/{order}" as BvGOrderAPI_checkBvgOrder {
    Get
    com.crolox.pisend.api.BvGOrderAPI
    BvGOrderAPI_checkBvgOrder
}

class "GET /api/v1/bvgorder/list" as BvGOrderAPI_listBvgOrderLog {
    Get
    com.crolox.pisend.api.BvGOrderAPI
    BvGOrderAPI_listBvgOrderLog
}



@enduml
