@startuml
'https://plantuml.com/class-diagram

' GENERATE PAGES DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.spring.web.WebFlowAnalyser
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/pickorderio/src/main/java/]
' Configuration   : [./docs/config.json]
' Generated at    : Thu Jan 15 11:56:46 CET 2026
'
'   Pages infos    :


@enduml
