@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolobrunasti/IdeaProjects/OCTA/Octa_Internal_Trace/trace-service/build/classes/java/main]
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/Octa_Internal_Trace/trace-service/src/main/java/]
' Configuration   : [/Users/paolobrunasti/IdeaProjects/mine/java-diagrammer/docs/octa/config.json]
' Generated at    : Wed Feb 04 13:21:32 CET 2026
'
'   Stat infos    :
'       Files : [232]
'       Lines : [14404]
'     Classes : [230]
'     Methods : [1282]
'      Fields : [714]

' Include         : [./docs/includedFile.txt] ---------
title Example with legend and title

hide empty members


legend
Connections legend
----
--|> : Extends
..|> : Implements
----
--> : Fields and Attributes
..> : Uses
end legend
' Include end     : --------------------------



'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_AOP_LOGGING
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_AOP_LOGGING
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_AOP_LOGGING
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_AOP_LOGGING
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_AOP_LOGGING
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_AOP_LOGGING

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_CLIENT
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_CLIENT
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_CLIENT
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_CLIENT
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_CLIENT
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_CLIENT

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_CONFIG
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_CONFIG
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_CONFIG
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_CONFIG
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_CONFIG
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_CONFIG

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_DOMAIN
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_DOMAIN
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_DOMAIN
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_DOMAIN
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_DOMAIN
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_DOMAIN

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_HELPER
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_HELPER
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_HELPER
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_HELPER
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_HELPER
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_HELPER

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_REPOSITORY
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_REPOSITORY
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_REPOSITORY
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_REPOSITORY
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_REPOSITORY
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_REPOSITORY

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_SECURITY
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_SECURITY
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_SECURITY
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_SECURITY
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_SECURITY
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_SECURITY

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_SERVICE
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_SERVICE
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_SERVICE
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_SERVICE_DTO
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE_DTO
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE_DTO
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_SERVICE_DTO
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_SERVICE_DTO
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE_DTO

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_WEB_REST
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_WEB_REST
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS

'!includesub OCTA-trace-service-class-diagram.puml!COM_FLUENC_FIT_TRACE_WEB_REST_VM
'!includesub OCTA-trace-service-class-diagram.puml!INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST_VM
'!includesub OCTA-trace-service-class-diagram.puml!IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST_VM
'!includesub OCTA-trace-service-class-diagram.puml!FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST_VM
'!includesub OCTA-trace-service-class-diagram.puml!USES_COM_FLUENC_FIT_TRACE_WEB_REST_VM
'!includesub OCTA-trace-service-class-diagram.puml!IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST_VM



' CLASSES =======
!startsub COM_FLUENC_FIT_TRACE
class com.fluenc.fit.trace.ApplicationWebXml
class com.fluenc.fit.trace.FittraceApp
interface com.fluenc.fit.trace.GeneratedByJHipster

!endsub

!startsub COM_FLUENC_FIT_TRACE_AOP_LOGGING
class com.fluenc.fit.trace.aop.logging.LoggingAspect

!endsub

!startsub COM_FLUENC_FIT_TRACE_CLIENT
class com.fluenc.fit.trace.client.TokenRelayRequestInterceptor
class com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration
interface com.fluenc.fit.trace.client.AuthorizedFeignClient

!endsub

!startsub COM_FLUENC_FIT_TRACE_CONFIG
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeWritingConverter
class com.fluenc.fit.trace.config.JacksonConfiguration
class com.fluenc.fit.trace.config.LoggingConfiguration
class com.fluenc.fit.trace.config.WebConfigurer
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantReadingConverter
class com.fluenc.fit.trace.config.LoggingAspectConfiguration
class com.fluenc.fit.trace.config.ElasticsearchConfiguration
class com.fluenc.fit.trace.config.DatabaseConfiguration
class com.fluenc.fit.trace.config.FeignConfiguration
class com.fluenc.fit.trace.config.SecurityConfiguration
class com.fluenc.fit.trace.config.LiquibaseConfiguration
class com.fluenc.fit.trace.config.Constants
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateReadingConverter
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeReadingConverter
class com.fluenc.fit.trace.config.DateTimeFormatConfiguration
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantWritingConverter
class com.fluenc.fit.trace.config.LocaleConfiguration
class com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateWritingConverter
class com.fluenc.fit.trace.config.ApplicationProperties
class com.fluenc.fit.trace.config.AsyncConfiguration
class com.fluenc.fit.trace.config.CacheConfiguration

!endsub

!startsub COM_FLUENC_FIT_TRACE_DOMAIN
abstract com.fluenc.fit.trace.domain.Collo_
abstract com.fluenc.fit.trace.domain.Authority_
abstract com.fluenc.fit.trace.domain.AbstractAuditingEntity_
abstract com.fluenc.fit.trace.domain.User_
abstract com.fluenc.fit.trace.domain.Hub_
class com.fluenc.fit.trace.domain.Collo
abstract com.fluenc.fit.trace.domain.Tote_
abstract com.fluenc.fit.trace.domain.Prescription_
class com.fluenc.fit.trace.domain.Hub
class com.fluenc.fit.trace.domain.User
abstract com.fluenc.fit.trace.domain.Trace_
abstract com.fluenc.fit.trace.domain.Event_
class com.fluenc.fit.trace.domain.Event
abstract com.fluenc.fit.trace.domain.AbstractAuditingEntity
class com.fluenc.fit.trace.domain.Prescription
class com.fluenc.fit.trace.domain.Trace
class com.fluenc.fit.trace.domain.Tote
class com.fluenc.fit.trace.domain.Authority
abstract com.fluenc.fit.trace.domain.Pharmacy_
class com.fluenc.fit.trace.domain.Pharmacy

!endsub

!startsub COM_FLUENC_FIT_TRACE_HELPER
class com.fluenc.fit.trace.helper.PrescriptionsTraceRequest

!endsub

!startsub COM_FLUENC_FIT_TRACE_REPOSITORY
interface com.fluenc.fit.trace.repository.HubRepository
interface com.fluenc.fit.trace.repository.PrescriptionRepository
interface com.fluenc.fit.trace.repository.TraceRepository
interface com.fluenc.fit.trace.repository.HubRepositoryExtended
interface com.fluenc.fit.trace.repository.EventRepository
interface com.fluenc.fit.trace.repository.AuthorityRepository
interface com.fluenc.fit.trace.repository.ColloRepository
interface com.fluenc.fit.trace.repository.EventRepositoryExtended
interface com.fluenc.fit.trace.repository.ToteRepository
interface com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended
interface com.fluenc.fit.trace.repository.PharmacyRepository
interface com.fluenc.fit.trace.repository.PharmacyRepositoryExtended
interface com.fluenc.fit.trace.repository.UserRepository

!endsub

!startsub COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
class com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternalImpl
class com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternalImpl
interface com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternal
class com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternalImpl
interface com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
interface com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.TraceSearchRepository
interface com.fluenc.fit.trace.repository.search.HubSearchRepository
interface com.fluenc.fit.trace.repository.search.ToteSearchRepository
interface com.fluenc.fit.trace.repository.search.UserSearchRepository
interface com.fluenc.fit.trace.repository.search.ColloSearchRepository
class com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternalImpl
interface com.fluenc.fit.trace.repository.search.PharmacySearchRepository
interface com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternal
interface com.fluenc.fit.trace.repository.search.EventSearchRepository
class com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternalImpl
class com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternalImpl
class com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternalImpl
class com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternalImpl

!endsub

!startsub COM_FLUENC_FIT_TRACE_SECURITY
class com.fluenc.fit.trace.security.SecurityUtils
class com.fluenc.fit.trace.security.SpringSecurityAuditorAware
class com.fluenc.fit.trace.security.AuthoritiesConstants

!endsub

!startsub COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
class com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil
class com.fluenc.fit.trace.security.oauth2.JwtGrantedAuthorityConverter
class com.fluenc.fit.trace.security.oauth2.OAuthIdpTokenResponseDTO
class com.fluenc.fit.trace.security.oauth2.AudienceValidator

!endsub

!startsub COM_FLUENC_FIT_TRACE_SERVICE
class com.fluenc.fit.trace.service.UserService
class com.fluenc.fit.trace.service.ElasticsearchIndexService
class com.fluenc.fit.trace.service.KeycloakService

!endsub

!startsub COM_FLUENC_FIT_TRACE_SERVICE_DTO
class com.fluenc.fit.trace.service.dto.AdminUserDTO
class com.fluenc.fit.trace.service.dto.UserDTO

!endsub

!startsub COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
class com.fluenc.fit.trace.service.mapper.UserMapper

!endsub

!startsub COM_FLUENC_FIT_TRACE_WEB_REST
class com.fluenc.fit.trace.web.rest.TraceResource
class com.fluenc.fit.trace.web.rest.UserResource
class com.fluenc.fit.trace.web.rest.ToteResource
class com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource
class com.fluenc.fit.trace.web.rest.EventResource
class com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource
class com.fluenc.fit.trace.web.rest.ColloResource
class com.fluenc.fit.trace.web.rest.PublicUserResource
class com.fluenc.fit.trace.web.rest.HubResource
class com.fluenc.fit.trace.web.rest.PharmacyResource
class com.fluenc.fit.trace.web.rest.PrescriptionResource

!endsub

!startsub COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
class com.fluenc.fit.trace.web.rest.errors.FieldErrorVM
class com.fluenc.fit.trace.web.rest.errors.ErrorConstants
class com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
class com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator

!endsub

!startsub COM_FLUENC_FIT_TRACE_WEB_REST_VM
class com.fluenc.fit.trace.web.rest.vm.ManagedUserVM

!endsub

' INHERITANCES =======

!startsub INHERITANCES_COM_FLUENC_FIT_TRACE

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_AOP_LOGGING

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_CLIENT

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_CONFIG

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_DOMAIN
com.fluenc.fit.trace.domain.AbstractAuditingEntity_ <|-- com.fluenc.fit.trace.domain.User_
com.fluenc.fit.trace.domain.AbstractAuditingEntity <|-- com.fluenc.fit.trace.domain.User

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_HELPER

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_REPOSITORY

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_SECURITY

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE_DTO

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS

!endsub


!startsub INHERITANCES_COM_FLUENC_FIT_TRACE_WEB_REST_VM
com.fluenc.fit.trace.service.dto.AdminUserDTO <|-- com.fluenc.fit.trace.web.rest.vm.ManagedUserVM

!endsub

' IMPLEMENT INTERFACE =======

!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE
java.lang.annotation.Annotation <|.. com.fluenc.fit.trace.GeneratedByJHipster

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_AOP_LOGGING

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_CLIENT
java.lang.annotation.Annotation <|.. com.fluenc.fit.trace.client.AuthorizedFeignClient

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_CONFIG

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_DOMAIN
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Collo
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Hub
java.io.Serializable <|.. com.fluenc.fit.trace.domain.User
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Event
java.io.Serializable <|.. com.fluenc.fit.trace.domain.AbstractAuditingEntity
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Prescription
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Trace
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Tote
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Authority
java.io.Serializable <|.. com.fluenc.fit.trace.domain.Pharmacy

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_HELPER

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_REPOSITORY
com.fluenc.fit.trace.repository.HubRepository <|.. com.fluenc.fit.trace.repository.HubRepositoryExtended
com.fluenc.fit.trace.repository.EventRepository <|.. com.fluenc.fit.trace.repository.EventRepositoryExtended
com.fluenc.fit.trace.repository.PrescriptionRepository <|.. com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended
com.fluenc.fit.trace.repository.PharmacyRepository <|.. com.fluenc.fit.trace.repository.PharmacyRepositoryExtended

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternalImpl
com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternal <|.. com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternalImpl

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_SECURITY

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
java.io.Serializable <|.. com.fluenc.fit.trace.security.oauth2.OAuthIdpTokenResponseDTO

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE_DTO

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
java.io.Serializable <|.. com.fluenc.fit.trace.web.rest.errors.FieldErrorVM

!endsub


!startsub IMPLEMENTS_COM_FLUENC_FIT_TRACE_WEB_REST_VM

!endsub

' FIELDS =======

!startsub FIELDS_COM_FLUENC_FIT_TRACE

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_AOP_LOGGING

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_CLIENT
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor --> com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_CONFIG
com.fluenc.fit.trace.config.WebConfigurer --> tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.SecurityConfiguration --> tech.jhipster.config.JHipsterProperties

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_DOMAIN
com.fluenc.fit.trace.domain.Collo --> com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.domain.Collo --> com.fluenc.fit.trace.domain.Tote
com.fluenc.fit.trace.domain.Collo --> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.domain.Prescription --> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.domain.Prescription --> com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.domain.Trace --> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.domain.Trace --> com.fluenc.fit.trace.domain.Event
com.fluenc.fit.trace.domain.Trace --> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.domain.Trace --> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.domain.Tote --> com.fluenc.fit.trace.domain.Hub

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_HELPER

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_REPOSITORY

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_SECURITY

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_SERVICE
com.fluenc.fit.trace.service.UserService --> com.fluenc.fit.trace.repository.UserRepository
com.fluenc.fit.trace.service.UserService --> com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.service.UserService --> com.fluenc.fit.trace.repository.AuthorityRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService --> com.fluenc.fit.trace.repository.search.TraceSearchRepository

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_SERVICE_DTO

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST
com.fluenc.fit.trace.web.rest.TraceResource --> com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.web.rest.TraceResource --> com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.web.rest.TraceResource --> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.TraceResource --> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.TraceResource --> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.UserResource --> com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.ToteResource --> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource --> com.fluenc.fit.trace.service.ElasticsearchIndexService
com.fluenc.fit.trace.web.rest.EventResource --> com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.web.rest.EventResource --> com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.PharmacyRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.HubRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.EventRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource --> com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.web.rest.ColloResource --> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ColloResource --> com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.web.rest.ColloResource --> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ColloResource --> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.ColloResource --> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.PublicUserResource --> com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.PublicUserResource --> com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.web.rest.HubResource --> com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.web.rest.HubResource --> com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.web.rest.PharmacyResource --> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.PharmacyResource --> com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.web.rest.PharmacyResource --> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PrescriptionResource --> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource --> com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource --> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PrescriptionResource --> com.fluenc.fit.trace.repository.PharmacyRepository

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS

!endsub


!startsub FIELDS_COM_FLUENC_FIT_TRACE_WEB_REST_VM

!endsub

' USES =======

!startsub USES_COM_FLUENC_FIT_TRACE

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_AOP_LOGGING

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_CLIENT
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor ..> com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor ..> feign.RequestTemplate
com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration ..> feign.RequestInterceptor
com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration ..> com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_CONFIG
com.fluenc.fit.trace.config.LoggingConfiguration ..> tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.WebConfigurer ..> tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.LoggingAspectConfiguration ..> com.fluenc.fit.trace.aop.logging.LoggingAspect
com.fluenc.fit.trace.config.FeignConfiguration ..> feign.Logger$Level
com.fluenc.fit.trace.config.SecurityConfiguration ..> tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.LiquibaseConfiguration ..> liquibase.integration.spring.SpringLiquibase
com.fluenc.fit.trace.config.CacheConfiguration ..> tech.jhipster.config.JHipsterProperties

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_DOMAIN
com.fluenc.fit.trace.domain.Collo ..> com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.domain.Collo ..> com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.domain.Collo ..> com.fluenc.fit.trace.domain.Tote
com.fluenc.fit.trace.domain.Collo ..> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.domain.Hub ..> com.fluenc.fit.trace.domain.Tote
com.fluenc.fit.trace.domain.Hub ..> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.domain.Hub ..> com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.domain.Event ..> com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.domain.Prescription ..> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.domain.Prescription ..> com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.domain.Prescription ..> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.domain.Prescription ..> com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.domain.Trace ..> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.domain.Trace ..> com.fluenc.fit.trace.domain.Event
com.fluenc.fit.trace.domain.Trace ..> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.domain.Trace ..> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.domain.Tote ..> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.domain.Tote ..> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.domain.Pharmacy ..> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.domain.Pharmacy ..> com.fluenc.fit.trace.domain.Prescription

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_HELPER

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_REPOSITORY

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_SECURITY

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil ..> com.fluenc.fit.trace.security.oauth2.OAuthIdpTokenResponseDTO

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_SERVICE
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.repository.UserRepository
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.repository.AuthorityRepository
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.service.dto.AdminUserDTO
com.fluenc.fit.trace.service.UserService ..> com.fluenc.fit.trace.domain.Authority
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.service.ElasticsearchIndexService ..> com.fluenc.fit.trace.repository.search.TraceSearchRepository

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_SERVICE_DTO
com.fluenc.fit.trace.service.dto.AdminUserDTO ..> com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.service.dto.UserDTO ..> com.fluenc.fit.trace.domain.User

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
com.fluenc.fit.trace.service.mapper.UserMapper ..> com.fluenc.fit.trace.service.dto.UserDTO
com.fluenc.fit.trace.service.mapper.UserMapper ..> com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.service.mapper.UserMapper ..> com.fluenc.fit.trace.service.dto.AdminUserDTO
com.fluenc.fit.trace.service.mapper.UserMapper ..> com.fluenc.fit.trace.domain.Authority

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_WEB_REST
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.TraceResource ..> com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.web.rest.UserResource ..> com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ToteResource ..> com.fluenc.fit.trace.domain.Tote
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource ..> com.fluenc.fit.trace.service.ElasticsearchIndexService
com.fluenc.fit.trace.web.rest.EventResource ..> com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.web.rest.EventResource ..> com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.web.rest.EventResource ..> com.fluenc.fit.trace.domain.Event
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..> com.fluenc.fit.trace.helper.PrescriptionsTraceRequest
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.ColloResource ..> com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.web.rest.PublicUserResource ..> com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.web.rest.PublicUserResource ..> com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.HubResource ..> com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.web.rest.HubResource ..> com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.web.rest.HubResource ..> com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.web.rest.PharmacyResource ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.PharmacyResource ..> com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.web.rest.PharmacyResource ..> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PharmacyResource ..> com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.PrescriptionResource ..> com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource ..> com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource ..> com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PrescriptionResource ..> com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource ..> com.fluenc.fit.trace.domain.Prescription

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator ..> com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator ..> com.fluenc.fit.trace.web.rest.errors.FieldErrorVM

!endsub


!startsub USES_COM_FLUENC_FIT_TRACE_WEB_REST_VM

!endsub

' IMPORTS =======
' Java Files Path : /Users/paolobrunasti/IdeaProjects/OCTA/Octa_Internal_Trace/trace-service/src/main/java/

!startsub IMPORTS_COM_FLUENC_FIT_TRACE
' com.fluenc.fit.trace.ApplicationWebXml
com.fluenc.fit.trace.ApplicationWebXml ..o tech.jhipster.config.DefaultProfileUtil

' com.fluenc.fit.trace.FittraceApp
com.fluenc.fit.trace.FittraceApp ..o com.fluenc.fit.trace.config.ApplicationProperties
com.fluenc.fit.trace.FittraceApp ..o tech.jhipster.config.DefaultProfileUtil
com.fluenc.fit.trace.FittraceApp ..o tech.jhipster.config.JHipsterConstants

' com.fluenc.fit.trace.GeneratedByJHipster

' com.fluenc.fit.trace.FittraceApp

' com.fluenc.fit.trace.ApplicationWebXml

' com.fluenc.fit.trace.GeneratedByJHipster


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_AOP_LOGGING
' com.fluenc.fit.trace.aop.logging.LoggingAspect
com.fluenc.fit.trace.aop.logging.LoggingAspect ..o tech.jhipster.config.JHipsterConstants

' com.fluenc.fit.trace.aop.logging.LoggingAspect


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_CLIENT
' com.fluenc.fit.trace.client.TokenRelayRequestInterceptor
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor ..o feign.RequestInterceptor
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor ..o com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil
com.fluenc.fit.trace.client.TokenRelayRequestInterceptor ..o feign.RequestTemplate

' com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration
com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration ..o feign.RequestInterceptor
com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration ..o com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil

' com.fluenc.fit.trace.client.AuthorizedFeignClient

' com.fluenc.fit.trace.client.TokenRelayRequestInterceptor

' com.fluenc.fit.trace.client.AuthorizedFeignClient

' com.fluenc.fit.trace.client.OAuth2InterceptedFeignConfiguration


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_CONFIG
' com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeWritingConverter

' com.fluenc.fit.trace.config.JacksonConfiguration

' com.fluenc.fit.trace.config.LoggingConfiguration
com.fluenc.fit.trace.config.LoggingConfiguration ..o ch.qos.logback.classic.LoggerContext
com.fluenc.fit.trace.config.LoggingConfiguration ..o  tech.jhipster.config.logging.LoggingUtils
com.fluenc.fit.trace.config.LoggingConfiguration ..o tech.jhipster.config.JHipsterProperties

' com.fluenc.fit.trace.config.WebConfigurer
com.fluenc.fit.trace.config.WebConfigurer ..o tech.jhipster.config.JHipsterProperties

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantReadingConverter

' com.fluenc.fit.trace.config.LoggingAspectConfiguration
com.fluenc.fit.trace.config.LoggingAspectConfiguration ..o tech.jhipster.config.JHipsterConstants
com.fluenc.fit.trace.config.LoggingAspectConfiguration ..o com.fluenc.fit.trace.aop.logging.LoggingAspect

' com.fluenc.fit.trace.config.ElasticsearchConfiguration

' com.fluenc.fit.trace.config.DatabaseConfiguration
com.fluenc.fit.trace.config.DatabaseConfiguration ..o tech.jhipster.config.JHipsterConstants

' com.fluenc.fit.trace.config.FeignConfiguration

' com.fluenc.fit.trace.config.SecurityConfiguration
com.fluenc.fit.trace.config.SecurityConfiguration ..o com.fluenc.fit.trace.security.oauth2.JwtGrantedAuthorityConverter
com.fluenc.fit.trace.config.SecurityConfiguration ..o tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.SecurityConfiguration ..o com.fluenc.fit.trace.security.oauth2.AudienceValidator
com.fluenc.fit.trace.config.SecurityConfiguration ..o com.fluenc.fit.trace.security.SecurityUtils

' com.fluenc.fit.trace.config.LiquibaseConfiguration
com.fluenc.fit.trace.config.LiquibaseConfiguration ..o tech.jhipster.config.JHipsterConstants
com.fluenc.fit.trace.config.LiquibaseConfiguration ..o tech.jhipster.config.liquibase.SpringLiquibaseUtil
com.fluenc.fit.trace.config.LiquibaseConfiguration ..o liquibase.integration.spring.SpringLiquibase

' com.fluenc.fit.trace.config.Constants

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateReadingConverter

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeReadingConverter

' com.fluenc.fit.trace.config.DateTimeFormatConfiguration

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantWritingConverter

' com.fluenc.fit.trace.config.LocaleConfiguration
com.fluenc.fit.trace.config.LocaleConfiguration ..o tech.jhipster.config.locale.AngularCookieLocaleResolver

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateWritingConverter

' com.fluenc.fit.trace.config.ApplicationProperties

' com.fluenc.fit.trace.config.AsyncConfiguration
com.fluenc.fit.trace.config.AsyncConfiguration ..o tech.jhipster.async.ExceptionHandlingAsyncTaskExecutor

' com.fluenc.fit.trace.config.CacheConfiguration
com.fluenc.fit.trace.config.CacheConfiguration ..o tech.jhipster.config.JHipsterProperties
com.fluenc.fit.trace.config.CacheConfiguration ..o tech.jhipster.config.cache.PrefixedKeyGenerator

' com.fluenc.fit.trace.config.ApplicationProperties

' com.fluenc.fit.trace.config.DatabaseConfiguration

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateWritingConverter

' com.fluenc.fit.trace.config.DateTimeFormatConfiguration

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$LocalDateReadingConverter

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantReadingConverter

' com.fluenc.fit.trace.config.AsyncConfiguration

' com.fluenc.fit.trace.config.CacheConfiguration

' com.fluenc.fit.trace.config.LoggingAspectConfiguration

' com.fluenc.fit.trace.config.SecurityConfiguration

' com.fluenc.fit.trace.config.ElasticsearchConfiguration

' com.fluenc.fit.trace.config.FeignConfiguration

' com.fluenc.fit.trace.config.JacksonConfiguration

' com.fluenc.fit.trace.config.Constants

' com.fluenc.fit.trace.config.LiquibaseConfiguration

' com.fluenc.fit.trace.config.WebConfigurer

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeWritingConverter

' com.fluenc.fit.trace.config.LoggingConfiguration

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$InstantWritingConverter

' com.fluenc.fit.trace.config.ElasticsearchConfiguration$ZonedDateTimeReadingConverter

' com.fluenc.fit.trace.config.LocaleConfiguration


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_DOMAIN
' com.fluenc.fit.trace.domain.Collo_

' com.fluenc.fit.trace.domain.Authority_

' com.fluenc.fit.trace.domain.AbstractAuditingEntity_

' com.fluenc.fit.trace.domain.User_

' com.fluenc.fit.trace.domain.Hub_

' com.fluenc.fit.trace.domain.Collo

' com.fluenc.fit.trace.domain.Tote_

' com.fluenc.fit.trace.domain.Prescription_

' com.fluenc.fit.trace.domain.Hub

' com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.domain.User ..o com.fluenc.fit.trace.config.Constants

' com.fluenc.fit.trace.domain.Trace_

' com.fluenc.fit.trace.domain.Event_

' com.fluenc.fit.trace.domain.Event

' com.fluenc.fit.trace.domain.AbstractAuditingEntity

' com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.domain.Trace

' com.fluenc.fit.trace.domain.Tote

' com.fluenc.fit.trace.domain.Authority

' com.fluenc.fit.trace.domain.Pharmacy_

' com.fluenc.fit.trace.domain.Pharmacy

' com.fluenc.fit.trace.domain.Authority

' com.fluenc.fit.trace.domain.AbstractAuditingEntity_

' com.fluenc.fit.trace.domain.Trace

' com.fluenc.fit.trace.domain.User

' com.fluenc.fit.trace.domain.Event

' com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.domain.AbstractAuditingEntity

' com.fluenc.fit.trace.domain.Pharmacy_

' com.fluenc.fit.trace.domain.Tote_

' com.fluenc.fit.trace.domain.Hub

' com.fluenc.fit.trace.domain.Trace_

' com.fluenc.fit.trace.domain.Authority_

' com.fluenc.fit.trace.domain.Pharmacy

' com.fluenc.fit.trace.domain.Hub_

' com.fluenc.fit.trace.domain.Collo_

' com.fluenc.fit.trace.domain.Event_

' com.fluenc.fit.trace.domain.User_

' com.fluenc.fit.trace.domain.Prescription_

' com.fluenc.fit.trace.domain.Tote

' com.fluenc.fit.trace.domain.Collo


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_HELPER
' com.fluenc.fit.trace.helper.PrescriptionsTraceRequest

' com.fluenc.fit.trace.helper.PrescriptionsTraceRequest


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_REPOSITORY
' com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.repository.HubRepository ..o com.fluenc.fit.trace.domain.Hub

' com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.repository.PrescriptionRepository ..o com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.repository.TraceRepository ..o com.fluenc.fit.trace.domain.Trace

' com.fluenc.fit.trace.repository.HubRepositoryExtended
com.fluenc.fit.trace.repository.HubRepositoryExtended ..o com.fluenc.fit.trace.domain.Hub

' com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.repository.EventRepository ..o com.fluenc.fit.trace.domain.Event

' com.fluenc.fit.trace.repository.AuthorityRepository
com.fluenc.fit.trace.repository.AuthorityRepository ..o com.fluenc.fit.trace.domain.Authority

' com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.repository.ColloRepository ..o com.fluenc.fit.trace.domain.Collo

' com.fluenc.fit.trace.repository.EventRepositoryExtended
com.fluenc.fit.trace.repository.EventRepositoryExtended ..o com.fluenc.fit.trace.domain.Event

' com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.repository.ToteRepository ..o com.fluenc.fit.trace.domain.Tote

' com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended
com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended ..o com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.repository.PharmacyRepository
com.fluenc.fit.trace.repository.PharmacyRepository ..o com.fluenc.fit.trace.domain.Pharmacy

' com.fluenc.fit.trace.repository.PharmacyRepositoryExtended
com.fluenc.fit.trace.repository.PharmacyRepositoryExtended ..o com.fluenc.fit.trace.domain.Pharmacy

' com.fluenc.fit.trace.repository.UserRepository
com.fluenc.fit.trace.repository.UserRepository ..o com.fluenc.fit.trace.domain.User

' com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.repository.EventRepository

' com.fluenc.fit.trace.repository.EventRepositoryExtended

' com.fluenc.fit.trace.repository.PharmacyRepositoryExtended

' com.fluenc.fit.trace.repository.ToteRepository

' com.fluenc.fit.trace.repository.UserRepository

' com.fluenc.fit.trace.repository.AuthorityRepository

' com.fluenc.fit.trace.repository.HubRepositoryExtended

' com.fluenc.fit.trace.repository.PrescriptionRepository

' com.fluenc.fit.trace.repository.TraceRepository

' com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended

' com.fluenc.fit.trace.repository.HubRepository

' com.fluenc.fit.trace.repository.ColloRepository


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_REPOSITORY_SEARCH
' com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository ..o com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.repository.search.TraceSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.TraceSearchRepository ..o com.fluenc.fit.trace.domain.Trace

' com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.repository.search.HubSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.HubSearchRepository ..o com.fluenc.fit.trace.domain.Hub

' com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.repository.search.ToteSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.ToteSearchRepository ..o com.fluenc.fit.trace.domain.Tote

' com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.repository.search.UserSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.UserSearchRepository ..o com.fluenc.fit.trace.domain.User

' com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.repository.search.ColloSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.ColloSearchRepository ..o com.fluenc.fit.trace.domain.Collo

' com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.repository.search.PharmacySearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.PharmacySearchRepository ..o com.fluenc.fit.trace.domain.Pharmacy

' com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.repository.search.EventSearchRepository ..o  org.elasticsearch.index.query.QueryBuilders.queryStringQuery
com.fluenc.fit.trace.repository.search.EventSearchRepository ..o com.fluenc.fit.trace.domain.Event

' com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.HubSearchRepository

' com.fluenc.fit.trace.repository.search.PharmacySearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.TraceSearchRepository

' com.fluenc.fit.trace.repository.search.ToteSearchRepository

' com.fluenc.fit.trace.repository.search.UserSearchRepository

' com.fluenc.fit.trace.repository.search.EventSearchRepository

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository

' com.fluenc.fit.trace.repository.search.ColloSearchRepository

' com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.ToteSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.TraceSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.UserSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.ColloSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternalImpl

' com.fluenc.fit.trace.repository.search.PrescriptionSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.HubSearchRepositoryInternal

' com.fluenc.fit.trace.repository.search.PharmacySearchRepository

' com.fluenc.fit.trace.repository.search.EventSearchRepositoryInternal


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_SECURITY
' com.fluenc.fit.trace.security.SecurityUtils

' com.fluenc.fit.trace.security.SpringSecurityAuditorAware
com.fluenc.fit.trace.security.SpringSecurityAuditorAware ..o com.fluenc.fit.trace.config.Constants

' com.fluenc.fit.trace.security.AuthoritiesConstants

' com.fluenc.fit.trace.security.AuthoritiesConstants

' com.fluenc.fit.trace.security.SecurityUtils

' com.fluenc.fit.trace.security.SpringSecurityAuditorAware


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_SECURITY_OAUTH2
' com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil

' com.fluenc.fit.trace.security.oauth2.JwtGrantedAuthorityConverter

' com.fluenc.fit.trace.security.oauth2.OAuthIdpTokenResponseDTO

' com.fluenc.fit.trace.security.oauth2.AudienceValidator

' com.fluenc.fit.trace.security.oauth2.OAuthIdpTokenResponseDTO

' com.fluenc.fit.trace.security.oauth2.JwtGrantedAuthorityConverter

' com.fluenc.fit.trace.security.oauth2.AuthorizationHeaderUtil

' com.fluenc.fit.trace.security.oauth2.AudienceValidator


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE
' com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.service.dto.AdminUserDTO
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.repository.UserRepository
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.config.Constants
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.repository.AuthorityRepository
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.service.dto.UserDTO
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.domain.Authority
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.service.UserService ..o com.fluenc.fit.trace.repository.search.UserSearchRepository

' com.fluenc.fit.trace.service.ElasticsearchIndexService

' com.fluenc.fit.trace.service.KeycloakService

' com.fluenc.fit.trace.service.ElasticsearchIndexService

' com.fluenc.fit.trace.service.UserService

' com.fluenc.fit.trace.service.KeycloakService


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE_DTO
' com.fluenc.fit.trace.service.dto.AdminUserDTO

' com.fluenc.fit.trace.service.dto.UserDTO

' com.fluenc.fit.trace.service.dto.AdminUserDTO

' com.fluenc.fit.trace.service.dto.UserDTO


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_SERVICE_MAPPER
' com.fluenc.fit.trace.service.mapper.UserMapper
com.fluenc.fit.trace.service.mapper.UserMapper ..o com.fluenc.fit.trace.service.dto.AdminUserDTO
com.fluenc.fit.trace.service.mapper.UserMapper ..o com.fluenc.fit.trace.domain.User
com.fluenc.fit.trace.service.mapper.UserMapper ..o com.fluenc.fit.trace.service.dto.UserDTO
com.fluenc.fit.trace.service.mapper.UserMapper ..o com.fluenc.fit.trace.domain.Authority

' com.fluenc.fit.trace.service.mapper.UserMapper


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST
' com.fluenc.fit.trace.web.rest.TraceResource
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.TraceResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.TraceResource ..o com.google.common.collect.Lists
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.TraceResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.TraceResource ..o tech.jhipster.web.util.PaginationUtil
com.fluenc.fit.trace.web.rest.TraceResource ..o tech.jhipster.web.util.PageUtil
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.TraceResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.web.rest.TraceResource ..o com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.web.rest.UserResource
com.fluenc.fit.trace.web.rest.UserResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.UserResource ..o com.fluenc.fit.trace.service.dto.AdminUserDTO
com.fluenc.fit.trace.web.rest.UserResource ..o com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.UserResource ..o com.fluenc.fit.trace.config.Constants
com.fluenc.fit.trace.web.rest.UserResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.UserResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.UserResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.UserResource ..o tech.jhipster.web.util.PaginationUtil

' com.fluenc.fit.trace.web.rest.ToteResource
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.domain.Tote
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ToteResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.repository.ToteRepository
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.ToteResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.ToteResource ..o tech.jhipster.web.util.PaginationUtil
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.repository.search.ToteSearchRepository
com.fluenc.fit.trace.web.rest.ToteResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.ToteResource ..o com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource ..o com.fluenc.fit.trace.service.ElasticsearchIndexService
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants

' com.fluenc.fit.trace.web.rest.EventResource
com.fluenc.fit.trace.web.rest.EventResource ..o com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.web.rest.EventResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.EventResource ..o com.fluenc.fit.trace.repository.EventRepository
com.fluenc.fit.trace.web.rest.EventResource ..o com.fluenc.fit.trace.domain.Event
com.fluenc.fit.trace.web.rest.EventResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.EventResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.EventResource ..o  org.elasticsearch.index.query.QueryBuilders

' com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.helper.PrescriptionsTraceRequest
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.PharmacyRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.EventRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.domain.Event
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.search.TraceSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.TraceRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.PrescriptionRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.HubRepositoryExtended
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.repository.search.EventSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource ..o com.fluenc.fit.trace.domain.Prescription

' com.fluenc.fit.trace.web.rest.ColloResource
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.repository.search.ColloSearchRepository
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.repository.ColloRepository
com.fluenc.fit.trace.web.rest.ColloResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.ColloResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.ColloResource ..o tech.jhipster.web.util.PaginationUtil
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.domain.Collo
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.ColloResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.web.rest.ColloResource ..o com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.web.rest.PublicUserResource
com.fluenc.fit.trace.web.rest.PublicUserResource ..o com.fluenc.fit.trace.service.UserService
com.fluenc.fit.trace.web.rest.PublicUserResource ..o com.fluenc.fit.trace.service.dto.UserDTO
com.fluenc.fit.trace.web.rest.PublicUserResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.PublicUserResource ..o com.fluenc.fit.trace.repository.search.UserSearchRepository
com.fluenc.fit.trace.web.rest.PublicUserResource ..o tech.jhipster.web.util.PaginationUtil

' com.fluenc.fit.trace.web.rest.HubResource
com.fluenc.fit.trace.web.rest.HubResource ..o com.fluenc.fit.trace.repository.HubRepository
com.fluenc.fit.trace.web.rest.HubResource ..o com.fluenc.fit.trace.repository.search.HubSearchRepository
com.fluenc.fit.trace.web.rest.HubResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.HubResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.HubResource ..o com.fluenc.fit.trace.domain.Hub
com.fluenc.fit.trace.web.rest.HubResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.HubResource ..o  org.elasticsearch.index.query.QueryBuilders

' com.fluenc.fit.trace.web.rest.PharmacyResource
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.repository.search.PharmacySearchRepository
com.fluenc.fit.trace.web.rest.PharmacyResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.PharmacyResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PharmacyResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.PharmacyResource ..o com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.web.rest.PrescriptionResource
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.repository.PrescriptionRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.domain.Trace
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o tech.jhipster.web.util.HeaderUtil
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.google.common.collect.Lists
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.security.SecurityUtils
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o  org.elasticsearch.index.query.QueryBuilders
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.security.AuthoritiesConstants
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o tech.jhipster.web.util.PaginationUtil
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o tech.jhipster.web.util.PageUtil
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.repository.search.PrescriptionSearchRepository
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.domain.Pharmacy
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.service.KeycloakService
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o tech.jhipster.web.util.ResponseUtil
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.domain.Prescription
com.fluenc.fit.trace.web.rest.PrescriptionResource ..o com.fluenc.fit.trace.repository.PharmacyRepository

' com.fluenc.fit.trace.web.rest.HubResource

' com.fluenc.fit.trace.web.rest.ToteResource

' com.fluenc.fit.trace.web.rest.PublicUserResource

' com.fluenc.fit.trace.web.rest.ColloResource

' com.fluenc.fit.trace.web.rest.UserResource

' com.fluenc.fit.trace.web.rest.PrescriptionResource

' com.fluenc.fit.trace.web.rest.PharmacyResource

' com.fluenc.fit.trace.web.rest.PrescriptionsTraceResource

' com.fluenc.fit.trace.web.rest.TraceResource

' com.fluenc.fit.trace.web.rest.EventResource

' com.fluenc.fit.trace.web.rest.ElasticsearchIndexResource


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST_ERRORS
' com.fluenc.fit.trace.web.rest.errors.FieldErrorVM

' com.fluenc.fit.trace.web.rest.errors.ErrorConstants

' com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException

' com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator
com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator ..o tech.jhipster.config.JHipsterConstants
com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator ..o tech.jhipster.web.util.HeaderUtil

' com.fluenc.fit.trace.web.rest.errors.BadRequestAlertException

' com.fluenc.fit.trace.web.rest.errors.ExceptionTranslator

' com.fluenc.fit.trace.web.rest.errors.FieldErrorVM

' com.fluenc.fit.trace.web.rest.errors.ErrorConstants


!endsub


!startsub IMPORTS_COM_FLUENC_FIT_TRACE_WEB_REST_VM
' com.fluenc.fit.trace.web.rest.vm.ManagedUserVM
com.fluenc.fit.trace.web.rest.vm.ManagedUserVM ..o com.fluenc.fit.trace.service.dto.AdminUserDTO

' com.fluenc.fit.trace.web.rest.vm.ManagedUserVM


!endsub


@enduml
