@startuml
'https://plantuml.com/class-diagram

' GENERATE PAGES DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.spring.web.WebFlowAnalyser
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/labelscout/src/main/java/]
' Configuration   : [./docs/config.json]
' Generated at    : Wed Jan 14 15:42:16 CET 2026
'
'   Pages infos    :
class "POST /v1/public/advice" as LabelscoutServiceV1_advice {
    Post
    nl.crolox.labelscout.service.LabelscoutServiceV1
    LabelscoutServiceV1_advice
}

class "POST /v1/cgm-advice" as LabelscoutServiceV1_adviceCGM {
    Post
    nl.crolox.labelscout.service.LabelscoutServiceV1
    LabelscoutServiceV1_adviceCGM
}

class "GET /login/admin/" as AdminPagesController_adminPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_adminPage
}

class "GET /login/admin/apotheekgroep" as AdminPagesController_apotheekGroepPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekGroepPage
}

class "GET /login/admin/label/{id}" as AdminPagesController_labelPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_labelPage
}

class "GET /login/admin/label/new/{id}" as AdminPagesController_labelNewPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_labelNewPage
}

class "GET /login/admin/label/edit/{id}" as AdminPagesController_labelEditPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_labelEditPage
}

class "GET /login/admin/groep" as AdminPagesController_groepPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_groepPage
}

class "GET /login/admin/groep/new" as AdminPagesController_groepNewPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_groepNewPage
}

class "GET /login/admin/groep/{id}" as AdminPagesController_getGroep {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_getGroep
}

class "GET /login/admin/apotheek/{id}" as AdminPagesController_getApotheek {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_getApotheek
}

class "GET /login/admin/apotheekGroep/{id}" as AdminPagesController_getApotheekGroep {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_getApotheekGroep
}

class "GET /login/admin/apotheek/" as AdminPagesController_apotheekNewPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekNewPage
}

class "GET /login/admin/apotheekgroep/new" as AdminPagesController_apotheekGroepNewPage {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekGroepNewPage
}

class "POST /login/admin/apotheek" as AdminPagesController_apotheekSubmit {
    Post
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekSubmit
}

class "POST /login/admin/apotheekGroep" as AdminPagesController_apotheekGroepSubmit {
    Post
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekGroepSubmit
}

class "POST /login/admin/label" as AdminPagesController_apotheekGroepLabelSubmit {
    Post
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_apotheekGroepLabelSubmit
}

class "POST /login/admin/groep" as AdminPagesController_groepSubmit {
    Post
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_groepSubmit
}

class "DELETE /login/admin/apotheek/delete/{id}" as AdminPagesController_deleteApotheek {
    Delete
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_deleteApotheek
}

class "DELETE /login/admin/apotheekGroep/delete/{id}" as AdminPagesController_deleteApotheekGroep {
    Delete
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_deleteApotheekGroep
}

class "DELETE /login/admin/groep/delete/{id}" as AdminPagesController_deleteGroep {
    Delete
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_deleteGroep
}

class "GET /login/admin/label/delete/{id}" as AdminPagesController_deleteLabel {
    Get
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_deleteLabel
}

class "POST /login/admin/label/update-order" as AdminPagesController_updateOrder {
    Post
    nl.crolox.labelscout.web.AdminPagesController
    AdminPagesController_updateOrder
}

class "GET /" as HomeController_homePage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_homePage
}

class "GET /login/" as HomeController_loginPage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_loginPage
}

class "GET /login/notAllowed" as HomeController_notAllowedPage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_notAllowedPage
}

class "GET /login/groupadmin/" as HomeController_groupAdminPage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_groupAdminPage
}

class "GET /login/user/" as HomeController_userPage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_userPage
}

class "GET /login/user/optipro" as HomeController_optiproPage {
    Get
    nl.crolox.labelscout.web.HomeController
    HomeController_optiproPage
}

class "GET /login/zoeken" as ZoekController_toonZoekPagina {
    Get
    nl.crolox.labelscout.web.ZoekController
    ZoekController_toonZoekPagina
}

class "GET /login/zoeken/zoek" as ZoekController_zoekOpZindex {
    Get
    nl.crolox.labelscout.web.ZoekController
    ZoekController_zoekOpZindex
}



@enduml
