@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolobrunasti/IdeaProjects/OCTA/labelscout/build/classes/java/main]
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/labelscout/src/main/java/]
' Configuration   : [/Users/paolobrunasti/IdeaProjects/mine/java-diagrammer/docs/octa/config.json]
' Generated at    : Mon Jan 26 17:44:24 CET 2026
'
'   Stat infos    :
'       Files : [104]
'       Lines : [4970]
'     Classes : [104]
'     Methods : [1024]
'      Fields : [370]

' Include         : [./docs/includedFile.txt] ---------
title Example with legend and title

hide empty members


legend
Connections legend
----
--|> : Extends
..|> : Implements
----
--> : Fields and Attributes
..> : Uses
end legend
' Include end     : --------------------------



'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_ASPECT
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_ASPECT
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_ASPECT
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_ASPECT
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_ASPECT
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_ASPECT

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_DOMAIN
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_DOMAIN
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_DOMAIN
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_DOMAIN
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_DOMAIN
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_DOMAIN

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_HELPER
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_HELPER

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_INTERCEPTOR
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_INTERCEPTOR
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_INTERCEPTOR
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_INTERCEPTOR
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_INTERCEPTOR
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_INTERCEPTOR

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_REPOSITORY
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_REPOSITORY
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_REPOSITORY
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_REPOSITORY
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_REPOSITORY
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_REPOSITORY

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_SERVICE
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_SERVICE
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_SERVICE
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_SERVICE
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_SERVICE
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_SERVICE

'!includesub OCTA-labelscout-class-diagram.puml!NL_CROLOX_LABELSCOUT_WEB
'!includesub OCTA-labelscout-class-diagram.puml!INHERITANCES_NL_CROLOX_LABELSCOUT_WEB
'!includesub OCTA-labelscout-class-diagram.puml!IMPLEMENTS_NL_CROLOX_LABELSCOUT_WEB
'!includesub OCTA-labelscout-class-diagram.puml!FIELDS_NL_CROLOX_LABELSCOUT_WEB
'!includesub OCTA-labelscout-class-diagram.puml!USES_NL_CROLOX_LABELSCOUT_WEB
'!includesub OCTA-labelscout-class-diagram.puml!IMPORTS_NL_CROLOX_LABELSCOUT_WEB



' CLASSES =======
!startsub NL_CROLOX_LABELSCOUT
class nl.crolox.labelscout.KeycloakLogoutHandler
class nl.crolox.labelscout.LabelscoutApplication
class nl.crolox.labelscout.SecurityConfig

!endsub

!startsub NL_CROLOX_LABELSCOUT_ASPECT
interface nl.crolox.labelscout.aspect.Loggable
class nl.crolox.labelscout.aspect.LoggingAspect

!endsub

!startsub NL_CROLOX_LABELSCOUT_DOMAIN
class nl.crolox.labelscout.domain.Apotheek
class nl.crolox.labelscout.domain.Logger
class nl.crolox.labelscout.domain.Label
class nl.crolox.labelscout.domain.Gebruiker
class nl.crolox.labelscout.domain.Groep
class nl.crolox.labelscout.domain.VoorraadCluster
class nl.crolox.labelscout.domain.AuditLog
class nl.crolox.labelscout.domain.Groothandel
class nl.crolox.labelscout.domain.ApotheekGroep
class nl.crolox.labelscout.domain.GroothandelVoorraad
enum nl.crolox.labelscout.domain.Gebruiker$USERROLE{
  ADMIN
  USER
  GROUPOWNER
}
class nl.crolox.labelscout.domain.Product

!endsub

!startsub NL_CROLOX_LABELSCOUT_HELPER
class nl.crolox.labelscout.helper.AdviceHelperRespone
class nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData
class nl.crolox.labelscout.helper.Product
class nl.crolox.labelscout.helper.AdviceHelperRequest
class nl.crolox.labelscout.helper.ProductResponse
class nl.crolox.labelscout.helper.ProductKeuze
class nl.crolox.labelscout.helper.Product$ProductPrice
class nl.crolox.labelscout.helper.OrderUpdateRequest
class nl.crolox.labelscout.helper.PreferentieClusterResponse$PreferentieClusterData
class nl.crolox.labelscout.helper.VoorraadResponse
class nl.crolox.labelscout.helper.LabelHelper
class nl.crolox.labelscout.helper.AdviceHelperResponeLine
class nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts
class nl.crolox.labelscout.helper.ApotheekHelper
class nl.crolox.labelscout.helper.GroepHelper
class nl.crolox.labelscout.helper.PreferentieClusterResponse

!endsub

!startsub NL_CROLOX_LABELSCOUT_INTERCEPTOR
class nl.crolox.labelscout.interceptor.DaoInterceptor

!endsub

!startsub NL_CROLOX_LABELSCOUT_REPOSITORY
interface nl.crolox.labelscout.repository.GroothandelRepository
interface nl.crolox.labelscout.repository.LabelRepository
interface nl.crolox.labelscout.repository.ApotheekGroepRepository
interface nl.crolox.labelscout.repository.GroepRepository
interface nl.crolox.labelscout.repository.GroothandelVoorraadRepository
interface nl.crolox.labelscout.repository.ProductRepository
interface nl.crolox.labelscout.repository.GebruikerRepository
interface nl.crolox.labelscout.repository.VoorraadClusterRepository
interface nl.crolox.labelscout.repository.ApotheekRepository

!endsub

!startsub NL_CROLOX_LABELSCOUT_SERVICE
class nl.crolox.labelscout.service.LabelscoutServiceV1
class nl.crolox.labelscout.service.ProductAdviesService
class nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$Embedded
class nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse
class nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$PreferentieCluster

!endsub

!startsub NL_CROLOX_LABELSCOUT_WEB
class nl.crolox.labelscout.web.HomeController
class nl.crolox.labelscout.web.Utils
class nl.crolox.labelscout.web.ZoekController
class nl.crolox.labelscout.web.AdminPagesController

!endsub

' INHERITANCES =======

!startsub INHERITANCES_NL_CROLOX_LABELSCOUT

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_ASPECT

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_DOMAIN
java.lang.Enum <|-- nl.crolox.labelscout.domain.Gebruiker$USERROLE

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_HELPER

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_INTERCEPTOR

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_REPOSITORY

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_SERVICE

!endsub


!startsub INHERITANCES_NL_CROLOX_LABELSCOUT_WEB

!endsub

' IMPLEMENT INTERFACE =======

!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_ASPECT
java.lang.annotation.Annotation <|.. nl.crolox.labelscout.aspect.Loggable

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_DOMAIN

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_HELPER

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_INTERCEPTOR

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_REPOSITORY

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_SERVICE

!endsub


!startsub IMPLEMENTS_NL_CROLOX_LABELSCOUT_WEB

!endsub

' FIELDS =======

!startsub FIELDS_NL_CROLOX_LABELSCOUT
nl.crolox.labelscout.SecurityConfig --> nl.crolox.labelscout.KeycloakLogoutHandler

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_ASPECT

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_DOMAIN
nl.crolox.labelscout.domain.Apotheek --> nl.crolox.labelscout.domain.VoorraadCluster
nl.crolox.labelscout.domain.Apotheek --> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Apotheek --> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.domain.Logger --> nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.domain.Label --> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.domain.Gebruiker --> nl.crolox.labelscout.domain.Gebruiker$USERROLE
nl.crolox.labelscout.domain.Gebruiker --> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Gebruiker --> nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.domain.Groep --> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Groep --> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.domain.AuditLog --> nl.crolox.labelscout.domain.Gebruiker
nl.crolox.labelscout.domain.GroothandelVoorraad --> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.domain.Product --> nl.crolox.labelscout.domain.Label

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_HELPER
nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData --> nl.crolox.labelscout.helper.PreferentieClusterResponse$PreferentieClusterData
nl.crolox.labelscout.helper.Product --> nl.crolox.labelscout.helper.Product$ProductPrice
nl.crolox.labelscout.helper.ProductResponse --> nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts
nl.crolox.labelscout.helper.ProductKeuze --> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts --> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.helper.PreferentieClusterResponse --> nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_INTERCEPTOR

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_REPOSITORY

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_SERVICE
nl.crolox.labelscout.service.LabelscoutServiceV1 --> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.service.LabelscoutServiceV1 --> nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.service.ProductAdviesService --> nl.crolox.labelscout.repository.GroothandelVoorraadRepository
nl.crolox.labelscout.service.ProductAdviesService --> nl.crolox.labelscout.repository.LabelRepository
nl.crolox.labelscout.service.ProductAdviesService --> nl.crolox.labelscout.repository.ProductRepository
nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse --> nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$Embedded

!endsub


!startsub FIELDS_NL_CROLOX_LABELSCOUT_WEB
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.repository.GebruikerRepository
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.repository.ApotheekGroepRepository
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.repository.GroothandelRepository
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.repository.GroepRepository
nl.crolox.labelscout.web.HomeController --> nl.crolox.labelscout.web.Utils
nl.crolox.labelscout.web.Utils --> nl.crolox.labelscout.repository.GebruikerRepository
nl.crolox.labelscout.web.ZoekController --> nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.web.ZoekController --> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.GebruikerRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.ApotheekGroepRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.GroothandelRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.GroepRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.LabelRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.ProductRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.repository.VoorraadClusterRepository
nl.crolox.labelscout.web.AdminPagesController --> nl.crolox.labelscout.web.Utils

!endsub

' USES =======

!startsub USES_NL_CROLOX_LABELSCOUT
nl.crolox.labelscout.SecurityConfig ..> nl.crolox.labelscout.KeycloakLogoutHandler

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_ASPECT

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_DOMAIN
nl.crolox.labelscout.domain.Apotheek ..> nl.crolox.labelscout.domain.VoorraadCluster
nl.crolox.labelscout.domain.Apotheek ..> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Apotheek ..> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.domain.Logger ..> nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.domain.Label ..> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.domain.Gebruiker ..> nl.crolox.labelscout.domain.Gebruiker$USERROLE
nl.crolox.labelscout.domain.Gebruiker ..> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Gebruiker ..> nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.domain.Groep ..> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.domain.Groep ..> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.domain.AuditLog ..> nl.crolox.labelscout.domain.Gebruiker
nl.crolox.labelscout.domain.GroothandelVoorraad ..> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.domain.Product ..> nl.crolox.labelscout.domain.Label

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_HELPER
nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData ..> nl.crolox.labelscout.helper.PreferentieClusterResponse$PreferentieClusterData
nl.crolox.labelscout.helper.Product ..> nl.crolox.labelscout.helper.Product$ProductPrice
nl.crolox.labelscout.helper.ProductResponse ..> nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts
nl.crolox.labelscout.helper.ProductKeuze ..> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts ..> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.helper.PreferentieClusterResponse ..> nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_INTERCEPTOR

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_REPOSITORY
nl.crolox.labelscout.repository.LabelRepository ..> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.repository.GroepRepository ..> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.repository.GroothandelVoorraadRepository ..> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.repository.ProductRepository ..> nl.crolox.labelscout.domain.Label
nl.crolox.labelscout.repository.GebruikerRepository ..> nl.crolox.labelscout.domain.Gebruiker
nl.crolox.labelscout.repository.ApotheekRepository ..> nl.crolox.labelscout.domain.Apotheek

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_SERVICE
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.helper.AdviceHelperRequest
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.helper.AdviceHelperResponeLine
nl.crolox.labelscout.service.LabelscoutServiceV1 ..> nl.crolox.labelscout.helper.ProductKeuze
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.helper.ProductKeuze
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.domain.Label
nl.crolox.labelscout.service.ProductAdviesService ..> nl.crolox.labelscout.helper.Product$ProductPrice
nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse ..> nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$Embedded

!endsub


!startsub USES_NL_CROLOX_LABELSCOUT_WEB
nl.crolox.labelscout.web.HomeController ..> nl.crolox.labelscout.domain.Gebruiker$USERROLE
nl.crolox.labelscout.web.Utils ..> nl.crolox.labelscout.domain.Gebruiker$USERROLE
nl.crolox.labelscout.web.ZoekController ..> nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.web.ZoekController ..> nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.web.ZoekController ..> nl.crolox.labelscout.helper.AdviceHelperResponeLine
nl.crolox.labelscout.web.ZoekController ..> nl.crolox.labelscout.helper.ProductKeuze
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.helper.ApotheekHelper
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.helper.LabelHelper
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.helper.GroepHelper
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.domain.Gebruiker$USERROLE
nl.crolox.labelscout.web.AdminPagesController ..> nl.crolox.labelscout.helper.OrderUpdateRequest

!endsub

' IMPORTS =======
' Java Files Path : /Users/paolobrunasti/IdeaProjects/OCTA/labelscout/src/main/java/

!startsub IMPORTS_NL_CROLOX_LABELSCOUT
' nl.crolox.labelscout.KeycloakLogoutHandler
nl.crolox.labelscout.KeycloakLogoutHandler ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.LabelscoutApplication

' nl.crolox.labelscout.SecurityConfig

' nl.crolox.labelscout.SecurityConfig

' nl.crolox.labelscout.KeycloakLogoutHandler

' nl.crolox.labelscout.LabelscoutApplication


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_ASPECT
' nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.aspect.LoggingAspect

' nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.aspect.LoggingAspect


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_DOMAIN
' nl.crolox.labelscout.domain.Apotheek

' nl.crolox.labelscout.domain.Logger

' nl.crolox.labelscout.domain.Label

' nl.crolox.labelscout.domain.Gebruiker

' nl.crolox.labelscout.domain.Groep

' nl.crolox.labelscout.domain.VoorraadCluster

' nl.crolox.labelscout.domain.AuditLog

' nl.crolox.labelscout.domain.Groothandel

' nl.crolox.labelscout.domain.ApotheekGroep

' nl.crolox.labelscout.domain.GroothandelVoorraad

' nl.crolox.labelscout.domain.Gebruiker$USERROLE

' nl.crolox.labelscout.domain.Product

' nl.crolox.labelscout.domain.Apotheek

' nl.crolox.labelscout.domain.AuditLog

' nl.crolox.labelscout.domain.Label

' nl.crolox.labelscout.domain.ApotheekGroep

' nl.crolox.labelscout.domain.Gebruiker

' nl.crolox.labelscout.domain.Product

' nl.crolox.labelscout.domain.GroothandelVoorraad

' nl.crolox.labelscout.domain.Groothandel

' nl.crolox.labelscout.domain.Gebruiker$USERROLE

' nl.crolox.labelscout.domain.VoorraadCluster

' nl.crolox.labelscout.domain.Groep

' nl.crolox.labelscout.domain.Logger


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_HELPER
' nl.crolox.labelscout.helper.AdviceHelperRespone

' nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData

' nl.crolox.labelscout.helper.Product

' nl.crolox.labelscout.helper.AdviceHelperRequest

' nl.crolox.labelscout.helper.ProductResponse

' nl.crolox.labelscout.helper.ProductKeuze
nl.crolox.labelscout.helper.ProductKeuze ..o nl.crolox.labelscout.repository.ProductRepository
nl.crolox.labelscout.helper.ProductKeuze ..o nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.helper.ProductKeuze ..o nl.crolox.labelscout.repository.LabelRepository
nl.crolox.labelscout.helper.ProductKeuze ..o nl.crolox.labelscout.domain.Label

' nl.crolox.labelscout.helper.Product$ProductPrice

' nl.crolox.labelscout.helper.OrderUpdateRequest

' nl.crolox.labelscout.helper.PreferentieClusterResponse$PreferentieClusterData

' nl.crolox.labelscout.helper.VoorraadResponse

' nl.crolox.labelscout.helper.LabelHelper

' nl.crolox.labelscout.helper.AdviceHelperResponeLine

' nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts

' nl.crolox.labelscout.helper.ApotheekHelper

' nl.crolox.labelscout.helper.GroepHelper

' nl.crolox.labelscout.helper.PreferentieClusterResponse

' nl.crolox.labelscout.helper.GroepHelper

' nl.crolox.labelscout.helper.ProductResponse

' nl.crolox.labelscout.helper.ProductKeuze

' nl.crolox.labelscout.helper.AdviceHelperRequest

' nl.crolox.labelscout.helper.LabelHelper

' nl.crolox.labelscout.helper.PreferentieClusterResponse

' nl.crolox.labelscout.helper.PreferentieClusterResponse$EmbeddedData

' nl.crolox.labelscout.helper.AdviceHelperResponeLine

' nl.crolox.labelscout.helper.PreferentieClusterResponse$PreferentieClusterData

' nl.crolox.labelscout.helper.ProductResponse$EmbeddedProducts

' nl.crolox.labelscout.helper.VoorraadResponse

' nl.crolox.labelscout.helper.OrderUpdateRequest

' nl.crolox.labelscout.helper.Product

' nl.crolox.labelscout.helper.Product$ProductPrice

' nl.crolox.labelscout.helper.ApotheekHelper

' nl.crolox.labelscout.helper.AdviceHelperRespone


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_INTERCEPTOR
' nl.crolox.labelscout.interceptor.DaoInterceptor

' nl.crolox.labelscout.interceptor.DaoInterceptor


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_REPOSITORY
' nl.crolox.labelscout.repository.GroothandelRepository
nl.crolox.labelscout.repository.GroothandelRepository ..o nl.crolox.labelscout.domain.VoorraadCluster
nl.crolox.labelscout.repository.GroothandelRepository ..o nl.crolox.labelscout.domain.Groothandel

' nl.crolox.labelscout.repository.LabelRepository

' nl.crolox.labelscout.repository.ApotheekGroepRepository
nl.crolox.labelscout.repository.ApotheekGroepRepository ..o nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.repository.ApotheekGroepRepository ..o nl.crolox.labelscout.domain.VoorraadCluster

' nl.crolox.labelscout.repository.GroepRepository
nl.crolox.labelscout.repository.GroepRepository ..o nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.repository.GroepRepository ..o nl.crolox.labelscout.domain.Groep

' nl.crolox.labelscout.repository.GroothandelVoorraadRepository
nl.crolox.labelscout.repository.GroothandelVoorraadRepository ..o nl.crolox.labelscout.domain.GroothandelVoorraad
nl.crolox.labelscout.repository.GroothandelVoorraadRepository ..o nl.crolox.labelscout.domain.VoorraadCluster
nl.crolox.labelscout.repository.GroothandelVoorraadRepository ..o nl.crolox.labelscout.domain.Groothandel

' nl.crolox.labelscout.repository.ProductRepository

' nl.crolox.labelscout.repository.GebruikerRepository
nl.crolox.labelscout.repository.GebruikerRepository ..o nl.crolox.labelscout.domain.Gebruiker
nl.crolox.labelscout.repository.GebruikerRepository ..o nl.crolox.labelscout.domain.VoorraadCluster

' nl.crolox.labelscout.repository.VoorraadClusterRepository
nl.crolox.labelscout.repository.VoorraadClusterRepository ..o nl.crolox.labelscout.domain.VoorraadCluster

' nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.repository.ApotheekRepository ..o nl.crolox.labelscout.domain.VoorraadCluster
nl.crolox.labelscout.repository.ApotheekRepository ..o nl.crolox.labelscout.domain.Apotheek

' nl.crolox.labelscout.repository.ApotheekRepository

' nl.crolox.labelscout.repository.ProductRepository

' nl.crolox.labelscout.repository.GroepRepository

' nl.crolox.labelscout.repository.LabelRepository

' nl.crolox.labelscout.repository.ApotheekGroepRepository

' nl.crolox.labelscout.repository.VoorraadClusterRepository

' nl.crolox.labelscout.repository.GebruikerRepository

' nl.crolox.labelscout.repository.GroothandelRepository

' nl.crolox.labelscout.repository.GroothandelVoorraadRepository


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_SERVICE
' nl.crolox.labelscout.service.LabelscoutServiceV1
nl.crolox.labelscout.service.LabelscoutServiceV1 ..o nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.service.LabelscoutServiceV1 ..o nl.crolox.labelscout.domain.ApotheekGroep
nl.crolox.labelscout.service.LabelscoutServiceV1 ..o nl.crolox.labelscout.domain.Apotheek
nl.crolox.labelscout.service.LabelscoutServiceV1 ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.domain.Groep
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.repository.LabelRepository
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.domain.Label
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.domain.Groothandel
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.repository.GroothandelVoorraadRepository
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.repository.ProductRepository
nl.crolox.labelscout.service.ProductAdviesService ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$Embedded

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$PreferentieCluster

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$Embedded

' nl.crolox.labelscout.service.LabelscoutServiceV1

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse$PreferentieCluster

' nl.crolox.labelscout.service.ProductAdviesService$PreferentieClusterResponse

' nl.crolox.labelscout.service.ProductAdviesService


!endsub


!startsub IMPORTS_NL_CROLOX_LABELSCOUT_WEB
' nl.crolox.labelscout.web.HomeController
nl.crolox.labelscout.web.HomeController ..o nl.crolox.labelscout.helper.GroepHelper
nl.crolox.labelscout.web.HomeController ..o nl.crolox.labelscout.helper.ApotheekHelper
nl.crolox.labelscout.web.HomeController ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.web.Utils
nl.crolox.labelscout.web.Utils ..o nl.crolox.labelscout.domain.Gebruiker
nl.crolox.labelscout.web.Utils ..o nl.crolox.labelscout.repository.GebruikerRepository

' nl.crolox.labelscout.web.ZoekController
nl.crolox.labelscout.web.ZoekController ..o nl.crolox.labelscout.helper.Product
nl.crolox.labelscout.web.ZoekController ..o nl.crolox.labelscout.repository.ApotheekRepository
nl.crolox.labelscout.web.ZoekController ..o nl.crolox.labelscout.service.ProductAdviesService
nl.crolox.labelscout.web.ZoekController ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.web.AdminPagesController
nl.crolox.labelscout.web.AdminPagesController ..o nl.crolox.labelscout.helper.GroepHelper
nl.crolox.labelscout.web.AdminPagesController ..o nl.crolox.labelscout.helper.LabelHelper
nl.crolox.labelscout.web.AdminPagesController ..o nl.crolox.labelscout.helper.OrderUpdateRequest
nl.crolox.labelscout.web.AdminPagesController ..o nl.crolox.labelscout.helper.ApotheekHelper
nl.crolox.labelscout.web.AdminPagesController ..o nl.crolox.labelscout.aspect.Loggable

' nl.crolox.labelscout.web.ZoekController

' nl.crolox.labelscout.web.AdminPagesController

' nl.crolox.labelscout.web.HomeController

' nl.crolox.labelscout.web.Utils


!endsub


@enduml
