@startuml
'https://plantuml.com/class-diagram

' GENERATE PAGES DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.spring.web.WebFlowAnalyser
' Java Files Path : [/Users/paolobrunasti/IdeaProjects/OCTA/labelscout/src/main/java/]
' Configuration   : [./docs/config.json]
' Generated at    : Tue Jan 13 16:03:13 CET 2026
'
'   Pages infos    :
rectangle "/v1/public/advice" as advice
rectangle "/v1/cgm-advice" as adviceCGM
rectangle "/login/admin/" as adminPage
rectangle "/login/admin/apotheekgroep" as apotheekGroepPage
rectangle "/login/admin/label/{id}" as labelPage
rectangle "/login/admin/label/new/{id}" as labelNewPage
rectangle "/login/admin/label/edit/{id}" as labelEditPage
rectangle "/login/admin/groep" as groepPage
rectangle "/login/admin/groep/new" as groepNewPage
rectangle "/login/admin/groep/{id}" as getGroep
rectangle "/login/admin/apotheek/{id}" as getApotheek
rectangle "/login/admin/apotheekGroep/{id}" as getApotheekGroep
rectangle "/login/admin/apotheek/" as apotheekNewPage
rectangle "/login/admin/apotheekgroep/new" as apotheekGroepNewPage
rectangle "/login/admin/apotheek" as apotheekSubmit
rectangle "/login/admin/apotheekGroep" as apotheekGroepSubmit
rectangle "/login/admin/label" as apotheekGroepSubmit
rectangle "/login/admin/groep" as groepSubmit
rectangle "/login/admin/apotheek/delete/{id}" as deleteApotheek
rectangle "/login/admin/apotheekGroep/delete/{id}" as deleteApotheekGroep
rectangle "/login/admin/groep/delete/{id}" as deleteGroep
rectangle "/login/admin/label/delete/{id}" as deleteLabel
rectangle "/login/admin/label/update-order" as updateOrder
rectangle "/" as homePage
rectangle "/login/" as loginPage
rectangle "/login/notAllowed" as notAllowedPage
rectangle "/login/groupadmin/" as groupAdminPage
rectangle "/login/user/" as userPage
rectangle "/login/user/optipro" as optiproPage
rectangle "/login/zoeken/zoek" as zoekOpZindex


@enduml
