@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "it.brunasti.java.diagrammer.ClassDiagrammer",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_547127440 { 
   	label=brunasti
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1168587968 { 
   	label=java
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   ClassDiagrammer1748953464[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ClassDiagrammer</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   classLoader: ClassLoader [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   usesWritten: HashSet&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- generateDiagram(path: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- initToBeExcluded()</TD></TR>
<TR><TD ALIGN="LEFT" >- isTypeToBeConnected(objectClazz: JavaClass, field: Field): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- isTypeToBeConnected(objectClazz: JavaClass, type: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >- iterateSubDirectories(path: String, localPackage: String): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >- iterateSubDirectories(path: String, localPackage: String, files: Set&lt;String&gt;): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ main(args: String[])</TD></TR>
<TR><TD ALIGN="LEFT" >- writeUses(objectClazz: JavaClass, type: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Utils1748953464[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Utils</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dump(t: String, arr: Object[])</TD></TR>
<TR><TD ALIGN="LEFT" >+ dump(t: String, arr: ArrayList)</TD></TR>
<TR><TD ALIGN="LEFT" >+ dump(t: String, arr: Set)</TD></TR>
<TR><TD ALIGN="LEFT" >+ listDirectories(dir: String): Set&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ listFilesUsingFilesList(dir: String): Set&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    

    
}
@enduml