@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [./target/classes]
' Configuration   : [./docs/config-includeFile.json]
' Generated at    : Thu Jan 16 10:21:26 CET 2025

' Include         : [./docs/includedFile.txt] ---------
title Example with legend and title

hide empty members


legend
Connections legend
----
--|> : Extends
..|> : Implements
----
--> : Fields and Attributes
..> : Uses
end legend
' Include end     : --------------------------



' CLASSES =======
class it.brunasti.java.diagrammer.ClassDiagrammer
class it.brunasti.java.diagrammer.Utils
interface it.brunasti.java.diagrammer.package-info
class it.brunasti.java.diagrammer.Debugger
class it.brunasti.java.diagrammer.ClassDiagrammerMain
class it.brunasti.java.diagrammer.ImportsIdentifier
class it.brunasti.java.diagrammer.DiagramPlotter

' INHERITANCES =======

' IMPLEMENT INTERFACE =======

' FIELDS =======
it.brunasti.java.diagrammer.ClassDiagrammer --> java.io.PrintStream
it.brunasti.java.diagrammer.ClassDiagrammerMain --> org.apache.commons.cli.CommandLine
it.brunasti.java.diagrammer.ClassDiagrammerMain --> it.brunasti.java.diagrammer.ClassDiagrammer
it.brunasti.java.diagrammer.ClassDiagrammerMain --> org.apache.commons.cli.Options

' USES =======
it.brunasti.java.diagrammer.ClassDiagrammer ..> java.io.PrintStream
it.brunasti.java.diagrammer.ClassDiagrammer ..> org.json.simple.JSONObject
it.brunasti.java.diagrammer.ClassDiagrammer ..> org.apache.bcel.classfile.JavaClass
it.brunasti.java.diagrammer.ClassDiagrammer ..> org.apache.bcel.classfile.Field
it.brunasti.java.diagrammer.ClassDiagrammer ..> org.apache.bcel.util.ClassLoaderRepository
it.brunasti.java.diagrammer.ClassDiagrammer ..> it.brunasti.java.diagrammer.ImportsIdentifier
it.brunasti.java.diagrammer.Utils ..> java.io.PrintStream
it.brunasti.java.diagrammer.Utils ..> org.json.simple.JSONObject
it.brunasti.java.diagrammer.ClassDiagrammerMain ..> org.apache.commons.cli.Options
it.brunasti.java.diagrammer.DiagramPlotter ..> java.nio.file.Path

' IMPORTS =======
' Java Files Path : 


@enduml
