@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [./target/test-classes]
' Configuration   : [./docs/config-includeFile.json]
' Generated at    : Wed Apr 03 10:36:29 CEST 2024

' Include         : [./docs/includedFile.txt] ---------
title Example with legend and title

hide empty members


legend
Connections legend
----
--|> : Extends
..|> : Implements
----
--> : Fields and Attributes
..> : Uses
end legend
' Include end     : --------------------------



' CLASSES =======
class it.brunasti.java.diagrammer.ClassDiagrammerTest
class it.brunasti.java.diagrammer.UtilsTest
interface it.brunasti.java.diagrammer.TestConstants
class it.brunasti.java.diagrammer.ImportsIdentifierTest
class it.brunasti.java.diagrammer.teststructure.TestExtendedClass
class it.brunasti.java.diagrammer.teststructure.TestOtherClass
class it.brunasti.java.diagrammer.DocumentGenerationTest
class it.brunasti.java.diagrammer.DiagramPlotterTest
abstract it.brunasti.java.diagrammer.teststructure.TestAbstractClass
class it.brunasti.java.diagrammer.teststructure.TestBaseClass
enum it.brunasti.java.diagrammer.teststructure.TestEnumClass{
  FIRST
  SECOND
  THIRD
}
class it.brunasti.java.diagrammer.ClassDiagrammerMainTest
class it.brunasti.java.diagrammer.DebuggerTest

' INHERITANCES =======
it.brunasti.java.diagrammer.teststructure.TestBaseClass <|-- it.brunasti.java.diagrammer.teststructure.TestExtendedClass
it.brunasti.java.diagrammer.teststructure.TestAbstractClass <|-- it.brunasti.java.diagrammer.teststructure.TestOtherClass
it.brunasti.java.diagrammer.teststructure.TestAbstractClass <|-- it.brunasti.java.diagrammer.teststructure.TestBaseClass
java.lang.Enum <|-- it.brunasti.java.diagrammer.teststructure.TestEnumClass

' IMPLEMENT INTERFACE =======
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.ClassDiagrammerTest
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.UtilsTest
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.ImportsIdentifierTest
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.teststructure.TestOtherClass
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.DocumentGenerationTest
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.teststructure.TestBaseClass
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.ClassDiagrammerMainTest
it.brunasti.java.diagrammer.TestConstants <|.. it.brunasti.java.diagrammer.DebuggerTest

' FIELDS =======
it.brunasti.java.diagrammer.teststructure.TestOtherClass --> it.brunasti.java.diagrammer.teststructure.TestBaseClass
it.brunasti.java.diagrammer.teststructure.TestOtherClass --> it.brunasti.java.diagrammer.teststructure.TestEnumClass
it.brunasti.java.diagrammer.teststructure.TestBaseClass --> it.brunasti.java.diagrammer.teststructure.TestEnumClass

' USES =======
it.brunasti.java.diagrammer.ClassDiagrammerTest ..> it.brunasti.java.diagrammer.ClassDiagrammer
it.brunasti.java.diagrammer.UtilsTest ..> it.brunasti.java.diagrammer.Utils
it.brunasti.java.diagrammer.ImportsIdentifierTest ..> it.brunasti.java.diagrammer.ImportsIdentifier
it.brunasti.java.diagrammer.DocumentGenerationTest ..> it.brunasti.java.diagrammer.DiagramPlotter
it.brunasti.java.diagrammer.DiagramPlotterTest ..> it.brunasti.java.diagrammer.DiagramPlotter
it.brunasti.java.diagrammer.ClassDiagrammerMainTest ..> it.brunasti.java.diagrammer.ClassDiagrammerMain
it.brunasti.java.diagrammer.ClassDiagrammerMainTest ..> org.apache.commons.cli.Options
it.brunasti.java.diagrammer.DebuggerTest ..> it.brunasti.java.diagrammer.Debugger

' IMPORTS =======
' Java Files Path : 


@enduml
