@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.spring.web.WebFlowAnalyser
' Java Files Path : [./src/test/java/]
' Configuration   : [./docs/config.json]
' Generated at    : Tue Jan 13 13:33:54 CET 2026
'
'   Stat infos    :


@enduml
