@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-payment-service/build/classes/java/main]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-payment-service/src/main/java/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Fri Jan 17 20:03:26 CET 2025
'
'   Stat infos    :
'       Files : [165]
'       Lines : [5906]
'     Classes : [164]
'     Methods : [1367]
'      Fields : [680]



' CLASSES =======
class com.freelanceplaza.payment.config.OppConfiguration$StageConfig
enum com.freelanceplaza.payment.enums.PaymentAccountStatus{
  PENDING
  ACTIVE
  INACTIVE
  UNVERIFIED
  SUSPENDED
  BLOCKED
  DELETED
}
class com.freelanceplaza.payment.utils.DateFormatter
class com.freelanceplaza.payment.exceptions.ErrorResponse
class com.freelanceplaza.payment.config.JacksonConfig$FpInstantSerializer
interface com.freelanceplaza.payment.repositories.InvoiceRepository
class com.freelanceplaza.payment.exceptions.EntityNotFoundException
class com.freelanceplaza.payment.config.aws.SQSConfig
interface com.freelanceplaza.payment.opp.dtos.IOppTransaction
class com.freelanceplaza.payment.producers.OppFreelancerProfileMessage
class com.freelanceplaza.payment.opp.OppPort$MultipartEntityBuilderWrapper
class com.freelanceplaza.payment.dtos.PaymentAccountDto
class com.freelanceplaza.payment.services.CustomerService$Customer
class com.freelanceplaza.payment.entities.User
class com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
interface com.freelanceplaza.payment.opp.repositories.OppNotificationLogRepository
class com.freelanceplaza.payment.config.aws.SNSConfig
class com.freelanceplaza.payment.opp.OppPort
abstract com.freelanceplaza.payment.entities.PaymentAccount
class com.freelanceplaza.payment.services.CustomerService
class com.freelanceplaza.payment.services.utils.SecurityUtils
class com.freelanceplaza.payment.opp.dtos.RequirementDto
class com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
class com.freelanceplaza.payment.entities.Organization
class com.freelanceplaza.payment.producers.CreateTransactionBundleProducer
class com.freelanceplaza.payment.opp.dtos.BankAccountDto
enum com.freelanceplaza.payment.enums.Units{
  MONEY
  MINUTES
  PERCENTAGE
  HOURS
  DAYS
  DATE
}
class com.freelanceplaza.payment.entities.OppRequirement
class com.freelanceplaza.payment.opp.dtos.DisapprovalDto
class com.freelanceplaza.payment.opp.dtos.MetadataDto
class com.freelanceplaza.payment.entities.Invoice
class com.freelanceplaza.payment.services.BucketService
interface com.freelanceplaza.payment.opp.repositories.OppAccountRepository
class com.freelanceplaza.payment.opp.dtos.ComplianceDto
class com.freelanceplaza.payment.opp.OppTransactionService
class com.freelanceplaza.payment.services.ReferenceMockGenerator
class com.freelanceplaza.payment.entities.OppAccountDeduction
class com.freelanceplaza.payment.entities.Product
class com.freelanceplaza.payment.exceptions.ConfigException
enum com.freelanceplaza.payment.enums.TransactionStatus{
  READY_TO_CREATE
  CREATED
  PENDING
  COMPLETED
  CANCELLED
  EXPIRED
  FAILED
  UNKNOWN
}
interface com.freelanceplaza.payment.repositories.TransactionRepository
class com.freelanceplaza.payment.listeners.WorkFinishedListener
enum com.freelanceplaza.payment.enums.OppKycDeductionStatus{
  NOT_STARTED
  CREATED
  COMPLETED
}
class com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails
enum com.freelanceplaza.payment.services.ReferenceMockGenerator$CharType{
  UPPER
  NUMBER
}
class com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener
class com.freelanceplaza.payment.config.RedisConfiguration
class com.freelanceplaza.payment.config.OppConfiguration$BankConfig
class com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
class com.freelanceplaza.payment.config.aws.S3Config
class com.freelanceplaza.payment.utils.PaymentDetailsDeserializer
class com.freelanceplaza.payment.services.PaymentAssignmentService
interface com.freelanceplaza.payment.repositories.ProductRepository
class com.freelanceplaza.payment.entities.OppCompliance
class com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto
class com.freelanceplaza.payment.opp.dtos.OppTransactionDto
class com.freelanceplaza.payment.entities.PaymentAssignment
class com.freelanceplaza.payment.utils.OppUtils
class com.freelanceplaza.payment.services.OrganizationService
class com.freelanceplaza.payment.dtos.ConfigDto
class com.freelanceplaza.payment.opp.OppService
class com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
class com.freelanceplaza.payment.listeners.RunBundledTransactionListener
class com.freelanceplaza.payment.producers.CreateOppAccountProducer
class com.freelanceplaza.payment.security.OppNotificationFilter
interface com.freelanceplaza.payment.repositories.LocationRepository
class com.freelanceplaza.payment.services.CustomerService$CustomerIdentifier
class com.freelanceplaza.payment.config.OppConfiguration$UriConfig
class com.freelanceplaza.payment.services.OppDataCollector
class com.freelanceplaza.payment.config.aws.S3ConfigDev
interface com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository
abstract com.freelanceplaza.payment.entities.Transaction
interface com.freelanceplaza.payment.repositories.PaymentAccountRepository
class com.freelanceplaza.payment.entities.config.ConfigHistory
class com.freelanceplaza.payment.opp.entities.OppNotificationLog
class com.freelanceplaza.payment.config.security.SecurityConfig
class com.freelanceplaza.payment.PaymentApplication
class com.freelanceplaza.payment.services.ReferenceMockGenerator$1
class com.freelanceplaza.payment.listeners.LocationSyncListener
enum com.freelanceplaza.payment.enums.ConfigSource{
  INVOICE
}
class com.freelanceplaza.payment.controllers.PaymentAssignmentController
class com.freelanceplaza.payment.listeners.CreateTransactionBundleListener
class com.freelanceplaza.payment.entities.InvoiceBundle
class com.freelanceplaza.payment.services.impl.ConfigServiceImpl
class com.freelanceplaza.payment.config.ApplicationConfiguration
class com.freelanceplaza.payment.services.PaymentAccountService
enum com.freelanceplaza.payment.enums.PaymentMethod{
  SEPA
  IDEAL
}
class com.freelanceplaza.payment.exceptions.PaymentServiceException
class com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
class com.freelanceplaza.payment.services.UserService
class com.freelanceplaza.payment.entities.Location
class com.freelanceplaza.payment.opp.dtos.OppTransactionStatus
class com.freelanceplaza.payment.opp.dtos.ProfileDto
enum com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels{
  CREATED
  FAILED
  EXPIRED
  TERMS_EXPIRED
  COMPLETED
}
interface com.freelanceplaza.payment.repositories.ConfigRepository
class com.freelanceplaza.payment.listeners.OrganizationSyncListener
class com.freelanceplaza.payment.controllers.AccountController
class com.freelanceplaza.payment.config.aws.SQSConfig$FPDefaultListenerContainerRegistry
class com.freelanceplaza.payment.listeners.CompletedInvoiceListener
class com.freelanceplaza.payment.opp.dtos.NotificationDto
class com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto
class com.freelanceplaza.payment.listeners.CreateOppAccountListener
class com.freelanceplaza.payment.listeners.UserSyncListener
class com.freelanceplaza.payment.opp.OppTransactionService$2
class com.freelanceplaza.payment.services.WorkFinishedService
class com.freelanceplaza.payment.opp.OppTransactionService$1
class com.freelanceplaza.payment.producers.RunBundledTransactionProducer
class com.freelanceplaza.payment.opp.OppTransactionService$3
class com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification
class com.freelanceplaza.payment.producers.CreateOppAccountProducer$CreateOppAccountEvent
class com.freelanceplaza.payment.config.security.AuthConfiguration
class com.freelanceplaza.payment.entities.OppTransaction
class com.freelanceplaza.payment.config.ApiPortConfiguration
interface com.freelanceplaza.payment.repositories.OrganizationRepository
enum com.freelanceplaza.payment.enums.OppStatus{
  UNVERIFIED
  PENDING
  VERIFIED
  LIVE
  TERMINATED
  SUSPENDED
  BLOCKED
  DELETED
  NEW
  DISAPPROVED
  APPROVED
}
class com.freelanceplaza.payment.entities.OppAccount
class com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
class com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
interface com.freelanceplaza.payment.services.ConfigService
class com.freelanceplaza.payment.exceptions.GlobalExceptionHandler
class com.freelanceplaza.payment.opp.OppLogService
interface com.freelanceplaza.payment.repositories.OppTransactionRepository
class com.freelanceplaza.payment.entities.DisapprovalReasonLabel
class com.freelanceplaza.payment.services.LocationService
class com.freelanceplaza.payment.opp.dtos.OppRequestLogDto
class com.freelanceplaza.payment.config.JacksonConfig
class com.freelanceplaza.payment.entities.config.Config
class com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage
interface com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
enum com.freelanceplaza.payment.enums.ProductType{
  INVOICE
}
class com.freelanceplaza.payment.config.ApiPortConfiguration$ServiceConfiguration
class com.freelanceplaza.payment.config.OppConfiguration
class com.freelanceplaza.payment.enums.PaymentSystem
class com.freelanceplaza.payment.controllers.M2mController
class com.freelanceplaza.payment.controllers.OppController
class com.freelanceplaza.payment.dtos.DisapprovalDto
class com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener
class com.freelanceplaza.payment.opp.KYCDeductionConfig
enum com.freelanceplaza.payment.enums.OppTransactionType{
  MULTI
  SINGLE
}
class com.freelanceplaza.payment.services.InvoiceService
class com.freelanceplaza.payment.opp.OppService$1
interface com.freelanceplaza.payment.repositories.UserRepository
class com.freelanceplaza.payment.opp.OppPort$5
class com.freelanceplaza.payment.opp.dtos.MerchantDto
class com.freelanceplaza.payment.opp.dtos.ContactDto
class com.freelanceplaza.payment.opp.OppPort$6
class com.freelanceplaza.payment.opp.OppPort$3
class com.freelanceplaza.payment.opp.OppPort$4
class com.freelanceplaza.payment.config.aws.SqsBootstrapConfiguration
class com.freelanceplaza.payment.opp.OppPort$1
class com.freelanceplaza.payment.opp.OppPort$2
class com.freelanceplaza.payment.opp.MerchantConfig
interface com.freelanceplaza.payment.opp.repositories.OppRequestLogRepository
class com.freelanceplaza.payment.entities.OppDisapproval
class com.freelanceplaza.payment.opp.entities.OppRequestLog
class com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
class com.freelanceplaza.payment.opp.dtos.ProductDto
class com.freelanceplaza.payment.opp.OppPort$9
class com.freelanceplaza.payment.services.InvoiceService$1
class com.freelanceplaza.payment.opp.OppPort$7
class com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
class com.freelanceplaza.payment.opp.OppPort$8
interface com.freelanceplaza.payment.repositories.InvoiceBundleRepository
class com.freelanceplaza.payment.dtos.RequirementDto

' INHERITANCES =======
java.lang.Enum <|-- com.freelanceplaza.payment.enums.PaymentAccountStatus
java.lang.RuntimeException <|-- com.freelanceplaza.payment.exceptions.EntityNotFoundException
java.lang.Enum <|-- com.freelanceplaza.payment.enums.Units
java.lang.RuntimeException <|-- com.freelanceplaza.payment.exceptions.ConfigException
java.lang.Enum <|-- com.freelanceplaza.payment.enums.TransactionStatus
java.lang.Enum <|-- com.freelanceplaza.payment.enums.OppKycDeductionStatus
java.lang.Enum <|-- com.freelanceplaza.payment.services.ReferenceMockGenerator$CharType
com.freelanceplaza.payment.config.aws.S3Config <|-- com.freelanceplaza.payment.config.aws.S3ConfigDev
java.lang.Enum <|-- com.freelanceplaza.payment.enums.ConfigSource
java.lang.Enum <|-- com.freelanceplaza.payment.enums.PaymentMethod
java.lang.RuntimeException <|-- com.freelanceplaza.payment.exceptions.PaymentServiceException
java.lang.Enum <|-- com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels
com.freelanceplaza.payment.entities.Transaction <|-- com.freelanceplaza.payment.entities.OppTransaction
java.lang.Enum <|-- com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.PaymentAccount <|-- com.freelanceplaza.payment.entities.OppAccount
java.lang.Enum <|-- com.freelanceplaza.payment.enums.ProductType
java.lang.Enum <|-- com.freelanceplaza.payment.enums.OppTransactionType

' IMPLEMENT INTERFACE =======
com.freelanceplaza.payment.opp.dtos.IOppTransaction <|.. com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
com.freelanceplaza.payment.opp.dtos.IOppTransaction <|.. com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto
com.freelanceplaza.payment.opp.dtos.IOppTransaction <|.. com.freelanceplaza.payment.opp.dtos.OppTransactionDto
com.freelanceplaza.payment.services.ConfigService <|.. com.freelanceplaza.payment.services.impl.ConfigServiceImpl

' FIELDS =======
com.freelanceplaza.payment.dtos.PaymentAccountDto --> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.dtos.PaymentAccountDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.services.CustomerService$Customer --> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.User --> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.opp.OppPort --> com.freelanceplaza.payment.config.OppConfiguration$UriConfig
com.freelanceplaza.payment.opp.OppPort --> com.freelanceplaza.payment.config.OppConfiguration$StageConfig
com.freelanceplaza.payment.entities.PaymentAccount --> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.entities.PaymentAccount --> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.services.CustomerService --> com.freelanceplaza.payment.services.OppDataCollector
com.freelanceplaza.payment.entities.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationStatus
com.freelanceplaza.payment.entities.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationType
com.freelanceplaza.payment.entities.OppRequirement --> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppRequirement --> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppRequirement --> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.entities.Invoice --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.Invoice --> com.freelanceplaza.payment.entities.InvoiceBundle
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.services.CustomerService
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.repositories.InvoiceRepository
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.repositories.ProductRepository
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.repositories.OppTransactionRepository
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.producers.RunBundledTransactionProducer
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.services.ReferenceMockGenerator
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.config.OppConfiguration
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.services.OppDataCollector
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
com.freelanceplaza.payment.opp.OppTransactionService --> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.entities.OppAccountDeduction --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.OppAccountDeduction --> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.entities.OppAccountDeduction --> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.entities.Product --> com.freelanceplaza.payment.enums.ProductType
com.freelanceplaza.payment.listeners.WorkFinishedListener --> com.freelanceplaza.payment.services.BucketService
com.freelanceplaza.payment.listeners.WorkFinishedListener --> com.freelanceplaza.payment.services.WorkFinishedService
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener --> com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto --> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.services.PaymentAssignmentService --> com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
com.freelanceplaza.payment.services.PaymentAssignmentService --> com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
com.freelanceplaza.payment.services.PaymentAssignmentService --> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.entities.OppCompliance --> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppCompliance --> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto --> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.opp.dtos.OppTransactionDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.PaymentAssignment --> com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
com.freelanceplaza.payment.entities.PaymentAssignment --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.PaymentAssignment --> com.freelanceplaza.payment.entities.Transaction
com.freelanceplaza.payment.entities.PaymentAssignment --> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.services.OrganizationService --> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.OrganizationService --> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.dtos.ConfigDto --> com.freelanceplaza.payment.enums.Units
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.opp.MerchantConfig
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.opp.OppService --> com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto --> com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels
com.freelanceplaza.payment.listeners.RunBundledTransactionListener --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.services.CustomerService$CustomerIdentifier --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.services.OppDataCollector --> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.OppDataCollector --> com.freelanceplaza.payment.repositories.LocationRepository
com.freelanceplaza.payment.services.OppDataCollector --> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.services.OppDataCollector --> com.freelanceplaza.payment.repositories.ProductRepository
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.enums.PaymentMethod
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.enums.TransactionStatus
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.entities.Transaction
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.Transaction --> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.entities.config.ConfigHistory --> com.freelanceplaza.payment.entities.config.Config
com.freelanceplaza.payment.listeners.LocationSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.listeners.LocationSyncListener --> com.freelanceplaza.payment.services.LocationService
com.freelanceplaza.payment.controllers.PaymentAssignmentController --> com.freelanceplaza.payment.services.PaymentAssignmentService
com.freelanceplaza.payment.listeners.CreateTransactionBundleListener --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.services.impl.ConfigServiceImpl --> com.freelanceplaza.payment.repositories.ConfigRepository
com.freelanceplaza.payment.services.PaymentAccountService --> com.freelanceplaza.payment.repositories.PaymentAccountRepository
com.freelanceplaza.payment.services.PaymentAccountService --> com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository
com.freelanceplaza.payment.services.UserService --> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.entities.Location --> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.opp.dtos.ProfileDto --> com.freelanceplaza.payment.opp.dtos.BankAccountDto
com.freelanceplaza.payment.listeners.OrganizationSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.listeners.OrganizationSyncListener --> com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.controllers.AccountController --> com.freelanceplaza.payment.services.PaymentAccountService
com.freelanceplaza.payment.listeners.CompletedInvoiceListener --> com.freelanceplaza.payment.services.InvoiceService
com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto --> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.listeners.CreateOppAccountListener --> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.listeners.CreateOppAccountListener --> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.listeners.UserSyncListener --> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.listeners.UserSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.opp.OppTransactionService$2 --> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.opp.OppTransactionService$2 --> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.opp.OppTransactionService$2 --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.UserServiceSyncPort
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.services.WorkFinishedService --> com.freelanceplaza.payment.producers.CreateOppAccountProducer
com.freelanceplaza.payment.opp.OppTransactionService$1 --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.opp.OppTransactionService$3 --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification --> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.config.security.AuthConfiguration --> com.freelanceplaza.commons.fpauthentication.config.AudienceConfig
com.freelanceplaza.payment.config.security.AuthConfiguration --> com.freelanceplaza.commons.fpauthentication.config.AuthDecoderConfig
com.freelanceplaza.payment.entities.OppTransaction --> com.freelanceplaza.payment.enums.OppTransactionType
com.freelanceplaza.payment.entities.OppTransaction --> com.freelanceplaza.payment.entities.OppAccountDeduction
com.freelanceplaza.payment.entities.OppAccount --> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppAccount --> com.freelanceplaza.payment.enums.OppKycDeductionStatus
com.freelanceplaza.payment.entities.OppAccount --> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.opp.OppLogService --> com.freelanceplaza.payment.opp.repositories.OppRequestLogRepository
com.freelanceplaza.payment.opp.OppLogService --> com.freelanceplaza.payment.opp.repositories.OppNotificationLogRepository
com.freelanceplaza.payment.opp.OppLogService --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.opp.OppLogService --> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.payment.services.LocationService --> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.LocationService --> com.freelanceplaza.payment.repositories.LocationRepository
com.freelanceplaza.payment.entities.config.Config --> com.freelanceplaza.payment.enums.Units
com.freelanceplaza.payment.entities.config.Config --> com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage --> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.config.OppConfiguration --> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.config.OppConfiguration --> com.freelanceplaza.payment.config.OppConfiguration$StageConfig
com.freelanceplaza.payment.config.OppConfiguration --> com.freelanceplaza.payment.enums.PaymentMethod
com.freelanceplaza.payment.controllers.M2mController --> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.controllers.M2mController --> com.freelanceplaza.payment.services.PaymentAssignmentService
com.freelanceplaza.payment.controllers.M2mController --> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.controllers.OppController --> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.controllers.OppController --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener --> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.services.InvoiceService --> com.freelanceplaza.payment.repositories.InvoiceRepository
com.freelanceplaza.payment.services.InvoiceService --> com.freelanceplaza.payment.repositories.InvoiceBundleRepository
com.freelanceplaza.payment.services.InvoiceService --> com.freelanceplaza.payment.producers.CreateTransactionBundleProducer
com.freelanceplaza.payment.opp.OppPort$5 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.dtos.MerchantDto --> com.freelanceplaza.payment.opp.dtos.ComplianceDto
com.freelanceplaza.payment.opp.OppPort$6 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$3 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$4 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$1 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$2 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.entities.OppDisapproval --> com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.opp.OppPort$9 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.services.InvoiceService$1 --> com.freelanceplaza.payment.entities.InvoiceBundle
com.freelanceplaza.payment.services.InvoiceService$1 --> com.freelanceplaza.payment.services.InvoiceService
com.freelanceplaza.payment.opp.OppPort$7 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$8 --> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.dtos.RequirementDto --> com.freelanceplaza.payment.enums.PaymentAccountStatus

' USES =======
com.freelanceplaza.payment.config.OppConfiguration$StageConfig ..> com.freelanceplaza.payment.config.OppConfiguration$StageConfig
com.freelanceplaza.payment.exceptions.ErrorResponse ..> com.freelanceplaza.payment.exceptions.ErrorResponse
com.freelanceplaza.payment.config.aws.SQSConfig ..> com.freelanceplaza.payment.producers.CreateOppAccountProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..> com.freelanceplaza.payment.producers.CreateTransactionBundleProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..> com.freelanceplaza.payment.producers.RunBundledTransactionProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..> com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.producers.OppFreelancerProfileMessage ..> com.freelanceplaza.payment.producers.OppFreelancerProfileMessage
com.freelanceplaza.payment.opp.OppPort$MultipartEntityBuilderWrapper ..> com.freelanceplaza.payment.opp.OppPort$MultipartEntityBuilderWrapper
com.freelanceplaza.payment.dtos.PaymentAccountDto ..> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.dtos.PaymentAccountDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAccountDto ..> com.freelanceplaza.payment.dtos.PaymentAccountDto
com.freelanceplaza.payment.services.CustomerService$Customer ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.User ..> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.payment.entities.User ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
com.freelanceplaza.payment.config.aws.SNSConfig ..> com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..> com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..> com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.config.OppConfiguration$UriConfig
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.config.OppConfiguration$StageConfig
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.MerchantDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.MerchantConfig
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.ContactDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.BankAccountDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.dtos.OppTransactionDto
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.opp.OppPort$MultipartEntityBuilderWrapper
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.payment.entities.Product
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.commons.fphttpclient.ports.AbstractApiPort$HttpRequestWrapper
com.freelanceplaza.payment.opp.OppPort ..> com.freelanceplaza.commons.fphttpclient.ports.AbstractApiPort$HttpResponseWrapper
com.freelanceplaza.payment.entities.PaymentAccount ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.entities.PaymentAccount ..> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.entities.PaymentAccount ..> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.services.CustomerService ..> com.freelanceplaza.payment.services.OppDataCollector
com.freelanceplaza.payment.services.CustomerService ..> com.freelanceplaza.payment.entities.Location
com.freelanceplaza.payment.services.CustomerService ..> com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.services.CustomerService ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.opp.dtos.RequirementDto ..> com.freelanceplaza.payment.opp.dtos.RequirementDto
com.freelanceplaza.payment.producers.OppKycDeductionEventProducer ..> com.freelanceplaza.invoices.dtos.KycDeductionEvent
com.freelanceplaza.payment.entities.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationStatus
com.freelanceplaza.payment.entities.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationType
com.freelanceplaza.payment.entities.Organization ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.opp.dtos.BankAccountDto ..> com.freelanceplaza.payment.opp.dtos.BankAccountDto
com.freelanceplaza.payment.entities.OppRequirement ..> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppRequirement ..> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.entities.OppRequirement ..> com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.opp.dtos.DisapprovalDto ..> com.freelanceplaza.payment.opp.dtos.DisapprovalDto
com.freelanceplaza.payment.opp.dtos.MetadataDto ..> com.freelanceplaza.payment.opp.dtos.MetadataDto
com.freelanceplaza.payment.entities.Invoice ..> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.entities.Invoice ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.Invoice ..> com.freelanceplaza.payment.entities.InvoiceBundle
com.freelanceplaza.payment.entities.Invoice ..> com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.opp.dtos.ComplianceDto ..> com.freelanceplaza.payment.opp.dtos.ComplianceDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.services.CustomerService$Customer
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.IOppTransaction
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.OppTransactionDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.services.CustomerService
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.repositories.InvoiceRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.repositories.ProductRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.repositories.OppTransactionRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.producers.RunBundledTransactionProducer
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.services.ReferenceMockGenerator
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.config.OppConfiguration
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.services.OppDataCollector
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.opp.dtos.MetadataDto
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.Transaction
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.OppAccountDeduction
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.Product
com.freelanceplaza.payment.opp.OppTransactionService ..> com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.services.ReferenceMockGenerator ..> C
com.freelanceplaza.payment.services.ReferenceMockGenerator ..> com.freelanceplaza.payment.services.ReferenceMockGenerator$CharType
com.freelanceplaza.payment.entities.OppAccountDeduction ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.OppAccountDeduction ..> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.entities.OppAccountDeduction ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.entities.OppAccountDeduction ..> com.freelanceplaza.payment.entities.OppAccountDeduction
com.freelanceplaza.payment.entities.Product ..> com.freelanceplaza.payment.enums.ProductType
com.freelanceplaza.payment.entities.Product ..> com.freelanceplaza.payment.entities.Product
com.freelanceplaza.payment.listeners.WorkFinishedListener ..> com.freelanceplaza.payment.services.BucketService
com.freelanceplaza.payment.listeners.WorkFinishedListener ..> com.freelanceplaza.payment.services.WorkFinishedService
com.freelanceplaza.payment.listeners.WorkFinishedListener ..> com.freelanceplaza.commons.fpcommons.converters.CustomColumnPositionMappingStrategy
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener ..> com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener ..> com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.config.RedisConfiguration ..> com.freelanceplaza.commons.fpcommons.caching.JedisPoolWrapper
com.freelanceplaza.payment.config.RedisConfiguration ..> com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.config.RedisConfiguration ..> com.freelanceplaza.payment.config.RedisConfiguration
com.freelanceplaza.payment.config.OppConfiguration$BankConfig ..> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto ..> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto ..> com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
com.freelanceplaza.payment.utils.PaymentDetailsDeserializer ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.services.PaymentAssignmentService ..> com.freelanceplaza.payment.exceptions.EntityNotFoundException
com.freelanceplaza.payment.entities.OppCompliance ..> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppCompliance ..> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.entities.OppCompliance ..> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto ..> com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto
com.freelanceplaza.payment.opp.dtos.OppTransactionDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.opp.dtos.OppTransactionDto ..> com.freelanceplaza.payment.opp.dtos.OppTransactionDto
com.freelanceplaza.payment.entities.PaymentAssignment ..> com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
com.freelanceplaza.payment.entities.PaymentAssignment ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.PaymentAssignment ..> com.freelanceplaza.payment.entities.Transaction
com.freelanceplaza.payment.entities.PaymentAssignment ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.PaymentAssignment ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.utils.OppUtils ..> com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.utils.OppUtils ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.services.OrganizationService ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSync
com.freelanceplaza.payment.services.OrganizationService ..> com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.payment.services.OrganizationService ..> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.OrganizationService ..> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.dtos.ConfigDto ..> com.freelanceplaza.payment.enums.Units
com.freelanceplaza.payment.dtos.ConfigDto ..> com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.MerchantDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.ComplianceDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.entities.OppDisapproval
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.DisapprovalDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.KYCDeductionConfig
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.MerchantConfig
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.RequirementDto
com.freelanceplaza.payment.opp.OppService ..> com.freelanceplaza.payment.opp.dtos.ContactDto
com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto ..> com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels
com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto ..> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.listeners.RunBundledTransactionListener ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.security.OppNotificationFilter ..> com.freelanceplaza.payment.security.OppNotificationFilter
com.freelanceplaza.payment.services.CustomerService$CustomerIdentifier ..> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.config.OppConfiguration$UriConfig ..> com.freelanceplaza.payment.config.OppConfiguration$UriConfig
com.freelanceplaza.payment.services.OppDataCollector ..> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.OppDataCollector ..> com.freelanceplaza.payment.repositories.LocationRepository
com.freelanceplaza.payment.services.OppDataCollector ..> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.services.OppDataCollector ..> com.freelanceplaza.payment.repositories.ProductRepository
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.enums.PaymentMethod
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.enums.TransactionStatus
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.entities.Transaction
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.Transaction ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.entities.config.ConfigHistory ..> com.freelanceplaza.payment.entities.config.Config
com.freelanceplaza.payment.entities.config.ConfigHistory ..> com.freelanceplaza.payment.entities.config.ConfigHistory
com.freelanceplaza.payment.opp.entities.OppNotificationLog ..> com.freelanceplaza.payment.opp.entities.OppNotificationLog
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.RequiredClaimFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.payment.security.OppNotificationFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient
com.freelanceplaza.payment.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.listeners.LocationSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.listeners.LocationSyncListener ..> com.freelanceplaza.payment.services.LocationService
com.freelanceplaza.payment.controllers.PaymentAssignmentController ..> com.freelanceplaza.payment.services.PaymentAssignmentService
com.freelanceplaza.payment.listeners.CreateTransactionBundleListener ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.entities.InvoiceBundle ..> com.freelanceplaza.payment.entities.InvoiceBundle
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..> com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..> com.freelanceplaza.payment.entities.config.Config
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..> com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..> com.freelanceplaza.payment.repositories.ConfigRepository
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..> com.freelanceplaza.payment.exceptions.ConfigException
com.freelanceplaza.payment.config.ApplicationConfiguration ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.config.ApplicationConfiguration ..> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.repositories.PaymentAccountRepository
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.dtos.PaymentAccountDto
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.dtos.RequirementDto
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.dtos.DisapprovalDto
com.freelanceplaza.payment.services.PaymentAccountService ..> com.freelanceplaza.payment.entities.OppDisapproval
com.freelanceplaza.payment.producers.OppFreelancerProfileProducer ..> com.freelanceplaza.payment.producers.OppFreelancerProfileMessage
com.freelanceplaza.payment.services.UserService ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.services.UserService ..> com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.payment.services.UserService ..> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.entities.Location ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.entities.Location ..> com.freelanceplaza.payment.entities.Location
com.freelanceplaza.payment.opp.dtos.OppTransactionStatus ..> com.freelanceplaza.payment.opp.dtos.OppTransactionStatus
com.freelanceplaza.payment.opp.dtos.ProfileDto ..> com.freelanceplaza.payment.opp.dtos.BankAccountDto
com.freelanceplaza.payment.opp.dtos.ProfileDto ..> com.freelanceplaza.payment.opp.dtos.ProfileDto
com.freelanceplaza.payment.repositories.ConfigRepository ..> com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.listeners.OrganizationSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.listeners.OrganizationSyncListener ..> com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.controllers.AccountController ..> com.freelanceplaza.payment.services.PaymentAccountService
com.freelanceplaza.payment.listeners.CompletedInvoiceListener ..> com.freelanceplaza.invoices.dtos.InvoiceHires
com.freelanceplaza.payment.listeners.CompletedInvoiceListener ..> com.freelanceplaza.payment.services.InvoiceService
com.freelanceplaza.payment.opp.dtos.NotificationDto ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto ..> com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto ..> com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..> com.freelanceplaza.payment.exceptions.PaymentServiceException
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..> com.freelanceplaza.payment.producers.CreateOppAccountProducer$CreateOppAccountEvent
com.freelanceplaza.payment.listeners.UserSyncListener ..> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.listeners.UserSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.opp.OppTransactionService$2 ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.opp.OppTransactionService$2 ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.opp.OppTransactionService$2 ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.Request
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.UserServiceSyncPort
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.producers.CreateOppAccountProducer
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.invoices.dtos.ShiftHire
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.services.WorkFinishedService ..> com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.opp.OppTransactionService$1 ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.opp.OppTransactionService$1 ..> com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.opp.OppTransactionService$3 ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification ..> com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification
com.freelanceplaza.payment.producers.CreateOppAccountProducer$CreateOppAccountEvent ..> com.freelanceplaza.payment.producers.CreateOppAccountProducer$CreateOppAccountEvent
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.payment.config.security.AuthConfiguration
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.config.AudienceConfig
com.freelanceplaza.payment.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.config.AuthDecoderConfig
com.freelanceplaza.payment.entities.OppTransaction ..> com.freelanceplaza.payment.enums.OppTransactionType
com.freelanceplaza.payment.entities.OppTransaction ..> com.freelanceplaza.payment.entities.OppAccountDeduction
com.freelanceplaza.payment.entities.OppTransaction ..> com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.config.ApiPortConfiguration ..> com.freelanceplaza.commons.fphttpclient.okta.OktaAuthPort
com.freelanceplaza.payment.config.ApiPortConfiguration ..> com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.UserServiceSyncPort
com.freelanceplaza.payment.config.ApiPortConfiguration ..> com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.config.ApiPortConfiguration ..> com.freelanceplaza.payment.config.ApiPortConfiguration
com.freelanceplaza.payment.entities.OppAccount ..> com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.entities.OppAccount ..> com.freelanceplaza.payment.enums.OppKycDeductionStatus
com.freelanceplaza.payment.entities.OppAccount ..> com.freelanceplaza.payment.entities.OppCompliance
com.freelanceplaza.payment.entities.OppAccount ..> com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer ..> com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification
com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer ..> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.services.ConfigService ..> com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.services.ConfigService ..> com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.exceptions.GlobalExceptionHandler ..> com.freelanceplaza.payment.exceptions.EntityNotFoundException
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.payment.opp.entities.OppRequestLog
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.commons.fphttpclient.ports.AbstractApiPort$HttpRequestWrapper
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.commons.fphttpclient.ports.AbstractApiPort$HttpResponseWrapper
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.payment.opp.dtos.OppRequestLogDto
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.payment.opp.repositories.OppRequestLogRepository
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.payment.opp.repositories.OppNotificationLogRepository
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.opp.OppLogService ..> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.payment.entities.DisapprovalReasonLabel ..> com.freelanceplaza.payment.entities.DisapprovalReasonLabel
com.freelanceplaza.payment.services.LocationService ..> com.freelanceplaza.commons.fpcommons.sync.locations.LocationSync
com.freelanceplaza.payment.services.LocationService ..> com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.LocationService ..> com.freelanceplaza.payment.repositories.LocationRepository
com.freelanceplaza.payment.services.LocationService ..> com.freelanceplaza.payment.exceptions.EntityNotFoundException
com.freelanceplaza.payment.opp.dtos.OppRequestLogDto ..> com.freelanceplaza.payment.opp.dtos.OppRequestLogDto
com.freelanceplaza.payment.entities.config.Config ..> com.freelanceplaza.payment.enums.Units
com.freelanceplaza.payment.entities.config.Config ..> com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.entities.config.Config ..> com.freelanceplaza.payment.entities.config.Config
com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage ..> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage ..> com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage
com.freelanceplaza.payment.config.ApiPortConfiguration$ServiceConfiguration ..> com.freelanceplaza.payment.config.ApiPortConfiguration$ServiceConfiguration
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.opp.OppLogService
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.config.OppConfiguration
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.config.OppConfiguration$BankConfig
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.config.OppConfiguration$StageConfig
com.freelanceplaza.payment.config.OppConfiguration ..> com.freelanceplaza.payment.enums.PaymentMethod
com.freelanceplaza.payment.controllers.M2mController ..> com.freelanceplaza.payment.producers.OppFreelancerProfileMessage
com.freelanceplaza.payment.controllers.M2mController ..> com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.controllers.M2mController ..> com.freelanceplaza.payment.services.PaymentAssignmentService
com.freelanceplaza.payment.controllers.M2mController ..> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.controllers.OppController ..> com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.controllers.OppController ..> com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.controllers.OppController ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.dtos.DisapprovalDto ..> com.freelanceplaza.payment.dtos.DisapprovalDto
com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener ..> com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.services.InvoiceService ..> com.freelanceplaza.invoices.dtos.InvoiceHires
com.freelanceplaza.payment.services.InvoiceService ..> com.freelanceplaza.payment.repositories.InvoiceRepository
com.freelanceplaza.payment.services.InvoiceService ..> com.freelanceplaza.payment.repositories.InvoiceBundleRepository
com.freelanceplaza.payment.services.InvoiceService ..> com.freelanceplaza.payment.producers.CreateTransactionBundleProducer
com.freelanceplaza.payment.opp.OppPort$5 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.dtos.MerchantDto ..> com.freelanceplaza.payment.opp.dtos.ComplianceDto
com.freelanceplaza.payment.opp.dtos.MerchantDto ..> com.freelanceplaza.payment.opp.dtos.MerchantDto
com.freelanceplaza.payment.opp.dtos.ContactDto ..> com.freelanceplaza.payment.opp.dtos.ContactDto
com.freelanceplaza.payment.opp.OppPort$6 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$3 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$4 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$1 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort$2 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.MerchantConfig ..> com.freelanceplaza.payment.opp.MerchantConfig
com.freelanceplaza.payment.entities.OppDisapproval ..> com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.entities.OppDisapproval ..> com.freelanceplaza.payment.entities.OppDisapproval
com.freelanceplaza.payment.opp.entities.OppRequestLog ..> com.freelanceplaza.payment.opp.entities.OppRequestLog
com.freelanceplaza.payment.opp.dtos.ProductDto ..> com.freelanceplaza.payment.opp.dtos.ProductDto
com.freelanceplaza.payment.opp.OppPort$9 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.services.InvoiceService$1 ..> com.freelanceplaza.payment.services.InvoiceService
com.freelanceplaza.payment.services.InvoiceService$1 ..> com.freelanceplaza.payment.entities.InvoiceBundle
com.freelanceplaza.payment.opp.OppPort$7 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer ..> com.freelanceplaza.invoices.dtos.PaymentAssignmentEvent
com.freelanceplaza.payment.opp.OppPort$8 ..> com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.dtos.RequirementDto ..> com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.dtos.RequirementDto ..> com.freelanceplaza.payment.dtos.RequirementDto

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-payment-service/src/main/java/
' com.freelanceplaza.payment.config.OppConfiguration$StageConfig

' com.freelanceplaza.payment.enums.PaymentAccountStatus

' com.freelanceplaza.payment.utils.DateFormatter

' com.freelanceplaza.payment.exceptions.ErrorResponse

' com.freelanceplaza.payment.config.JacksonConfig$FpInstantSerializer

' com.freelanceplaza.payment.repositories.InvoiceRepository

' com.freelanceplaza.payment.exceptions.EntityNotFoundException

' com.freelanceplaza.payment.config.aws.SQSConfig
com.freelanceplaza.payment.config.aws.SQSConfig ..o com.freelanceplaza.payment.producers.RunBundledTransactionProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..o com.freelanceplaza.commons.fpcommons.config.FpProfile
com.freelanceplaza.payment.config.aws.SQSConfig ..o com.freelanceplaza.payment.producers.CreateTransactionBundleProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..o com.freelanceplaza.payment.producers.CreateOppAccountProducer
com.freelanceplaza.payment.config.aws.SQSConfig ..o com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer

' com.freelanceplaza.payment.opp.dtos.IOppTransaction

' com.freelanceplaza.payment.producers.OppFreelancerProfileMessage

' com.freelanceplaza.payment.opp.OppPort$MultipartEntityBuilderWrapper

' com.freelanceplaza.payment.dtos.PaymentAccountDto
com.freelanceplaza.payment.dtos.PaymentAccountDto ..o com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.dtos.PaymentAccountDto ..o com.freelanceplaza.payment.enums.PaymentAccountStatus

' com.freelanceplaza.payment.services.CustomerService$Customer

' com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.entities.User ..o com.freelanceplaza.commons.fpcommons.sync.users.UserType

' com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto
com.freelanceplaza.payment.opp.dtos.OppMultiTransactionImportDto ..o com.freelanceplaza.commons.fpcommons.enums.Currency

' com.freelanceplaza.payment.opp.repositories.OppNotificationLogRepository
com.freelanceplaza.payment.opp.repositories.OppNotificationLogRepository ..o com.freelanceplaza.payment.opp.entities.OppNotificationLog

' com.freelanceplaza.payment.config.aws.SNSConfig
com.freelanceplaza.payment.config.aws.SNSConfig ..o com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..o com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..o com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
com.freelanceplaza.payment.config.aws.SNSConfig ..o com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer

' com.freelanceplaza.payment.opp.OppPort
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.payment.config.OppConfiguration
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.opp.OppPort ..o com.neovisionaries.i18n.CountryCode
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.commons.fphttpclient.ports.AbstractApiPort
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.payment.utils.OppUtils
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.payment.entities.OppTransaction
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.commons.fpcommons.utils.async.AsyncUtils
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppPort ..o com.freelanceplaza.commons.fphttpclient.exceptions.HttpClientException

' com.freelanceplaza.payment.entities.PaymentAccount
com.freelanceplaza.payment.entities.PaymentAccount ..o com.freelanceplaza.payment.enums.PaymentAccountStatus

' com.freelanceplaza.payment.services.CustomerService
com.freelanceplaza.payment.services.CustomerService ..o com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.payment.services.CustomerService ..o com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.services.CustomerService ..o com.freelanceplaza.payment.entities.Organization

' com.freelanceplaza.payment.services.utils.SecurityUtils

' com.freelanceplaza.payment.opp.dtos.RequirementDto
com.freelanceplaza.payment.opp.dtos.RequirementDto ..o com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.opp.dtos.RequirementDto ..o com.freelanceplaza.payment.entities.OppDisapproval
com.freelanceplaza.payment.opp.dtos.RequirementDto ..o com.freelanceplaza.payment.entities.OppCompliance

' com.freelanceplaza.payment.producers.OppKycDeductionEventProducer

' com.freelanceplaza.payment.entities.Organization

' com.freelanceplaza.payment.producers.CreateTransactionBundleProducer

' com.freelanceplaza.payment.opp.dtos.BankAccountDto

' com.freelanceplaza.payment.enums.Units

' com.freelanceplaza.payment.entities.OppRequirement
com.freelanceplaza.payment.entities.OppRequirement ..o com.freelanceplaza.payment.enums.OppStatus

' com.freelanceplaza.payment.opp.dtos.DisapprovalDto

' com.freelanceplaza.payment.opp.dtos.MetadataDto

' com.freelanceplaza.payment.entities.Invoice

' com.freelanceplaza.payment.services.BucketService

' com.freelanceplaza.payment.opp.repositories.OppAccountRepository

' com.freelanceplaza.payment.opp.dtos.ComplianceDto

' com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.exceptions.PaymentServiceException
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.invoices.dtos.PaymentAssignmentEvent
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.config.OppConfiguration
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.producers.RunBundledTransactionProducer
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.utils.OppUtils
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.services.CustomerService
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.producers.OppKycDeductionEventProducer
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.services.OppDataCollector
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.opp.repositories.OppAccountRepository
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.invoices.dtos.KycDeductionEvent
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.services.ReferenceMockGenerator
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.opp.OppTransactionService ..o com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer

' com.freelanceplaza.payment.services.ReferenceMockGenerator

' com.freelanceplaza.payment.entities.OppAccountDeduction
com.freelanceplaza.payment.entities.OppAccountDeduction ..o com.freelanceplaza.commons.fpcommons.enums.Currency

' com.freelanceplaza.payment.entities.Product

' com.freelanceplaza.payment.exceptions.ConfigException

' com.freelanceplaza.payment.enums.TransactionStatus

' com.freelanceplaza.payment.repositories.TransactionRepository
com.freelanceplaza.payment.repositories.TransactionRepository ..o com.freelanceplaza.payment.entities.Transaction

' com.freelanceplaza.payment.listeners.WorkFinishedListener
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.freelanceplaza.payment.services.WorkFinishedService
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.opencsv.exceptions.CsvValidationException
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.freelanceplaza.invoices.dtos.ShiftHire
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.opencsv.CSVReader
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.freelanceplaza.payment.services.BucketService
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.opencsv.bean.CsvToBeanBuilder
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.freelanceplaza.commons.fpcommons.converters.CustomColumnPositionMappingStrategy
com.freelanceplaza.payment.listeners.WorkFinishedListener ..o com.opencsv.bean.CsvToBean

' com.freelanceplaza.payment.enums.OppKycDeductionStatus

' com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto$PaymentDetails

' com.freelanceplaza.payment.services.ReferenceMockGenerator$CharType

' com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener ..o com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener ..o com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.listeners.InvoiceConfigurationSyncListener ..o com.freelanceplaza.payment.services.ConfigService

' com.freelanceplaza.payment.config.RedisConfiguration
com.freelanceplaza.payment.config.RedisConfiguration ..o com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.config.RedisConfiguration ..o com.freelanceplaza.commons.fpcommons.caching.JedisPoolWrapper
com.freelanceplaza.payment.config.RedisConfiguration ..o com.freelanceplaza.commons.fphttpclient.tokenhandlers.cache.RedisTokenCache

' com.freelanceplaza.payment.config.OppConfiguration$BankConfig

' com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto ..o com.freelanceplaza.commons.fpcommons.enums.Currency

' com.freelanceplaza.payment.config.aws.S3Config

' com.freelanceplaza.payment.utils.PaymentDetailsDeserializer
com.freelanceplaza.payment.utils.PaymentDetailsDeserializer ..o com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto

' com.freelanceplaza.payment.services.PaymentAssignmentService
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.entities.PaymentAssignment
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.repositories.PaymentAssignmentRepository
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.exceptions.EntityNotFoundException
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.entities.Invoice
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.invoices.dtos.PaymentAssignmentEvent
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto
com.freelanceplaza.payment.services.PaymentAssignmentService ..o com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer

' com.freelanceplaza.payment.repositories.ProductRepository

' com.freelanceplaza.payment.entities.OppCompliance

' com.freelanceplaza.payment.opp.dtos.OppMultiTransactionDto

' com.freelanceplaza.payment.opp.dtos.OppTransactionDto
com.freelanceplaza.payment.opp.dtos.OppTransactionDto ..o com.freelanceplaza.commons.fpcommons.enums.Currency

' com.freelanceplaza.payment.entities.PaymentAssignment

' com.freelanceplaza.payment.utils.OppUtils

' com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.enums.Language
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.payment.entities.Organization
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSync
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.sync.common.LegalEntity
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationType
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.payment.repositories.OrganizationRepository
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.payment.services.OrganizationService ..o com.freelanceplaza.commons.fpcommons.sync.users.UserType

' com.freelanceplaza.payment.dtos.ConfigDto

' com.freelanceplaza.payment.opp.OppService

' com.freelanceplaza.payment.dtos.PaymentAssignmentStatusDto

' com.freelanceplaza.payment.listeners.RunBundledTransactionListener
com.freelanceplaza.payment.listeners.RunBundledTransactionListener ..o com.freelanceplaza.payment.opp.OppTransactionService

' com.freelanceplaza.payment.producers.CreateOppAccountProducer

' com.freelanceplaza.payment.security.OppNotificationFilter

' com.freelanceplaza.payment.repositories.LocationRepository

' com.freelanceplaza.payment.services.CustomerService$CustomerIdentifier

' com.freelanceplaza.payment.config.OppConfiguration$UriConfig

' com.freelanceplaza.payment.services.OppDataCollector

' com.freelanceplaza.payment.config.aws.S3ConfigDev

' com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository
com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository ..o com.freelanceplaza.payment.entities.DisapprovalReasonLabel

' com.freelanceplaza.payment.entities.Transaction

' com.freelanceplaza.payment.repositories.PaymentAccountRepository

' com.freelanceplaza.payment.entities.config.ConfigHistory

' com.freelanceplaza.payment.opp.entities.OppNotificationLog

' com.freelanceplaza.payment.config.security.SecurityConfig
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.filters.RequiredClaimFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.authorityconverters.FPAuthoritiesConverter
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.payment.security.OppNotificationFilter
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.RemoteJwtDecoder
com.freelanceplaza.payment.config.security.SecurityConfig ..o com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient

' com.freelanceplaza.payment.PaymentApplication

' com.freelanceplaza.payment.services.ReferenceMockGenerator$1

' com.freelanceplaza.payment.listeners.LocationSyncListener
com.freelanceplaza.payment.listeners.LocationSyncListener ..o com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.listeners.LocationSyncListener ..o com.freelanceplaza.payment.services.LocationService
com.freelanceplaza.payment.listeners.LocationSyncListener ..o com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSyncMessage
com.freelanceplaza.payment.listeners.LocationSyncListener ..o com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.payment.listeners.LocationSyncListener ..o com.freelanceplaza.commons.fpcommons.sync.locations.LocationSyncMessage

' com.freelanceplaza.payment.enums.ConfigSource

' com.freelanceplaza.payment.controllers.PaymentAssignmentController
com.freelanceplaza.payment.controllers.PaymentAssignmentController ..o com.freelanceplaza.payment.services.utils.SecurityUtils
com.freelanceplaza.payment.controllers.PaymentAssignmentController ..o com.freelanceplaza.payment.dtos.PaymentAssignmentListItemDto
com.freelanceplaza.payment.controllers.PaymentAssignmentController ..o com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto
com.freelanceplaza.payment.controllers.PaymentAssignmentController ..o com.freelanceplaza.payment.services.PaymentAssignmentService

' com.freelanceplaza.payment.listeners.CreateTransactionBundleListener
com.freelanceplaza.payment.listeners.CreateTransactionBundleListener ..o com.freelanceplaza.payment.opp.OppTransactionService

' com.freelanceplaza.payment.entities.InvoiceBundle

' com.freelanceplaza.payment.services.impl.ConfigServiceImpl
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.dtos.ConfigDto
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.entities.config.Config
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.repositories.ConfigRepository
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.entities.config.ConfigHistory
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.enums.ConfigSource
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.services.ConfigService
com.freelanceplaza.payment.services.impl.ConfigServiceImpl ..o com.freelanceplaza.payment.exceptions.ConfigException

' com.freelanceplaza.payment.config.ApplicationConfiguration
com.freelanceplaza.payment.config.ApplicationConfiguration ..o com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.payment.config.ApplicationConfiguration ..o com.freelanceplaza.commons.fpcommons.utils.async.AsyncUtils
com.freelanceplaza.payment.config.ApplicationConfiguration ..o com.freelanceplaza.commons.fpcommons.crypto.Decoder

' com.freelanceplaza.payment.services.PaymentAccountService
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.enums.PaymentAccountStatus
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.entities.DisapprovalReasonLabel
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.repositories.DisapprovalReasonLabelRepository
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.repositories.PaymentAccountRepository
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.entities.OppAccount
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.enums.OppStatus
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.dtos.PaymentAccountDto
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.dtos.DisapprovalDto
com.freelanceplaza.payment.services.PaymentAccountService ..o com.freelanceplaza.payment.dtos.RequirementDto

' com.freelanceplaza.payment.enums.PaymentMethod

' com.freelanceplaza.payment.exceptions.PaymentServiceException

' com.freelanceplaza.payment.producers.OppFreelancerProfileProducer

' com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.services.UserService ..o com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.payment.services.UserService ..o com.freelanceplaza.payment.entities.User
com.freelanceplaza.payment.services.UserService ..o com.freelanceplaza.payment.repositories.UserRepository

' com.freelanceplaza.payment.entities.Location

' com.freelanceplaza.payment.opp.dtos.OppTransactionStatus

' com.freelanceplaza.payment.opp.dtos.ProfileDto

' com.freelanceplaza.payment.enums.PaymentAssignmentStatusLabels

' com.freelanceplaza.payment.repositories.ConfigRepository

' com.freelanceplaza.payment.listeners.OrganizationSyncListener
com.freelanceplaza.payment.listeners.OrganizationSyncListener ..o com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSyncMessage
com.freelanceplaza.payment.listeners.OrganizationSyncListener ..o com.freelanceplaza.payment.services.OrganizationService
com.freelanceplaza.payment.listeners.OrganizationSyncListener ..o com.freelanceplaza.commons.fpcommons.crypto.Decoder

' com.freelanceplaza.payment.controllers.AccountController
com.freelanceplaza.payment.controllers.AccountController ..o com.freelanceplaza.payment.dtos.PaymentAccountDto
com.freelanceplaza.payment.controllers.AccountController ..o com.freelanceplaza.payment.services.utils.SecurityUtils
com.freelanceplaza.payment.controllers.AccountController ..o com.freelanceplaza.payment.services.PaymentAccountService

' com.freelanceplaza.payment.config.aws.SQSConfig$FPDefaultListenerContainerRegistry

' com.freelanceplaza.payment.listeners.CompletedInvoiceListener
com.freelanceplaza.payment.listeners.CompletedInvoiceListener ..o com.freelanceplaza.invoices.dtos.InvoiceHires
com.freelanceplaza.payment.listeners.CompletedInvoiceListener ..o com.freelanceplaza.payment.services.InvoiceService
com.freelanceplaza.payment.listeners.CompletedInvoiceListener ..o com.freelanceplaza.invoices.enums.InvoiceType

' com.freelanceplaza.payment.opp.dtos.NotificationDto

' com.freelanceplaza.payment.dtos.PaymentAssignmentDetailsItemDto

' com.freelanceplaza.payment.listeners.CreateOppAccountListener
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..o com.freelanceplaza.payment.exceptions.PaymentServiceException
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..o com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..o com.freelanceplaza.payment.producers.CreateOppAccountProducer
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..o com.freelanceplaza.payment.repositories.UserRepository
com.freelanceplaza.payment.listeners.CreateOppAccountListener ..o com.freelanceplaza.payment.entities.OppAccount

' com.freelanceplaza.payment.listeners.UserSyncListener
com.freelanceplaza.payment.listeners.UserSyncListener ..o com.freelanceplaza.commons.fpcommons.sync.users.UserSyncMessage
com.freelanceplaza.payment.listeners.UserSyncListener ..o com.freelanceplaza.payment.services.UserService
com.freelanceplaza.payment.listeners.UserSyncListener ..o com.freelanceplaza.commons.fpcommons.crypto.Decoder

' com.freelanceplaza.payment.opp.OppTransactionService$2

' com.freelanceplaza.payment.services.WorkFinishedService

' com.freelanceplaza.payment.opp.OppTransactionService$1

' com.freelanceplaza.payment.producers.RunBundledTransactionProducer

' com.freelanceplaza.payment.opp.OppTransactionService$3

' com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer$TransactionNotification

' com.freelanceplaza.payment.producers.CreateOppAccountProducer$CreateOppAccountEvent

' com.freelanceplaza.payment.config.security.AuthConfiguration
com.freelanceplaza.payment.config.security.AuthConfiguration ..o com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.payment.config.security.AuthConfiguration ..o com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.payment.config.security.AuthConfiguration ..o com.freelanceplaza.commons.fpauthentication.config.AudienceConfig
com.freelanceplaza.payment.config.security.AuthConfiguration ..o com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient
com.freelanceplaza.payment.config.security.AuthConfiguration ..o com.freelanceplaza.commons.fpauthentication.config.AuthDecoderConfig

' com.freelanceplaza.payment.entities.OppTransaction

' com.freelanceplaza.payment.config.ApiPortConfiguration
com.freelanceplaza.payment.config.ApiPortConfiguration ..o com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.payment.config.ApiPortConfiguration ..o com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.UserServiceSyncPortConfig
com.freelanceplaza.payment.config.ApiPortConfiguration ..o com.freelanceplaza.commons.fphttpclient.syncports.userservicesync.UserServiceSyncPort
com.freelanceplaza.payment.config.ApiPortConfiguration ..o com.freelanceplaza.commons.fphttpclient.tokenhandlers.ClientCredentialsTokenHandler
com.freelanceplaza.payment.config.ApiPortConfiguration ..o com.freelanceplaza.commons.fphttpclient.okta.OktaAuthPort

' com.freelanceplaza.payment.repositories.OrganizationRepository

' com.freelanceplaza.payment.enums.OppStatus

' com.freelanceplaza.payment.entities.OppAccount

' com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer

' com.freelanceplaza.payment.producers.PaymentAccountStatusChangedProducer

' com.freelanceplaza.payment.services.ConfigService

' com.freelanceplaza.payment.exceptions.GlobalExceptionHandler

' com.freelanceplaza.payment.opp.OppLogService

' com.freelanceplaza.payment.repositories.OppTransactionRepository

' com.freelanceplaza.payment.entities.DisapprovalReasonLabel

' com.freelanceplaza.payment.services.LocationService

' com.freelanceplaza.payment.opp.dtos.OppRequestLogDto

' com.freelanceplaza.payment.config.JacksonConfig

' com.freelanceplaza.payment.entities.config.Config

' com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage
com.freelanceplaza.payment.producers.PaymentAccountStatusChangedMessage ..o com.freelanceplaza.payment.enums.PaymentAccountStatus

' com.freelanceplaza.payment.repositories.PaymentAssignmentRepository

' com.freelanceplaza.payment.enums.ProductType

' com.freelanceplaza.payment.config.ApiPortConfiguration$ServiceConfiguration

' com.freelanceplaza.payment.config.OppConfiguration

' com.freelanceplaza.payment.enums.PaymentSystem

' com.freelanceplaza.payment.controllers.M2mController
com.freelanceplaza.payment.controllers.M2mController ..o com.freelanceplaza.payment.producers.OppFreelancerProfileMessage
com.freelanceplaza.payment.controllers.M2mController ..o com.freelanceplaza.payment.producers.OppFreelancerProfileProducer
com.freelanceplaza.payment.controllers.M2mController ..o com.freelanceplaza.commons.fpcommons.utils.async.AsyncUtils
com.freelanceplaza.payment.controllers.M2mController ..o com.freelanceplaza.payment.opp.OppService
com.freelanceplaza.payment.controllers.M2mController ..o com.freelanceplaza.payment.services.PaymentAssignmentService

' com.freelanceplaza.payment.controllers.OppController
com.freelanceplaza.payment.controllers.OppController ..o com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.controllers.OppController ..o com.freelanceplaza.payment.opp.OppTransactionService
com.freelanceplaza.payment.controllers.OppController ..o com.freelanceplaza.payment.opp.dtos.NotificationDto
com.freelanceplaza.payment.controllers.OppController ..o com.freelanceplaza.payment.opp.OppService

' com.freelanceplaza.payment.dtos.DisapprovalDto

' com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener
com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener ..o com.freelanceplaza.payment.producers.TransactionNotificationProcessProducer
com.freelanceplaza.payment.listeners.TransactionNotificationProcessListener ..o com.freelanceplaza.payment.opp.OppTransactionService

' com.freelanceplaza.payment.opp.KYCDeductionConfig

' com.freelanceplaza.payment.enums.OppTransactionType

' com.freelanceplaza.payment.services.InvoiceService

' com.freelanceplaza.payment.opp.OppService$1

' com.freelanceplaza.payment.repositories.UserRepository

' com.freelanceplaza.payment.opp.OppPort$5

' com.freelanceplaza.payment.opp.dtos.MerchantDto

' com.freelanceplaza.payment.opp.dtos.ContactDto

' com.freelanceplaza.payment.opp.OppPort$6

' com.freelanceplaza.payment.opp.OppPort$3

' com.freelanceplaza.payment.opp.OppPort$4

' com.freelanceplaza.payment.config.aws.SqsBootstrapConfiguration

' com.freelanceplaza.payment.opp.OppPort$1

' com.freelanceplaza.payment.opp.OppPort$2

' com.freelanceplaza.payment.opp.MerchantConfig

' com.freelanceplaza.payment.opp.repositories.OppRequestLogRepository

' com.freelanceplaza.payment.entities.OppDisapproval

' com.freelanceplaza.payment.opp.entities.OppRequestLog

' com.freelanceplaza.payment.services.utils.SeparateTransactionTemplate

' com.freelanceplaza.payment.opp.dtos.ProductDto

' com.freelanceplaza.payment.opp.OppPort$9

' com.freelanceplaza.payment.services.InvoiceService$1

' com.freelanceplaza.payment.opp.OppPort$7

' com.freelanceplaza.payment.producers.PaymentAssignmentEventProducer

' com.freelanceplaza.payment.opp.OppPort$8

' com.freelanceplaza.payment.repositories.InvoiceBundleRepository

' com.freelanceplaza.payment.dtos.RequirementDto



@enduml
