@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-lrk-integration/build/classes/java/main]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-lrk-integration/src/main/java/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Fri Jan 17 14:24:51 CET 2025



' CLASSES =======
class freelanceplaza.lrkintegration.controller.LrkRecordController
interface freelanceplaza.lrkintegration.repository.LrkRepository
class freelanceplaza.lrkintegration.mapper.LocalDateConverter
class freelanceplaza.lrkintegration.dto.LrkDto
class freelanceplaza.lrkintegration.util.LrkSqlGenerator
class freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl$1
class freelanceplaza.lrkintegration.service.impl.FpLrkService
class freelanceplaza.lrkintegration.config.SecurityConfig
interface freelanceplaza.lrkintegration.repository.LrkJdbcRepository
class freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl
class freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader
class freelanceplaza.lrkintegration.mapper.LrkMapper
class freelanceplaza.lrkintegration.entity.LrkEntity
interface freelanceplaza.lrkintegration.service.LrkService
class freelanceplaza.lrkintegration.dto.LrkCsvDTO
class freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder
class freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder
class freelanceplaza.lrkintegration.FpBackendLrkIntegrationApplication

' INHERITANCES =======

' IMPLEMENT INTERFACE =======
freelanceplaza.lrkintegration.service.LrkService <|.. freelanceplaza.lrkintegration.service.impl.FpLrkService
freelanceplaza.lrkintegration.repository.LrkJdbcRepository <|.. freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl

' FIELDS =======
freelanceplaza.lrkintegration.controller.LrkRecordController --> freelanceplaza.lrkintegration.service.LrkService
freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl$1 --> freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl
freelanceplaza.lrkintegration.service.impl.FpLrkService --> freelanceplaza.lrkintegration.repository.LrkRepository
freelanceplaza.lrkintegration.service.impl.FpLrkService --> freelanceplaza.lrkintegration.mapper.LrkMapper
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader --> freelanceplaza.lrkintegration.repository.LrkJdbcRepository
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader --> freelanceplaza.lrkintegration.mapper.LrkMapper

' USES =======
freelanceplaza.lrkintegration.controller.LrkRecordController ..> freelanceplaza.lrkintegration.service.LrkService
freelanceplaza.lrkintegration.dto.LrkDto ..> freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder
freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl$1 ..> freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl
freelanceplaza.lrkintegration.service.impl.FpLrkService ..> freelanceplaza.lrkintegration.dto.LrkDto
freelanceplaza.lrkintegration.service.impl.FpLrkService ..> freelanceplaza.lrkintegration.repository.LrkRepository
freelanceplaza.lrkintegration.service.impl.FpLrkService ..> freelanceplaza.lrkintegration.mapper.LrkMapper
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..> freelanceplaza.lrkintegration.repository.LrkJdbcRepository
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..> freelanceplaza.lrkintegration.mapper.LrkMapper
freelanceplaza.lrkintegration.mapper.LrkMapper ..> freelanceplaza.lrkintegration.dto.LrkDto
freelanceplaza.lrkintegration.mapper.LrkMapper ..> freelanceplaza.lrkintegration.entity.LrkEntity
freelanceplaza.lrkintegration.mapper.LrkMapper ..> freelanceplaza.lrkintegration.dto.LrkCsvDTO
freelanceplaza.lrkintegration.entity.LrkEntity ..> freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder
freelanceplaza.lrkintegration.service.LrkService ..> freelanceplaza.lrkintegration.dto.LrkDto
freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder ..> freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder
freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder ..> freelanceplaza.lrkintegration.entity.LrkEntity
freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder ..> freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder
freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder ..> freelanceplaza.lrkintegration.dto.LrkDto

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-lrk-integration/src/main/java/
' freelanceplaza.lrkintegration.controller.LrkRecordController
freelanceplaza.lrkintegration.controller.LrkRecordController ..o freelanceplaza.lrkintegration.service.LrkService
freelanceplaza.lrkintegration.controller.LrkRecordController ..o freelanceplaza.lrkintegration.dto.LrkDto

' freelanceplaza.lrkintegration.repository.LrkRepository
freelanceplaza.lrkintegration.repository.LrkRepository ..o freelanceplaza.lrkintegration.entity.LrkEntity

' freelanceplaza.lrkintegration.mapper.LocalDateConverter
freelanceplaza.lrkintegration.mapper.LocalDateConverter ..o com.opencsv.bean.AbstractBeanField

' freelanceplaza.lrkintegration.dto.LrkDto

' freelanceplaza.lrkintegration.util.LrkSqlGenerator
freelanceplaza.lrkintegration.util.LrkSqlGenerator ..o freelanceplaza.lrkintegration.entity.LrkEntity

' freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl$1

' freelanceplaza.lrkintegration.service.impl.FpLrkService
freelanceplaza.lrkintegration.service.impl.FpLrkService ..o freelanceplaza.lrkintegration.entity.LrkEntity
freelanceplaza.lrkintegration.service.impl.FpLrkService ..o freelanceplaza.lrkintegration.service.LrkService
freelanceplaza.lrkintegration.service.impl.FpLrkService ..o freelanceplaza.lrkintegration.repository.LrkRepository
freelanceplaza.lrkintegration.service.impl.FpLrkService ..o freelanceplaza.lrkintegration.dto.LrkDto
freelanceplaza.lrkintegration.service.impl.FpLrkService ..o freelanceplaza.lrkintegration.mapper.LrkMapper

' freelanceplaza.lrkintegration.config.SecurityConfig

' freelanceplaza.lrkintegration.repository.LrkJdbcRepository
freelanceplaza.lrkintegration.repository.LrkJdbcRepository ..o freelanceplaza.lrkintegration.entity.LrkEntity

' freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl
freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl ..o freelanceplaza.lrkintegration.util.LrkSqlGenerator
freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl ..o freelanceplaza.lrkintegration.repository.LrkJdbcRepository
freelanceplaza.lrkintegration.repository.impl.LrkJdbcRepositoryImpl ..o freelanceplaza.lrkintegration.entity.LrkEntity

' freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o freelanceplaza.lrkintegration.repository.LrkJdbcRepository
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o freelanceplaza.lrkintegration.entity.LrkEntity
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o com.opencsv.bean.CsvToBeanBuilder
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o freelanceplaza.lrkintegration.dto.LrkCsvDTO
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o com.opencsv.bean.CsvToBean
freelanceplaza.lrkintegration.bootstrap.LrkCsvLoader ..o freelanceplaza.lrkintegration.mapper.LrkMapper

' freelanceplaza.lrkintegration.mapper.LrkMapper

' freelanceplaza.lrkintegration.entity.LrkEntity

' freelanceplaza.lrkintegration.service.LrkService

' freelanceplaza.lrkintegration.dto.LrkCsvDTO

' freelanceplaza.lrkintegration.entity.LrkEntity$LrkEntityBuilder

' freelanceplaza.lrkintegration.dto.LrkDto$LrkDtoBuilder

' freelanceplaza.lrkintegration.FpBackendLrkIntegrationApplication



@enduml
