@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-notification-service/build/classes/java/main/com/freelanceplaza/notification/entities]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-notification-service/src/main/java/com/freelanceplaza/notification/entities/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Thu Feb 20 18:12:52 CET 2025
'
'   Stat infos    :
'       Files : [12]
'       Lines : [331]
'     Classes : [12]
'     Methods : [144]
'      Fields : [64]



' CLASSES =======
abstract com.freelanceplaza.notification.entities.Address
class com.freelanceplaza.notification.entities.MobileDeviceToken
class com.freelanceplaza.notification.entities.LegalEntity
class com.freelanceplaza.notification.entities.Vertical
class com.freelanceplaza.notification.entities.Subscription$SubscriptionId
class com.freelanceplaza.notification.entities.EmailAddress
class com.freelanceplaza.notification.entities.Subscription
class com.freelanceplaza.notification.entities.NotificationTemplate
class com.freelanceplaza.notification.entities.Invoice
class com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
class com.freelanceplaza.notification.entities.InvoiceBundle
class com.freelanceplaza.notification.entities.Recipient

' INHERITANCES =======
com.freelanceplaza.notification.entities.Address <|-- com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.entities.Address <|-- com.freelanceplaza.notification.entities.EmailAddress

' IMPLEMENT INTERFACE =======
java.io.Serializable <|.. com.freelanceplaza.notification.entities.Subscription$SubscriptionId

' FIELDS =======
com.freelanceplaza.notification.entities.Address --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.MobileDeviceToken --> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.enums.SubscriptionStatus
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.entities.NotificationTemplate --> com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.entities.NotificationTemplate --> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.InvoiceType
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.commons.fpcommons.enums.Language

' USES =======
com.freelanceplaza.notification.entities.Address ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Address ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.entities.MobileDeviceToken ..> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.MobileDeviceToken ..> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.entities.LegalEntity ..> com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
com.freelanceplaza.notification.entities.LegalEntity ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.Vertical ..> com.freelanceplaza.notification.entities.Vertical
com.freelanceplaza.notification.entities.Subscription$SubscriptionId ..> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.enums.SubscriptionStatus
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Subscription
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.invoices.enums.InvoiceType
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.notification.entities.Invoice
com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder ..> com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.InvoiceBundle ..> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.commons.fpcommons.enums.Language
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.entities.Recipient

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-notification-service/src/main/java/com/freelanceplaza/notification/entities/
' com.freelanceplaza.notification.entities.Address

' com.freelanceplaza.notification.entities.MobileDeviceToken

' com.freelanceplaza.notification.entities.LegalEntity

' com.freelanceplaza.notification.entities.Vertical

' com.freelanceplaza.notification.entities.Subscription$SubscriptionId

' com.freelanceplaza.notification.entities.EmailAddress

' com.freelanceplaza.notification.entities.Subscription

' com.freelanceplaza.notification.entities.NotificationTemplate

' com.freelanceplaza.notification.entities.Invoice

' com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder

' com.freelanceplaza.notification.entities.InvoiceBundle

' com.freelanceplaza.notification.entities.Recipient



@enduml
