@startuml
'https://plantuml.com/class-diagram

hide *Q*
hide *Builder
hide *BuilderImpl

!include Tadaah-entities-documents.puml
!include Tadaah-entities-hiring.puml
!include Tadaah-entities-invoice.puml
!include Tadaah-entities-user.puml

@enduml
