@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-invoice-service/build/classes/java/main/freelanceplaza/fpbackendinvoiceservice/entity]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-invoice-service/src/main/java/freelanceplaza/fpbackendinvoiceservice/entity/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Thu Feb 20 18:12:52 CET 2025
'
'   Stat infos    :
'       Files : [39]
'       Lines : [971]
'     Classes : [39]
'     Methods : [594]
'      Fields : [319]



' CLASSES =======
class freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData
interface freelanceplaza.fpbackendinvoiceservice.entity.GroupedShiftView
class freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle
class freelanceplaza.fpbackendinvoiceservice.entity.KycDeductionProduct
class freelanceplaza.fpbackendinvoiceservice.entity.ProductData
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.Status{
}
class freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct
class freelanceplaza.fpbackendinvoiceservice.entity.Config
class freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes{
}
class freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct
class freelanceplaza.fpbackendinvoiceservice.entity.Supplier
class freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity
class freelanceplaza.fpbackendinvoiceservice.entity.Organization
class freelanceplaza.fpbackendinvoiceservice.entity.Invoice
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType{
}
class freelanceplaza.fpbackendinvoiceservice.entity.Product
class freelanceplaza.fpbackendinvoiceservice.entity.Address
class freelanceplaza.fpbackendinvoiceservice.entity.File
class freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction
class freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity
class freelanceplaza.fpbackendinvoiceservice.entity.Customer
class freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.Units{
}
class freelanceplaza.fpbackendinvoiceservice.entity.Shift
class freelanceplaza.fpbackendinvoiceservice.entity.Location
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType{
}
class freelanceplaza.fpbackendinvoiceservice.entity.Freelancer
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus{
}
class freelanceplaza.fpbackendinvoiceservice.entity.MediationFeeProduct
class freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.Status{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.Units{
}
enum freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes{
}

' INHERITANCES =======
freelanceplaza.fpbackendinvoiceservice.entity.Product <|-- freelanceplaza.fpbackendinvoiceservice.entity.KycDeductionProduct
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.Status
freelanceplaza.fpbackendinvoiceservice.entity.Product <|-- freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes
freelanceplaza.fpbackendinvoiceservice.entity.Product <|-- freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.Units
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus
freelanceplaza.fpbackendinvoiceservice.entity.Product <|-- freelanceplaza.fpbackendinvoiceservice.entity.MediationFeeProduct
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.Status
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.Units
java.lang.Enum <|-- freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes

' IMPLEMENT INTERFACE =======
java.io.Serializable <|.. freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData
java.io.Serializable <|.. freelanceplaza.fpbackendinvoiceservice.entity.ProductData
freelanceplaza.fpbackendinvoiceservice.entity.GroupedShiftView <|.. freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift

' FIELDS =======
freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct --> freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver
freelanceplaza.fpbackendinvoiceservice.entity.Config --> freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes
freelanceplaza.fpbackendinvoiceservice.entity.Config --> freelanceplaza.fpbackendinvoiceservice.entity.enums.Units
freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift --> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.Supplier --> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity --> freelanceplaza.fpbackendinvoiceservice.entity.ProductData
freelanceplaza.fpbackendinvoiceservice.entity.Organization --> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Organization --> freelanceplaza.fpbackendinvoiceservice.entity.enums.Status
freelanceplaza.fpbackendinvoiceservice.entity.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
freelanceplaza.fpbackendinvoiceservice.entity.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationInvoiceSetting
freelanceplaza.fpbackendinvoiceservice.entity.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationType
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> com.freelanceplaza.invoices.enums.InvoiceType
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Invoice --> freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.Invoice
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.Shift
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction
freelanceplaza.fpbackendinvoiceservice.entity.Product --> freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Address --> com.freelanceplaza.commons.fpcommons.sync.common.AddressType
freelanceplaza.fpbackendinvoiceservice.entity.File --> com.freelanceplaza.invoices.enums.InvoiceBucketReference
freelanceplaza.fpbackendinvoiceservice.entity.File --> freelanceplaza.fpbackendinvoiceservice.entity.Invoice
freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction --> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction --> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity --> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData
freelanceplaza.fpbackendinvoiceservice.entity.Customer --> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder --> com.freelanceplaza.commons.fpcommons.sync.common.AddressType
freelanceplaza.fpbackendinvoiceservice.entity.Shift --> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.Shift --> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.Shift --> com.freelanceplaza.invoices.enums.HireFlowStatus
freelanceplaza.fpbackendinvoiceservice.entity.Location --> freelanceplaza.fpbackendinvoiceservice.entity.Organization
freelanceplaza.fpbackendinvoiceservice.entity.Location --> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer --> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer --> com.freelanceplaza.commons.fpcommons.sync.users.Status
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer --> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment --> com.freelanceplaza.invoices.enums.PaymentAssignmentStatus

' USES =======
freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData
freelanceplaza.fpbackendinvoiceservice.entity.GroupedShiftView ..> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle
freelanceplaza.fpbackendinvoiceservice.entity.ProductData ..> freelanceplaza.fpbackendinvoiceservice.entity.ProductData
freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.Product
freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver
freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct
freelanceplaza.fpbackendinvoiceservice.entity.Config ..> freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes
freelanceplaza.fpbackendinvoiceservice.entity.Config ..> freelanceplaza.fpbackendinvoiceservice.entity.enums.Units
freelanceplaza.fpbackendinvoiceservice.entity.Config ..> freelanceplaza.fpbackendinvoiceservice.entity.Config
freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift ..> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift ..> freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift
freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.Product
freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct
freelanceplaza.fpbackendinvoiceservice.entity.Supplier ..> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.Supplier ..> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity ..> freelanceplaza.fpbackendinvoiceservice.entity.ProductData
freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity ..> freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> freelanceplaza.fpbackendinvoiceservice.entity.enums.Status
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationInvoiceSetting
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationType
freelanceplaza.fpbackendinvoiceservice.entity.Organization ..> freelanceplaza.fpbackendinvoiceservice.entity.Organization
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.File
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.Invoice
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> com.freelanceplaza.invoices.enums.InvoiceType
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Invoice ..> freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.Product
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.Invoice
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.Shift
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction
freelanceplaza.fpbackendinvoiceservice.entity.Product ..> freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Address ..> freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder
freelanceplaza.fpbackendinvoiceservice.entity.Address ..> com.freelanceplaza.commons.fpcommons.sync.common.AddressType
freelanceplaza.fpbackendinvoiceservice.entity.Address ..> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.File ..> com.freelanceplaza.invoices.enums.InvoiceBucketReference
freelanceplaza.fpbackendinvoiceservice.entity.File ..> freelanceplaza.fpbackendinvoiceservice.entity.Invoice
freelanceplaza.fpbackendinvoiceservice.entity.File ..> freelanceplaza.fpbackendinvoiceservice.entity.File
freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction ..> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction ..> freelanceplaza.fpbackendinvoiceservice.entity.Supplier
freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction ..> freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction
freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData
freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity ..> freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity
freelanceplaza.fpbackendinvoiceservice.entity.Customer ..> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.Customer ..> freelanceplaza.fpbackendinvoiceservice.entity.Customer
freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder ..> freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder
freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder ..> com.freelanceplaza.commons.fpcommons.sync.common.AddressType
freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder ..> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Shift ..> freelanceplaza.fpbackendinvoiceservice.entity.Shift
freelanceplaza.fpbackendinvoiceservice.entity.Shift ..> com.freelanceplaza.invoices.enums.MemberType
freelanceplaza.fpbackendinvoiceservice.entity.Shift ..> com.freelanceplaza.commons.fpcommons.enums.Currency
freelanceplaza.fpbackendinvoiceservice.entity.Shift ..> com.freelanceplaza.invoices.enums.HireFlowStatus
freelanceplaza.fpbackendinvoiceservice.entity.Location ..> freelanceplaza.fpbackendinvoiceservice.entity.Organization
freelanceplaza.fpbackendinvoiceservice.entity.Location ..> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Location ..> freelanceplaza.fpbackendinvoiceservice.entity.Location
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer ..> freelanceplaza.fpbackendinvoiceservice.entity.Address
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer ..> com.freelanceplaza.commons.fpcommons.sync.users.Status
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
freelanceplaza.fpbackendinvoiceservice.entity.Freelancer ..> freelanceplaza.fpbackendinvoiceservice.entity.Freelancer
freelanceplaza.fpbackendinvoiceservice.entity.MediationFeeProduct ..> freelanceplaza.fpbackendinvoiceservice.entity.Product
freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment ..> com.freelanceplaza.invoices.enums.PaymentAssignmentStatus
freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment ..> freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-invoice-service/src/main/java/freelanceplaza/fpbackendinvoiceservice/entity/
' freelanceplaza.fpbackendinvoiceservice.entity.InvoiceData

' freelanceplaza.fpbackendinvoiceservice.entity.GroupedShiftView

' freelanceplaza.fpbackendinvoiceservice.entity.InvoiceBundle

' freelanceplaza.fpbackendinvoiceservice.entity.KycDeductionProduct

' freelanceplaza.fpbackendinvoiceservice.entity.ProductData

' freelanceplaza.fpbackendinvoiceservice.entity.enums.Status

' freelanceplaza.fpbackendinvoiceservice.entity.CompensationFeeProduct

' freelanceplaza.fpbackendinvoiceservice.entity.Config

' freelanceplaza.fpbackendinvoiceservice.entity.GroupedShift

' freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes

' freelanceplaza.fpbackendinvoiceservice.entity.ShiftFeeProduct

' freelanceplaza.fpbackendinvoiceservice.entity.Supplier

' freelanceplaza.fpbackendinvoiceservice.entity.ProductDataEntity

' freelanceplaza.fpbackendinvoiceservice.entity.Organization

' freelanceplaza.fpbackendinvoiceservice.entity.Invoice

' freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType

' freelanceplaza.fpbackendinvoiceservice.entity.Product

' freelanceplaza.fpbackendinvoiceservice.entity.Address

' freelanceplaza.fpbackendinvoiceservice.entity.File

' freelanceplaza.fpbackendinvoiceservice.entity.KycDeduction

' freelanceplaza.fpbackendinvoiceservice.entity.InvoiceDataEntity

' freelanceplaza.fpbackendinvoiceservice.entity.Customer

' freelanceplaza.fpbackendinvoiceservice.entity.Address$AddressBuilder

' freelanceplaza.fpbackendinvoiceservice.entity.enums.Units

' freelanceplaza.fpbackendinvoiceservice.entity.Shift

' freelanceplaza.fpbackendinvoiceservice.entity.Location

' freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType

' freelanceplaza.fpbackendinvoiceservice.entity.Freelancer

' freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver

' freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus

' freelanceplaza.fpbackendinvoiceservice.entity.MediationFeeProduct

' freelanceplaza.fpbackendinvoiceservice.entity.PaymentAssignment

' freelanceplaza.fpbackendinvoiceservice.entity.enums.FreelancerInvoicePaymentAssignmentStatus

' freelanceplaza.fpbackendinvoiceservice.entity.enums.AddressType

' freelanceplaza.fpbackendinvoiceservice.entity.enums.Status

' freelanceplaza.fpbackendinvoiceservice.entity.enums.CompensationReceiver

' freelanceplaza.fpbackendinvoiceservice.entity.enums.ProductType

' freelanceplaza.fpbackendinvoiceservice.entity.enums.Units

' freelanceplaza.fpbackendinvoiceservice.entity.enums.ConfigCodes



@enduml
