@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-notification-service/build/classes/java/main]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-notification/src/main/java/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Fri Jan 17 09:59:02 CET 2025



' CLASSES =======
class com.freelanceplaza.notification.listeners.UserSyncListener
interface com.freelanceplaza.notification.utils.NotificationConstants
class com.freelanceplaza.notification.dto.PushNotification$Apns
class com.freelanceplaza.notification.services.UserService
class com.freelanceplaza.notification.validation.ValidationError
class com.freelanceplaza.notification.controllers.AuthorizationController
class com.freelanceplaza.notification.services.InvoiceService
abstract com.freelanceplaza.notification.entities.Address
interface com.freelanceplaza.notification.dto.Notification
class com.freelanceplaza.notification.services.EmailNotificationFactory
class com.freelanceplaza.notification.config.aws.SQSConfig$FPDefaultListenerContainerRegistry
interface com.freelanceplaza.notification.repositories.LegalEntityRepository
class com.freelanceplaza.notification.dto.PushNotification$Android
class com.freelanceplaza.notification.exceptions.NotificationException
class com.freelanceplaza.notification.services.BucketService
class com.freelanceplaza.notification.entities.Subscription$SubscriptionId
class com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
class com.freelanceplaza.notification.dto.TokenUserHandler
class com.freelanceplaza.notification.entities.MobileDeviceToken
class com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage
class com.freelanceplaza.notification.dto.PushNotification$FcmV1Message
class com.freelanceplaza.notification.utils.CurrencyUtils$1
class com.freelanceplaza.notification.listeners.OrganizationUserSyncListener
interface com.freelanceplaza.notification.validation.JsonFieldErrors
class com.freelanceplaza.notification.listeners.OrganizationSyncListener
class com.freelanceplaza.notification.entities.Recipient
class com.freelanceplaza.notification.dto.PushNotification$Aps
interface com.freelanceplaza.notification.repositories.RecipientRepository
class com.freelanceplaza.notification.dto.PushNotification$Alert
class com.freelanceplaza.notification.config.RedisConfiguration
interface com.freelanceplaza.notification.validation.notification.ValidBoolean
class com.freelanceplaza.notification.dto.GroupedInvoiceDTO
class com.freelanceplaza.notification.controllers.ThymeleafRendererController$TemplateResource
class com.freelanceplaza.notification.config.security.AuthConfiguration
class com.freelanceplaza.notification.dto.PushNotification$Webpush
class com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler
class com.freelanceplaza.notification.services.workfinished.WorkFinishedService
class com.freelanceplaza.notification.config.security.AudienceValidator
class com.freelanceplaza.notification.listeners.NotificationEventListener
class com.freelanceplaza.notification.services.LegalEntityMapper
class com.freelanceplaza.notification.validation.notification.BooleanValueValidator
class com.freelanceplaza.notification.services.notification.FreelancerNotificationService
interface com.freelanceplaza.notification.repositories.VerticalRepository
class com.freelanceplaza.notification.config.aws.S3ConfigDev
class com.freelanceplaza.notification.entities.LegalEntity
class com.freelanceplaza.notification.services.IOSMessageFactory
class com.freelanceplaza.notification.services.InvoiceService$1
class com.freelanceplaza.notification.controllers.ThymeleafRendererController$MultipartTemplateResolver
class com.freelanceplaza.notification.services.MobilePushNotificationFactory
class com.freelanceplaza.notification.services.PaymentService$1
class com.freelanceplaza.notification.config.PlatformConfiguration
class com.freelanceplaza.notification.services.S3ServiceImpl
interface com.freelanceplaza.notification.repositories.AddressRepository
class com.freelanceplaza.notification.entities.Subscription
class com.freelanceplaza.notification.dto.TokenData
class com.freelanceplaza.notification.entities.InvoiceBundle
class com.freelanceplaza.notification.utils.MessageUtils
class com.freelanceplaza.notification.controllers.ThymeleafRendererController
class com.freelanceplaza.notification.services.DeviceTokenRegistrarImpl
interface com.freelanceplaza.notification.repositories.NotificationTemplateRepository
class com.freelanceplaza.notification.config.EmailConfig
class com.freelanceplaza.notification.config.aws.SNSConfig
enum com.freelanceplaza.notification.enums.PaymentAccountStatus{
  PENDING
  ACTIVE
  INACTIVE
  UNVERIFIED
  SUSPENDED
  BLOCKED
  DELETED
}
class com.freelanceplaza.notification.config.security.SecurityUtils
enum com.freelanceplaza.notification.enums.Channel{
  EMAIL
  SMS
  PUSH_MOBILE
  PUSH_WEB
}
class com.freelanceplaza.notification.services.OrganizationService
class com.freelanceplaza.notification.dto.MobilePush
class com.freelanceplaza.notification.services.MobileNotificationGateway
class com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser
class com.freelanceplaza.notification.listeners.PaymentAccountStatusChangedListener
interface com.freelanceplaza.notification.services.NotificationService
class com.freelanceplaza.notification.dto.PushNotification$Default
class com.freelanceplaza.notification.entities.EmailAddress
interface com.freelanceplaza.notification.services.MessageFactory
class com.freelanceplaza.notification.services.impl.NotificationServiceImpl
class com.freelanceplaza.notification.dto.EmailNotification
class com.freelanceplaza.notification.exceptions.GlobalExceptionHandler
interface com.freelanceplaza.notification.utils.PaymentAssignmentConstants
interface com.freelanceplaza.notification.repositories.InvoiceRepository
class com.freelanceplaza.notification.entities.NotificationTemplate
enum com.freelanceplaza.notification.enums.MobilePlatform{
  IOS
  ANDROID
}
class com.freelanceplaza.notification.services.PaymentService
class com.freelanceplaza.notification.services.NotificationMessageHelper
class com.freelanceplaza.notification.services.ApplicationEventService$1
class com.freelanceplaza.notification.services.EmailNotificationGateway
class com.freelanceplaza.notification.dto.PushNotification$Message
class com.freelanceplaza.notification.config.aws.S3Config
interface com.freelanceplaza.notification.services.DeviceTokenRegistrar
class com.freelanceplaza.notification.config.aws.SQSConfig
class com.freelanceplaza.notification.publishers.NotificationPublisher
class com.freelanceplaza.notification.dto.PushNotification
class com.freelanceplaza.notification.dto.PushNotification$Notification
class com.freelanceplaza.notification.listeners.InvoiceGeneratedListener
class com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler
class com.freelanceplaza.notification.NotificationApplication
class com.freelanceplaza.notification.services.MobilePushMessageFactory$MobileMessage
class com.freelanceplaza.notification.utils.DateTimeUtils
class com.freelanceplaza.notification.entities.Vertical
interface com.freelanceplaza.notification.repositories.SubscriptionRepository
class com.freelanceplaza.notification.controllers.NotificationController
abstract com.freelanceplaza.notification.validation.CommonJsonErrorValidator
class com.freelanceplaza.notification.exceptions.ValidationFailedResponse
class com.freelanceplaza.notification.listeners.WorkFinishedListener
class com.freelanceplaza.notification.listeners.ApplicationEventListener
interface com.freelanceplaza.notification.services.S3Service
class com.freelanceplaza.notification.services.NotificationComposer
class com.freelanceplaza.notification.dto.NotificationsStatusDto
class com.freelanceplaza.notification.exceptions.ErrorResponse
class com.freelanceplaza.notification.utils.CurrencyUtils
class com.freelanceplaza.notification.services.ApplicationEventService
enum com.freelanceplaza.notification.enums.RecipientType{
  FREELANCER_USER
  ORGANIZATION_USER
  STAFF_USER
  UNKNOWN_USER
  ORGANIZATION
}
class com.freelanceplaza.notification.config.security.SecurityConfig
class com.freelanceplaza.notification.services.LocalDeviceTokenRegistrar
interface com.freelanceplaza.notification.services.NotificationFactory
class com.freelanceplaza.notification.services.EmailNotificationFactory$1
class com.freelanceplaza.notification.entities.Invoice
interface com.freelanceplaza.notification.repositories.InvoiceBundleRepository
class com.freelanceplaza.notification.services.AndroidMessageFactory
enum com.freelanceplaza.notification.enums.SubscriptionStatus{
  ACTIVE
  INACTIVE
}
class com.freelanceplaza.notification.config.ApplicationConfiguration
abstract com.freelanceplaza.notification.services.MobilePushMessageFactory
interface com.freelanceplaza.notification.services.NotificationGateway
class com.freelanceplaza.notification.dto.PushNotification$Payload
class com.freelanceplaza.notification.listeners.PaymentAssignmentStatusListener
class com.freelanceplaza.notification.config.aws.SqsBootstrapConfiguration

' INHERITANCES =======
java.lang.RuntimeException <|-- com.freelanceplaza.notification.exceptions.NotificationException
com.freelanceplaza.notification.entities.Address <|-- com.freelanceplaza.notification.entities.MobileDeviceToken
java.lang.Record <|-- com.freelanceplaza.notification.config.security.AudienceValidator
com.freelanceplaza.notification.validation.CommonJsonErrorValidator <|-- com.freelanceplaza.notification.validation.notification.BooleanValueValidator
com.freelanceplaza.notification.config.aws.S3Config <|-- com.freelanceplaza.notification.config.aws.S3ConfigDev
com.freelanceplaza.notification.services.MobilePushMessageFactory <|-- com.freelanceplaza.notification.services.IOSMessageFactory
java.lang.Enum <|-- com.freelanceplaza.notification.enums.PaymentAccountStatus
java.lang.Enum <|-- com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.entities.Address <|-- com.freelanceplaza.notification.entities.EmailAddress
java.lang.Enum <|-- com.freelanceplaza.notification.enums.MobilePlatform
java.lang.Enum <|-- com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.services.MobilePushMessageFactory <|-- com.freelanceplaza.notification.services.AndroidMessageFactory
java.lang.Enum <|-- com.freelanceplaza.notification.enums.SubscriptionStatus

' IMPLEMENT INTERFACE =======
com.freelanceplaza.notification.services.NotificationFactory <|.. com.freelanceplaza.notification.services.EmailNotificationFactory
java.io.Serializable <|.. com.freelanceplaza.notification.entities.Subscription$SubscriptionId
java.lang.annotation.Annotation <|.. com.freelanceplaza.notification.validation.JsonFieldErrors
java.lang.annotation.Annotation <|.. com.freelanceplaza.notification.validation.notification.ValidBoolean
com.freelanceplaza.notification.services.NotificationFactory <|.. com.freelanceplaza.notification.services.MobilePushNotificationFactory
com.freelanceplaza.notification.services.S3Service <|.. com.freelanceplaza.notification.services.S3ServiceImpl
com.freelanceplaza.notification.services.DeviceTokenRegistrar <|.. com.freelanceplaza.notification.services.DeviceTokenRegistrarImpl
com.freelanceplaza.notification.dto.Notification <|.. com.freelanceplaza.notification.dto.MobilePush
com.freelanceplaza.notification.services.NotificationGateway <|.. com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.services.NotificationService <|.. com.freelanceplaza.notification.services.impl.NotificationServiceImpl
com.freelanceplaza.notification.dto.Notification <|.. com.freelanceplaza.notification.dto.EmailNotification
com.freelanceplaza.notification.services.NotificationGateway <|.. com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.services.DeviceTokenRegistrar <|.. com.freelanceplaza.notification.services.LocalDeviceTokenRegistrar
com.freelanceplaza.notification.services.MessageFactory <|.. com.freelanceplaza.notification.services.MobilePushMessageFactory

' FIELDS =======
com.freelanceplaza.notification.listeners.UserSyncListener --> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.listeners.UserSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.dto.PushNotification$Apns --> com.freelanceplaza.notification.dto.PushNotification$Payload
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.repositories.NotificationTemplateRepository
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.repositories.SubscriptionRepository
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.services.DeviceTokenRegistrar
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.repositories.AddressRepository
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.services.LegalEntityMapper
com.freelanceplaza.notification.services.UserService --> com.freelanceplaza.notification.repositories.LegalEntityRepository
com.freelanceplaza.notification.controllers.AuthorizationController --> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.repositories.InvoiceRepository
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.repositories.InvoiceBundleRepository
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.InvoiceService --> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.entities.Address --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.EmailNotificationFactory --> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.services.EmailNotificationFactory --> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.dto.PushNotification$Android --> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.TokenUserHandler --> com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser
com.freelanceplaza.notification.dto.TokenUserHandler --> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.MobileDeviceToken --> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage --> com.freelanceplaza.notification.enums.PaymentAccountStatus
com.freelanceplaza.notification.dto.PushNotification$FcmV1Message --> com.freelanceplaza.notification.dto.PushNotification$Message
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener --> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener --> com.freelanceplaza.notification.services.OrganizationService
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.listeners.OrganizationSyncListener --> com.freelanceplaza.notification.services.OrganizationService
com.freelanceplaza.notification.listeners.OrganizationSyncListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.Recipient --> com.freelanceplaza.commons.fpcommons.enums.Language
com.freelanceplaza.notification.dto.PushNotification$Aps --> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.config.security.AuthConfiguration --> com.freelanceplaza.commons.fpauthentication.config.AudienceConfig
com.freelanceplaza.notification.config.security.AuthConfiguration --> com.freelanceplaza.commons.fpauthentication.config.AuthDecoderConfig
com.freelanceplaza.notification.dto.PushNotification$Webpush --> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler --> com.freelanceplaza.notification.entities.EmailAddress
com.freelanceplaza.notification.services.workfinished.WorkFinishedService --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.workfinished.WorkFinishedService --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.listeners.NotificationEventListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.NotificationEventListener --> com.freelanceplaza.notification.services.NotificationComposer
com.freelanceplaza.notification.services.notification.FreelancerNotificationService --> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.notification.FreelancerNotificationService --> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.services.IOSMessageFactory --> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.services.InvoiceService$1 --> com.freelanceplaza.notification.services.InvoiceService
com.freelanceplaza.notification.services.MobilePushNotificationFactory --> com.freelanceplaza.notification.services.AndroidMessageFactory
com.freelanceplaza.notification.services.MobilePushNotificationFactory --> com.freelanceplaza.notification.services.IOSMessageFactory
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.enums.SubscriptionStatus
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Subscription --> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.dto.TokenData --> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.controllers.ThymeleafRendererController --> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.services.OrganizationService --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.OrganizationService --> com.freelanceplaza.notification.services.LegalEntityMapper
com.freelanceplaza.notification.services.OrganizationService --> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.services.OrganizationService --> com.freelanceplaza.notification.repositories.LegalEntityRepository
com.freelanceplaza.notification.services.OrganizationService --> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.dto.MobilePush --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.dto.MobilePush --> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.dto.MobilePush --> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.services.MobileNotificationGateway --> com.freelanceplaza.notification.repositories.AddressRepository
com.freelanceplaza.notification.listeners.PaymentAccountStatusChangedListener --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.dto.PushNotification$Default --> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.services.impl.NotificationServiceImpl --> com.freelanceplaza.notification.repositories.SubscriptionRepository
com.freelanceplaza.notification.services.impl.NotificationServiceImpl --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.dto.EmailNotification --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.dto.EmailNotification --> com.freelanceplaza.notification.entities.EmailAddress
com.freelanceplaza.notification.dto.EmailNotification --> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.entities.NotificationTemplate --> com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.entities.NotificationTemplate --> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.services.PaymentService --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.PaymentService --> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.services.PaymentService --> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.services.NotificationMessageHelper --> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.services.EmailNotificationGateway --> com.freelanceplaza.notification.config.EmailConfig
com.freelanceplaza.notification.services.EmailNotificationGateway --> com.freelanceplaza.notification.services.S3Service
com.freelanceplaza.notification.dto.PushNotification$Message --> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Message --> com.freelanceplaza.notification.dto.PushNotification$Android
com.freelanceplaza.notification.dto.PushNotification$Message --> com.freelanceplaza.notification.dto.PushNotification$Apns
com.freelanceplaza.notification.dto.PushNotification$Message --> com.freelanceplaza.notification.dto.PushNotification$Webpush
com.freelanceplaza.notification.publishers.NotificationPublisher --> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.notification.listeners.InvoiceGeneratedListener --> com.freelanceplaza.notification.services.InvoiceService
com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler --> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler --> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.utils.DateTimeUtils --> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.controllers.NotificationController --> com.freelanceplaza.notification.services.NotificationService
com.freelanceplaza.notification.listeners.WorkFinishedListener --> com.freelanceplaza.notification.services.BucketService
com.freelanceplaza.notification.listeners.WorkFinishedListener --> com.freelanceplaza.notification.services.workfinished.WorkFinishedService
com.freelanceplaza.notification.listeners.ApplicationEventListener --> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.ApplicationEventListener --> com.freelanceplaza.notification.services.ApplicationEventService
com.freelanceplaza.notification.services.NotificationComposer --> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.ApplicationEventService --> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.ApplicationEventService --> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.ApplicationEventService --> com.freelanceplaza.notification.services.notification.FreelancerNotificationService
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.entities.Invoice --> com.freelanceplaza.invoices.enums.InvoiceType
com.freelanceplaza.notification.services.AndroidMessageFactory --> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.dto.PushNotification$Payload --> com.freelanceplaza.notification.dto.PushNotification$Aps
com.freelanceplaza.notification.listeners.PaymentAssignmentStatusListener --> com.freelanceplaza.notification.services.PaymentService

' USES =======
com.freelanceplaza.notification.listeners.UserSyncListener ..> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.listeners.UserSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.dto.PushNotification$Apns ..> com.freelanceplaza.notification.dto.PushNotification$Payload
com.freelanceplaza.notification.dto.PushNotification$Apns ..> com.freelanceplaza.notification.dto.PushNotification$Apns
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.dto.TokenUserHandler
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.entities.Subscription
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.commons.fpcommons.sync.SyncModel
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.repositories.NotificationTemplateRepository
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.repositories.SubscriptionRepository
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.services.DeviceTokenRegistrar
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.repositories.AddressRepository
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.services.LegalEntityMapper
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.repositories.LegalEntityRepository
com.freelanceplaza.notification.services.UserService ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.validation.ValidationError ..> com.freelanceplaza.notification.validation.ValidationError
com.freelanceplaza.notification.controllers.AuthorizationController ..> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.invoices.dtos.InvoiceHires
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.dto.GroupedInvoiceDTO
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.repositories.InvoiceRepository
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.repositories.InvoiceBundleRepository
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.commons.fpcommons.notifications.AttachmentDto
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.invoices.dtos.InvoiceHires$BucketReference
com.freelanceplaza.notification.services.InvoiceService ..> com.freelanceplaza.notification.entities.Invoice
com.freelanceplaza.notification.entities.Address ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Address ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.dto.Notification ..> com.freelanceplaza.notification.services.NotificationGateway
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.dto.EmailNotification
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler
com.freelanceplaza.notification.services.EmailNotificationFactory ..> com.freelanceplaza.notification.entities.EmailAddress
com.freelanceplaza.notification.dto.PushNotification$Android ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Android ..> com.freelanceplaza.notification.dto.PushNotification$Android
com.freelanceplaza.notification.entities.Subscription$SubscriptionId ..> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder ..> com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.dto.TokenUserHandler ..> com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser
com.freelanceplaza.notification.dto.TokenUserHandler ..> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.MobileDeviceToken ..> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.MobileDeviceToken ..> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage ..> com.freelanceplaza.notification.enums.PaymentAccountStatus
com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage ..> com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage
com.freelanceplaza.notification.dto.PushNotification$FcmV1Message ..> com.freelanceplaza.notification.dto.PushNotification$Message
com.freelanceplaza.notification.dto.PushNotification$FcmV1Message ..> com.freelanceplaza.notification.dto.PushNotification$FcmV1Message
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.sync.organizationusers.OrganizationUserSyncMessage
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSync
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.enums.EmailTopics
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.notifications.Receiver
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.notification.services.OrganizationService
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.OrganizationUserSyncListener ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.listeners.OrganizationSyncListener ..> com.freelanceplaza.notification.services.OrganizationService
com.freelanceplaza.notification.listeners.OrganizationSyncListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.commons.fpcommons.enums.Language
com.freelanceplaza.notification.entities.Recipient ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.dto.PushNotification$Aps ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Aps ..> com.freelanceplaza.notification.dto.PushNotification$Aps
com.freelanceplaza.notification.dto.PushNotification$Alert ..> com.freelanceplaza.notification.dto.PushNotification$Alert
com.freelanceplaza.notification.config.RedisConfiguration ..> com.freelanceplaza.commons.fpcommons.caching.JedisPoolWrapper
com.freelanceplaza.notification.config.RedisConfiguration ..> com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.notification.config.RedisConfiguration ..> com.freelanceplaza.notification.config.RedisConfiguration
com.freelanceplaza.notification.dto.GroupedInvoiceDTO ..> com.freelanceplaza.notification.dto.GroupedInvoiceDTO
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.notification.config.security.AuthConfiguration
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.config.AudienceConfig
com.freelanceplaza.notification.config.security.AuthConfiguration ..> com.freelanceplaza.commons.fpauthentication.config.AuthDecoderConfig
com.freelanceplaza.notification.dto.PushNotification$Webpush ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Webpush ..> com.freelanceplaza.notification.dto.PushNotification$Webpush
com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler ..> com.freelanceplaza.notification.entities.EmailAddress
com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler ..> com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler
com.freelanceplaza.notification.services.workfinished.WorkFinishedService ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.workfinished.WorkFinishedService ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.workfinished.WorkFinishedService ..> com.freelanceplaza.invoices.dtos.ShiftHire
com.freelanceplaza.notification.services.workfinished.WorkFinishedService ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.listeners.NotificationEventListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.NotificationEventListener ..> com.freelanceplaza.notification.services.NotificationComposer
com.freelanceplaza.notification.listeners.NotificationEventListener ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.listeners.NotificationEventListener ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.services.LegalEntityMapper ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.services.LegalEntityMapper ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSync
com.freelanceplaza.notification.services.LegalEntityMapper ..> com.freelanceplaza.commons.fpcommons.sync.users.UserSync
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.commons.fpcommons.event.ShiftDetails
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.commons.fpcommons.event.Hire
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.commons.fpcommons.enums.EmailTopics
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.notification.FreelancerNotificationService ..> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.entities.LegalEntity ..> com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder
com.freelanceplaza.notification.entities.LegalEntity ..> com.freelanceplaza.notification.entities.LegalEntity
com.freelanceplaza.notification.services.IOSMessageFactory ..> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.services.IOSMessageFactory ..> com.freelanceplaza.notification.dto.MobilePush
com.freelanceplaza.notification.services.IOSMessageFactory ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.services.IOSMessageFactory ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.IOSMessageFactory ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.services.InvoiceService$1 ..> com.freelanceplaza.notification.services.InvoiceService
com.freelanceplaza.notification.services.InvoiceService$1 ..> com.freelanceplaza.notification.dto.GroupedInvoiceDTO
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.services.AndroidMessageFactory
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.services.IOSMessageFactory
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.dto.MobilePush
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.MobilePushNotificationFactory ..> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.config.PlatformConfiguration ..> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Subscription$SubscriptionId
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.enums.SubscriptionStatus
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.entities.Subscription ..> com.freelanceplaza.notification.entities.Subscription
com.freelanceplaza.notification.dto.TokenData ..> com.freelanceplaza.notification.enums.MobilePlatform
com.freelanceplaza.notification.entities.InvoiceBundle ..> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.controllers.ThymeleafRendererController ..> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.services.DeviceTokenRegistrarImpl ..> com.freelanceplaza.notification.dto.TokenData
com.freelanceplaza.notification.repositories.NotificationTemplateRepository ..> com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.repositories.NotificationTemplateRepository ..> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.config.EmailConfig ..> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.config.EmailConfig ..> com.freelanceplaza.notification.services.S3Service
com.freelanceplaza.notification.config.EmailConfig ..> com.freelanceplaza.notification.config.EmailConfig
com.freelanceplaza.notification.config.aws.SNSConfig ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.config.aws.SNSConfig ..> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.notification.config.aws.SNSConfig ..> com.freelanceplaza.notification.services.DeviceTokenRegistrar
com.freelanceplaza.notification.config.security.SecurityUtils ..> com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationSync
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.notification.services.LegalEntityMapper
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.notification.repositories.VerticalRepository
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.notification.repositories.LegalEntityRepository
com.freelanceplaza.notification.services.OrganizationService ..> com.freelanceplaza.notification.services.UserService
com.freelanceplaza.notification.dto.MobilePush ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.dto.MobilePush ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.dto.MobilePush ..> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.dto.MobilePush ..> com.freelanceplaza.notification.services.NotificationGateway
com.freelanceplaza.notification.services.MobileNotificationGateway ..> com.freelanceplaza.notification.dto.MobilePush
com.freelanceplaza.notification.services.MobileNotificationGateway ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.services.MobileNotificationGateway ..> com.freelanceplaza.notification.repositories.AddressRepository
com.freelanceplaza.notification.listeners.PaymentAccountStatusChangedListener ..> com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage
com.freelanceplaza.notification.listeners.PaymentAccountStatusChangedListener ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.NotificationService ..> com.freelanceplaza.notification.dto.NotificationsStatusDto
com.freelanceplaza.notification.dto.PushNotification$Default ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Default ..> com.freelanceplaza.notification.dto.PushNotification$Default
com.freelanceplaza.notification.services.MessageFactory ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.services.MessageFactory ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.services.MessageFactory ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.impl.NotificationServiceImpl ..> com.freelanceplaza.notification.dto.NotificationsStatusDto
com.freelanceplaza.notification.services.impl.NotificationServiceImpl ..> com.freelanceplaza.notification.repositories.SubscriptionRepository
com.freelanceplaza.notification.services.impl.NotificationServiceImpl ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.dto.EmailNotification ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.dto.EmailNotification ..> com.freelanceplaza.notification.entities.EmailAddress
com.freelanceplaza.notification.dto.EmailNotification ..> com.freelanceplaza.notification.services.EmailNotificationGateway
com.freelanceplaza.notification.dto.EmailNotification ..> com.freelanceplaza.notification.services.NotificationGateway
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.enums.Channel
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.enums.RecipientType
com.freelanceplaza.notification.entities.NotificationTemplate ..> com.freelanceplaza.notification.entities.NotificationTemplate
com.freelanceplaza.notification.services.PaymentService ..> com.freelanceplaza.invoices.dtos.PaymentAssignmentEvent
com.freelanceplaza.notification.services.PaymentService ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.services.PaymentService ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.PaymentService ..> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.services.PaymentService ..> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.commons.fpcommons.event.ShiftDetails
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.commons.fpcommons.event.Hire
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.commons.fpcommons.enums.EmailTopics
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.commons.fpcommons.event.ApplicationEvent
com.freelanceplaza.notification.services.NotificationMessageHelper ..> com.freelanceplaza.notification.utils.DateTimeUtils
com.freelanceplaza.notification.services.EmailNotificationGateway ..> com.freelanceplaza.notification.dto.EmailNotification
com.freelanceplaza.notification.services.EmailNotificationGateway ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.services.EmailNotificationGateway ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.EmailNotificationGateway ..> com.freelanceplaza.notification.config.EmailConfig
com.freelanceplaza.notification.services.EmailNotificationGateway ..> com.freelanceplaza.notification.services.S3Service
com.freelanceplaza.notification.dto.PushNotification$Message ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.dto.PushNotification$Message ..> com.freelanceplaza.notification.dto.PushNotification$Android
com.freelanceplaza.notification.dto.PushNotification$Message ..> com.freelanceplaza.notification.dto.PushNotification$Apns
com.freelanceplaza.notification.dto.PushNotification$Message ..> com.freelanceplaza.notification.dto.PushNotification$Webpush
com.freelanceplaza.notification.dto.PushNotification$Message ..> com.freelanceplaza.notification.dto.PushNotification$Message
com.freelanceplaza.notification.services.DeviceTokenRegistrar ..> com.freelanceplaza.notification.dto.TokenData
com.freelanceplaza.notification.publishers.NotificationPublisher ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.publishers.NotificationPublisher ..> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.notification.dto.PushNotification ..> com.freelanceplaza.notification.dto.PushNotification
com.freelanceplaza.notification.dto.PushNotification$Notification ..> com.freelanceplaza.notification.dto.PushNotification$Notification
com.freelanceplaza.notification.listeners.InvoiceGeneratedListener ..> com.freelanceplaza.invoices.dtos.InvoiceHires
com.freelanceplaza.notification.listeners.InvoiceGeneratedListener ..> com.freelanceplaza.notification.services.InvoiceService
com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler ..> com.freelanceplaza.notification.entities.MobileDeviceToken
com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler ..> com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler
com.freelanceplaza.notification.utils.DateTimeUtils ..> com.freelanceplaza.notification.config.PlatformConfiguration
com.freelanceplaza.notification.entities.Vertical ..> com.freelanceplaza.notification.entities.Vertical
com.freelanceplaza.notification.repositories.SubscriptionRepository ..> com.freelanceplaza.notification.enums.SubscriptionStatus
com.freelanceplaza.notification.controllers.NotificationController ..> com.freelanceplaza.notification.dto.NotificationsStatusDto
com.freelanceplaza.notification.controllers.NotificationController ..> com.freelanceplaza.notification.services.NotificationService
com.freelanceplaza.notification.exceptions.ValidationFailedResponse ..> com.freelanceplaza.notification.exceptions.ValidationFailedResponse
com.freelanceplaza.notification.listeners.WorkFinishedListener ..> com.freelanceplaza.notification.services.BucketService
com.freelanceplaza.notification.listeners.WorkFinishedListener ..> com.freelanceplaza.notification.services.workfinished.WorkFinishedService
com.freelanceplaza.notification.listeners.WorkFinishedListener ..> com.freelanceplaza.commons.fpcommons.converters.CustomColumnPositionMappingStrategy
com.freelanceplaza.notification.listeners.ApplicationEventListener ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.listeners.ApplicationEventListener ..> com.freelanceplaza.notification.services.ApplicationEventService
com.freelanceplaza.notification.services.NotificationComposer ..> com.freelanceplaza.commons.fpcommons.notifications.Message
com.freelanceplaza.notification.services.NotificationComposer ..> com.freelanceplaza.notification.repositories.RecipientRepository
com.freelanceplaza.notification.services.NotificationComposer ..> com.freelanceplaza.commons.fpcommons.notifications.Receiver
com.freelanceplaza.notification.services.NotificationComposer ..> com.freelanceplaza.notification.services.NotificationFactory
com.freelanceplaza.notification.dto.NotificationsStatusDto ..> com.freelanceplaza.notification.dto.NotificationsStatusDto
com.freelanceplaza.notification.exceptions.ErrorResponse ..> com.freelanceplaza.notification.exceptions.ErrorResponse
com.freelanceplaza.notification.utils.CurrencyUtils ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.commons.fpcommons.event.ApplicationEvent
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.commons.fpcommons.enums.EmailTopics
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.commons.fpcommons.event.ShiftDetails
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.notification.publishers.NotificationPublisher
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.notification.services.NotificationMessageHelper
com.freelanceplaza.notification.services.ApplicationEventService ..> com.freelanceplaza.notification.services.notification.FreelancerNotificationService
com.freelanceplaza.notification.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.RequiredClaimFilter
com.freelanceplaza.notification.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.AudienceFilter
com.freelanceplaza.notification.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.filters.OrganizationFilter
com.freelanceplaza.notification.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpauthentication.http.AuthDecoderHttpClient
com.freelanceplaza.notification.config.security.SecurityConfig ..> com.freelanceplaza.commons.fpcommons.caching.TokenCache
com.freelanceplaza.notification.services.LocalDeviceTokenRegistrar ..> com.freelanceplaza.notification.dto.TokenData
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.invoices.enums.MemberType
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.notification.entities.InvoiceBundle
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.invoices.enums.InvoiceType
com.freelanceplaza.notification.entities.Invoice ..> com.freelanceplaza.notification.entities.Invoice
com.freelanceplaza.notification.services.AndroidMessageFactory ..> com.freelanceplaza.notification.services.MobileNotificationGateway
com.freelanceplaza.notification.services.AndroidMessageFactory ..> com.freelanceplaza.notification.dto.MobilePush
com.freelanceplaza.notification.services.AndroidMessageFactory ..> com.freelanceplaza.notification.entities.Address
com.freelanceplaza.notification.services.AndroidMessageFactory ..> com.freelanceplaza.notification.entities.Recipient
com.freelanceplaza.notification.services.AndroidMessageFactory ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.config.ApplicationConfiguration ..> com.freelanceplaza.commons.fpcommons.crypto.Decoder
com.freelanceplaza.notification.config.ApplicationConfiguration ..> com.freelanceplaza.commons.fpcommons.crypto.Encoder
com.freelanceplaza.notification.services.MobilePushMessageFactory ..> com.freelanceplaza.notification.services.MobilePushMessageFactory$MobileMessage
com.freelanceplaza.notification.services.MobilePushMessageFactory ..> com.freelanceplaza.notification.dto.PushNotification$Message
com.freelanceplaza.notification.services.NotificationGateway ..> com.freelanceplaza.notification.dto.Notification
com.freelanceplaza.notification.dto.PushNotification$Payload ..> com.freelanceplaza.notification.dto.PushNotification$Aps
com.freelanceplaza.notification.dto.PushNotification$Payload ..> com.freelanceplaza.notification.dto.PushNotification$Payload
com.freelanceplaza.notification.listeners.PaymentAssignmentStatusListener ..> com.freelanceplaza.invoices.dtos.PaymentAssignmentEvent
com.freelanceplaza.notification.listeners.PaymentAssignmentStatusListener ..> com.freelanceplaza.notification.services.PaymentService

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-notification/src/main/java/
' com.freelanceplaza.notification.listeners.UserSyncListener

' com.freelanceplaza.notification.utils.NotificationConstants

' com.freelanceplaza.notification.dto.PushNotification$Apns

' com.freelanceplaza.notification.services.UserService

' com.freelanceplaza.notification.validation.ValidationError

' com.freelanceplaza.notification.controllers.AuthorizationController

' com.freelanceplaza.notification.services.InvoiceService

' com.freelanceplaza.notification.entities.Address

' com.freelanceplaza.notification.dto.Notification

' com.freelanceplaza.notification.services.EmailNotificationFactory

' com.freelanceplaza.notification.config.aws.SQSConfig$FPDefaultListenerContainerRegistry

' com.freelanceplaza.notification.repositories.LegalEntityRepository

' com.freelanceplaza.notification.dto.PushNotification$Android

' com.freelanceplaza.notification.exceptions.NotificationException

' com.freelanceplaza.notification.services.BucketService

' com.freelanceplaza.notification.entities.Subscription$SubscriptionId

' com.freelanceplaza.notification.entities.LegalEntity$LegalEntityBuilder

' com.freelanceplaza.notification.dto.TokenUserHandler

' com.freelanceplaza.notification.entities.MobileDeviceToken

' com.freelanceplaza.notification.dto.PaymentAccountStatusChangedMessage

' com.freelanceplaza.notification.dto.PushNotification$FcmV1Message

' com.freelanceplaza.notification.utils.CurrencyUtils$1

' com.freelanceplaza.notification.listeners.OrganizationUserSyncListener

' com.freelanceplaza.notification.validation.JsonFieldErrors

' com.freelanceplaza.notification.listeners.OrganizationSyncListener

' com.freelanceplaza.notification.entities.Recipient

' com.freelanceplaza.notification.dto.PushNotification$Aps

' com.freelanceplaza.notification.repositories.RecipientRepository

' com.freelanceplaza.notification.dto.PushNotification$Alert

' com.freelanceplaza.notification.config.RedisConfiguration

' com.freelanceplaza.notification.validation.notification.ValidBoolean

' com.freelanceplaza.notification.dto.GroupedInvoiceDTO

' com.freelanceplaza.notification.controllers.ThymeleafRendererController$TemplateResource

' com.freelanceplaza.notification.config.security.AuthConfiguration

' com.freelanceplaza.notification.dto.PushNotification$Webpush

' com.freelanceplaza.notification.services.EmailNotificationFactory$RecipientHandler

' com.freelanceplaza.notification.services.workfinished.WorkFinishedService

' com.freelanceplaza.notification.config.security.AudienceValidator

' com.freelanceplaza.notification.listeners.NotificationEventListener

' com.freelanceplaza.notification.services.LegalEntityMapper

' com.freelanceplaza.notification.validation.notification.BooleanValueValidator

' com.freelanceplaza.notification.services.notification.FreelancerNotificationService

' com.freelanceplaza.notification.repositories.VerticalRepository

' com.freelanceplaza.notification.config.aws.S3ConfigDev

' com.freelanceplaza.notification.entities.LegalEntity

' com.freelanceplaza.notification.services.IOSMessageFactory

' com.freelanceplaza.notification.services.InvoiceService$1

' com.freelanceplaza.notification.controllers.ThymeleafRendererController$MultipartTemplateResolver

' com.freelanceplaza.notification.services.MobilePushNotificationFactory

' com.freelanceplaza.notification.services.PaymentService$1

' com.freelanceplaza.notification.config.PlatformConfiguration

' com.freelanceplaza.notification.services.S3ServiceImpl

' com.freelanceplaza.notification.repositories.AddressRepository

' com.freelanceplaza.notification.entities.Subscription

' com.freelanceplaza.notification.dto.TokenData

' com.freelanceplaza.notification.entities.InvoiceBundle

' com.freelanceplaza.notification.utils.MessageUtils

' com.freelanceplaza.notification.controllers.ThymeleafRendererController

' com.freelanceplaza.notification.services.DeviceTokenRegistrarImpl

' com.freelanceplaza.notification.repositories.NotificationTemplateRepository

' com.freelanceplaza.notification.config.EmailConfig

' com.freelanceplaza.notification.config.aws.SNSConfig

' com.freelanceplaza.notification.enums.PaymentAccountStatus

' com.freelanceplaza.notification.config.security.SecurityUtils

' com.freelanceplaza.notification.enums.Channel

' com.freelanceplaza.notification.services.OrganizationService

' com.freelanceplaza.notification.dto.MobilePush

' com.freelanceplaza.notification.services.MobileNotificationGateway

' com.freelanceplaza.notification.config.security.SecurityUtils$TokenUser

' com.freelanceplaza.notification.listeners.PaymentAccountStatusChangedListener

' com.freelanceplaza.notification.services.NotificationService

' com.freelanceplaza.notification.dto.PushNotification$Default

' com.freelanceplaza.notification.entities.EmailAddress

' com.freelanceplaza.notification.services.MessageFactory

' com.freelanceplaza.notification.services.impl.NotificationServiceImpl

' com.freelanceplaza.notification.dto.EmailNotification

' com.freelanceplaza.notification.exceptions.GlobalExceptionHandler

' com.freelanceplaza.notification.utils.PaymentAssignmentConstants

' com.freelanceplaza.notification.repositories.InvoiceRepository

' com.freelanceplaza.notification.entities.NotificationTemplate

' com.freelanceplaza.notification.enums.MobilePlatform

' com.freelanceplaza.notification.services.PaymentService

' com.freelanceplaza.notification.services.NotificationMessageHelper

' com.freelanceplaza.notification.services.ApplicationEventService$1

' com.freelanceplaza.notification.services.EmailNotificationGateway

' com.freelanceplaza.notification.dto.PushNotification$Message

' com.freelanceplaza.notification.config.aws.S3Config

' com.freelanceplaza.notification.services.DeviceTokenRegistrar

' com.freelanceplaza.notification.config.aws.SQSConfig

' com.freelanceplaza.notification.publishers.NotificationPublisher

' com.freelanceplaza.notification.dto.PushNotification

' com.freelanceplaza.notification.dto.PushNotification$Notification

' com.freelanceplaza.notification.listeners.InvoiceGeneratedListener

' com.freelanceplaza.notification.services.MobilePushNotificationFactory$UserHandler

' com.freelanceplaza.notification.NotificationApplication

' com.freelanceplaza.notification.services.MobilePushMessageFactory$MobileMessage

' com.freelanceplaza.notification.utils.DateTimeUtils

' com.freelanceplaza.notification.entities.Vertical

' com.freelanceplaza.notification.repositories.SubscriptionRepository

' com.freelanceplaza.notification.controllers.NotificationController

' com.freelanceplaza.notification.validation.CommonJsonErrorValidator

' com.freelanceplaza.notification.exceptions.ValidationFailedResponse

' com.freelanceplaza.notification.listeners.WorkFinishedListener

' com.freelanceplaza.notification.listeners.ApplicationEventListener

' com.freelanceplaza.notification.services.S3Service

' com.freelanceplaza.notification.services.NotificationComposer

' com.freelanceplaza.notification.dto.NotificationsStatusDto

' com.freelanceplaza.notification.exceptions.ErrorResponse

' com.freelanceplaza.notification.utils.CurrencyUtils

' com.freelanceplaza.notification.services.ApplicationEventService

' com.freelanceplaza.notification.enums.RecipientType

' com.freelanceplaza.notification.config.security.SecurityConfig

' com.freelanceplaza.notification.services.LocalDeviceTokenRegistrar

' com.freelanceplaza.notification.services.NotificationFactory

' com.freelanceplaza.notification.services.EmailNotificationFactory$1

' com.freelanceplaza.notification.entities.Invoice

' com.freelanceplaza.notification.repositories.InvoiceBundleRepository

' com.freelanceplaza.notification.services.AndroidMessageFactory

' com.freelanceplaza.notification.enums.SubscriptionStatus

' com.freelanceplaza.notification.config.ApplicationConfiguration

' com.freelanceplaza.notification.services.MobilePushMessageFactory

' com.freelanceplaza.notification.services.NotificationGateway

' com.freelanceplaza.notification.dto.PushNotification$Payload

' com.freelanceplaza.notification.listeners.PaymentAssignmentStatusListener

' com.freelanceplaza.notification.config.aws.SqsBootstrapConfiguration



@enduml
