@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-documents-service/build/classes/java/main/com/freelanceplaza/documents/entity]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-documents-service/src/main/java/com/freelanceplaza/documents/entity/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Thu Feb 20 18:00:56 CET 2025
'
'   Stat infos    :
'       Files : [78]
'       Lines : [1080]
'     Classes : [78]
'     Methods : [729]
'      Fields : [330]



' CLASSES =======
class com.freelanceplaza.documents.entity.dictionary.BaseDictionary
class com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
class com.freelanceplaza.documents.entity.dictionary.FunctionCategory
class com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl
enum com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule{
}
class com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder
class com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl
enum com.freelanceplaza.documents.entity.enums.Status{
}
abstract com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
class com.freelanceplaza.documents.entity.dictionary.EducationalLevel
class com.freelanceplaza.documents.entity.DocumentOwner
class com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder
enum com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus{
}
enum com.freelanceplaza.documents.entity.enums.Action{
}
enum com.freelanceplaza.documents.entity.enums.DocumentName{
}
abstract com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof
enum com.freelanceplaza.documents.entity.enums.FileType{
}
abstract com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder
enum com.freelanceplaza.documents.entity.enums.AttachmentType{
}
class com.freelanceplaza.documents.entity.Organization
abstract com.freelanceplaza.documents.entity.document.type.BaseDocumentType
enum com.freelanceplaza.documents.entity.enums.OnboardingStatus{
}
class com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
enum com.freelanceplaza.documents.entity.enums.QualificationType{
}
abstract com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
enum com.freelanceplaza.documents.entity.enums.OwnerType{
}
class com.freelanceplaza.documents.entity.DocumentReviewThread
enum com.freelanceplaza.documents.entity.dictionary.DictionaryType{
}
class com.freelanceplaza.documents.entity.User
class com.freelanceplaza.documents.entity.dictionary.Function
class com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
class com.freelanceplaza.documents.entity.Document
class com.freelanceplaza.documents.entity.QualificationHistory
class com.freelanceplaza.documents.entity.DocumentOwnerId
class com.freelanceplaza.documents.entity.LanguageLevel
enum com.freelanceplaza.documents.entity.enums.QualificationStatus{
}
class com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule
class com.freelanceplaza.documents.entity.DocumentAttachment
class com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType
class com.freelanceplaza.documents.entity.Qualification
class com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl
class com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder
enum com.freelanceplaza.documents.entity.enums.DocumentReviewActions{
}
class com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder
class com.freelanceplaza.documents.entity.Document$DocumentBuilder
class com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof
enum com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus{
}
abstract com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
enum com.freelanceplaza.documents.entity.enums.OwnerType{
}
enum com.freelanceplaza.documents.entity.enums.DocumentReviewActions{
}
enum com.freelanceplaza.documents.entity.enums.OnboardingStatus{
}
enum com.freelanceplaza.documents.entity.enums.QualificationStatus{
}
enum com.freelanceplaza.documents.entity.enums.Status{
}
enum com.freelanceplaza.documents.entity.enums.DocumentName{
}
enum com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus{
}
enum com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule{
}
enum com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus{
}
enum com.freelanceplaza.documents.entity.enums.QualificationType{
}
enum com.freelanceplaza.documents.entity.enums.FileType{
}
enum com.freelanceplaza.documents.entity.enums.AttachmentType{
}
enum com.freelanceplaza.documents.entity.enums.Action{
}
class com.freelanceplaza.documents.entity.dictionary.EducationalLevel
class com.freelanceplaza.documents.entity.dictionary.Function
enum com.freelanceplaza.documents.entity.dictionary.DictionaryType{
}
class com.freelanceplaza.documents.entity.dictionary.FunctionCategory
class com.freelanceplaza.documents.entity.dictionary.BaseDictionary
abstract com.freelanceplaza.documents.entity.document.type.BaseDocumentType
class com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl
abstract com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
class com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl
class com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
abstract com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
class com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType
class com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
class com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
abstract com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
class com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl
abstract com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder

' INHERITANCES =======
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.EducationalLevel
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.Action
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentName
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.FileType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.AttachmentType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.OnboardingStatus
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.QualificationType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.OwnerType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.dictionary.DictionaryType
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.Function
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.QualificationStatus
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentReviewActions
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof <|-- com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.OwnerType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentReviewActions
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.OnboardingStatus
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.QualificationStatus
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.Status
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentName
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.QualificationType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.FileType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.AttachmentType
java.lang.Enum <|-- com.freelanceplaza.documents.entity.enums.Action
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.Function
java.lang.Enum <|-- com.freelanceplaza.documents.entity.dictionary.DictionaryType
com.freelanceplaza.documents.entity.dictionary.BaseDictionary <|-- com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder <|-- com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder

' IMPLEMENT INTERFACE =======
java.io.Serializable <|.. com.freelanceplaza.documents.entity.DocumentOwnerId

' FIELDS =======
com.freelanceplaza.documents.entity.dictionary.BaseDictionary --> com.freelanceplaza.documents.entity.dictionary.DictionaryType
com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder --> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.DocumentOwner --> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder --> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof --> com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof --> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof --> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationStatus
com.freelanceplaza.documents.entity.Organization --> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.documents.entity.document.type.BaseDocumentType --> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType --> com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder --> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.DocumentReviewThread --> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentReviewThread --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.User --> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.documents.entity.User --> com.freelanceplaza.commons.fpcommons.sync.users.Status
com.freelanceplaza.documents.entity.User --> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.documents.entity.dictionary.Function --> com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.dictionary.Function --> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.Document --> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.Document --> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Document --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.QualificationHistory --> com.freelanceplaza.documents.entity.enums.QualificationStatus
com.freelanceplaza.documents.entity.QualificationHistory --> com.freelanceplaza.documents.entity.enums.Action
com.freelanceplaza.documents.entity.DocumentOwnerId --> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule --> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule --> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule --> com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule --> com.freelanceplaza.documents.entity.dictionary.BaseDictionary
com.freelanceplaza.documents.entity.DocumentAttachment --> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.DocumentAttachment --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentAttachment --> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentAttachment --> com.freelanceplaza.documents.entity.enums.AttachmentType
com.freelanceplaza.documents.entity.Qualification --> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Qualification --> com.freelanceplaza.documents.entity.dictionary.Function
com.freelanceplaza.documents.entity.Qualification --> com.freelanceplaza.documents.entity.enums.QualificationType
com.freelanceplaza.documents.entity.Qualification --> com.freelanceplaza.documents.entity.enums.QualificationStatus
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder --> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder --> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder --> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder --> com.freelanceplaza.documents.entity.enums.AttachmentType
com.freelanceplaza.documents.entity.Document$DocumentBuilder --> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.Document$DocumentBuilder --> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Document$DocumentBuilder --> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof --> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof --> com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder --> com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.dictionary.Function --> com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.dictionary.Function --> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.dictionary.BaseDictionary --> com.freelanceplaza.documents.entity.dictionary.DictionaryType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType --> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder --> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType --> com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder --> com.freelanceplaza.documents.entity.dictionary.EducationalLevel

' USES =======
com.freelanceplaza.documents.entity.dictionary.BaseDictionary ..> com.freelanceplaza.documents.entity.dictionary.DictionaryType
com.freelanceplaza.documents.entity.dictionary.BaseDictionary ..> com.freelanceplaza.documents.entity.dictionary.BaseDictionary
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
com.freelanceplaza.documents.entity.dictionary.FunctionCategory ..> com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder ..> com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder
com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder ..> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.UniqueDocumentType
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.DocumentOwner ..> com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder
com.freelanceplaza.documents.entity.DocumentOwner ..> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.DocumentOwner ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder ..> com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder
com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder ..> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder ..> com.freelanceplaza.documents.entity.DocumentOwnerId
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof ..> com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof ..> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof ..> com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OrganizationStatus
com.freelanceplaza.documents.entity.Organization ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.documents.entity.Organization ..> com.freelanceplaza.documents.entity.Organization
com.freelanceplaza.documents.entity.document.type.BaseDocumentType ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.BaseDocumentType ..> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType ..> com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder ..> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.documents.entity.DocumentReviewThread ..> com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder
com.freelanceplaza.documents.entity.DocumentReviewThread ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentReviewThread ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentReviewThread ..> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.User ..> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.documents.entity.User ..> com.freelanceplaza.commons.fpcommons.sync.users.Status
com.freelanceplaza.documents.entity.User ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.documents.entity.User ..> com.freelanceplaza.documents.entity.User
com.freelanceplaza.documents.entity.dictionary.Function ..> com.freelanceplaza.documents.entity.dictionary.FunctionCategory
com.freelanceplaza.documents.entity.dictionary.Function ..> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.dictionary.Function ..> com.freelanceplaza.documents.entity.dictionary.Function
com.freelanceplaza.documents.entity.document.type.CertificateDocumentType ..> com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.Document$DocumentBuilder
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.Document ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.QualificationHistory ..> com.freelanceplaza.documents.entity.Qualification
com.freelanceplaza.documents.entity.QualificationHistory ..> com.freelanceplaza.documents.entity.enums.Action
com.freelanceplaza.documents.entity.QualificationHistory ..> com.freelanceplaza.documents.entity.enums.QualificationStatus
com.freelanceplaza.documents.entity.QualificationHistory ..> com.freelanceplaza.documents.entity.QualificationHistory
com.freelanceplaza.documents.entity.DocumentOwnerId ..> com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder
com.freelanceplaza.documents.entity.DocumentOwnerId ..> com.freelanceplaza.documents.entity.enums.OwnerType
com.freelanceplaza.documents.entity.LanguageLevel ..> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule ..> com.freelanceplaza.documents.entity.LanguageLevel
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule ..> com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule ..> com.freelanceplaza.documents.entity.dictionary.BaseDictionary
com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule ..> com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.DocumentAttachment
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentAttachment ..> com.freelanceplaza.documents.entity.enums.AttachmentType
com.freelanceplaza.documents.entity.Qualification ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Qualification ..> com.freelanceplaza.documents.entity.dictionary.Function
com.freelanceplaza.documents.entity.Qualification ..> com.freelanceplaza.documents.entity.enums.QualificationType
com.freelanceplaza.documents.entity.Qualification ..> com.freelanceplaza.documents.entity.enums.QualificationStatus
com.freelanceplaza.documents.entity.Qualification ..> com.freelanceplaza.documents.entity.Qualification
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder ..> com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder ..> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.DocumentReviewThread
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.enums.AttachmentType
com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder ..> com.freelanceplaza.documents.entity.DocumentAttachment
com.freelanceplaza.documents.entity.Document$DocumentBuilder ..> com.freelanceplaza.documents.entity.Document$DocumentBuilder
com.freelanceplaza.documents.entity.Document$DocumentBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.Document$DocumentBuilder ..> com.freelanceplaza.documents.entity.DocumentOwner
com.freelanceplaza.documents.entity.Document$DocumentBuilder ..> com.freelanceplaza.documents.entity.enums.Status
com.freelanceplaza.documents.entity.Document$DocumentBuilder ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof ..> com.freelanceplaza.documents.entity.Document
com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof ..> com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule
com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof ..> com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.dictionary.EducationalLevel
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType
com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder ..> com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-documents-service/src/main/java/com/freelanceplaza/documents/entity/
' com.freelanceplaza.documents.entity.dictionary.BaseDictionary

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType

' com.freelanceplaza.documents.entity.dictionary.FunctionCategory

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule

' com.freelanceplaza.documents.entity.DocumentOwner$DocumentOwnerBuilder

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.enums.Status

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder

' com.freelanceplaza.documents.entity.dictionary.EducationalLevel

' com.freelanceplaza.documents.entity.DocumentOwner

' com.freelanceplaza.documents.entity.DocumentOwnerId$DocumentOwnerIdBuilder

' com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus

' com.freelanceplaza.documents.entity.enums.Action

' com.freelanceplaza.documents.entity.enums.DocumentName

' com.freelanceplaza.documents.entity.FreelancerLanguageLevelProof

' com.freelanceplaza.documents.entity.enums.FileType

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder

' com.freelanceplaza.documents.entity.enums.AttachmentType

' com.freelanceplaza.documents.entity.Organization

' com.freelanceplaza.documents.entity.document.type.BaseDocumentType

' com.freelanceplaza.documents.entity.enums.OnboardingStatus

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType

' com.freelanceplaza.documents.entity.enums.QualificationType

' com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder

' com.freelanceplaza.documents.entity.enums.OwnerType

' com.freelanceplaza.documents.entity.DocumentReviewThread

' com.freelanceplaza.documents.entity.dictionary.DictionaryType

' com.freelanceplaza.documents.entity.User

' com.freelanceplaza.documents.entity.dictionary.Function

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType

' com.freelanceplaza.documents.entity.Document

' com.freelanceplaza.documents.entity.QualificationHistory

' com.freelanceplaza.documents.entity.DocumentOwnerId

' com.freelanceplaza.documents.entity.LanguageLevel

' com.freelanceplaza.documents.entity.enums.QualificationStatus

' com.freelanceplaza.documents.entity.LanguageLevelDocumentTypeRule

' com.freelanceplaza.documents.entity.DocumentAttachment

' com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType

' com.freelanceplaza.documents.entity.Qualification

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.DocumentReviewThread$DocumentReviewThreadBuilder

' com.freelanceplaza.documents.entity.enums.DocumentReviewActions

' com.freelanceplaza.documents.entity.DocumentAttachment$DocumentAttachmentBuilder

' com.freelanceplaza.documents.entity.Document$DocumentBuilder

' com.freelanceplaza.documents.entity.FreelancerDocumentLanguageLevelProof

' com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder

' com.freelanceplaza.documents.entity.enums.OwnerType

' com.freelanceplaza.documents.entity.enums.DocumentReviewActions

' com.freelanceplaza.documents.entity.enums.OnboardingStatus

' com.freelanceplaza.documents.entity.enums.QualificationStatus

' com.freelanceplaza.documents.entity.enums.Status

' com.freelanceplaza.documents.entity.enums.DocumentName

' com.freelanceplaza.documents.entity.enums.FreelancerLanguageLevelStatus

' com.freelanceplaza.documents.entity.enums.DocumentTypeLanguageLevelBizRule

' com.freelanceplaza.documents.entity.enums.LanguageLevelProofStatus

' com.freelanceplaza.documents.entity.enums.QualificationType

' com.freelanceplaza.documents.entity.enums.FileType

' com.freelanceplaza.documents.entity.enums.AttachmentType

' com.freelanceplaza.documents.entity.enums.Action

' com.freelanceplaza.documents.entity.dictionary.EducationalLevel

' com.freelanceplaza.documents.entity.dictionary.Function

' com.freelanceplaza.documents.entity.dictionary.DictionaryType

' com.freelanceplaza.documents.entity.dictionary.FunctionCategory

' com.freelanceplaza.documents.entity.dictionary.BaseDictionary

' com.freelanceplaza.documents.entity.document.type.BaseDocumentType

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.document.type.BaseDocumentType$BaseDocumentTypeBuilder

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType$UniqueDocumentTypeBuilder

' com.freelanceplaza.documents.entity.document.type.ManualQualificationDocumentType

' com.freelanceplaza.documents.entity.document.type.UniqueDocumentType

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType

' com.freelanceplaza.documents.entity.document.type.DiplomaDocumentType$DiplomaDocumentTypeBuilder

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilderImpl

' com.freelanceplaza.documents.entity.document.type.CertificateDocumentType$CertificateDocumentTypeBuilder



@enduml
