@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-kvk-integration/build/classes/java/main]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-kvk-integration/src/main/java/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Fri Jan 17 14:59:07 CET 2025
'
'   Stat infos    :
'       Files : [64]
'       Lines : [1170]
'     Classes : [63]
'     Methods : [527]
'      Fields : [208]



' CLASSES =======
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
class freelanceplaza.fpbackendkvkintegration.config.SecurityConfig
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesGeneric
interface freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon
class freelanceplaza.fpbackendkvkintegration.FpBackendKvkIntegrationApplication
class freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon
class freelanceplaza.fpbackendkvkintegration.controller.v1.KvkSearchController
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder
interface freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder
class freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$RetryConfig
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon
class freelanceplaza.fpbackendkvkintegration.config.DutchUtils
class freelanceplaza.fpbackendkvkintegration.controller.v1.BranchProfileController
class freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric
interface freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric
class freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$TimeoutConfig
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon
interface freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
class freelanceplaza.fpbackendkvkintegration.controller.v1.BasicProfileController
class freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder
class freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2
class freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService
interface freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon
class freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon
class freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
interface freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService
class freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder
class freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesCommon
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder
class freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon
class freelanceplaza.fpbackendkvkintegration.config.RestTemplateConfig
class freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon
class freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
class freelanceplaza.fpbackendkvkintegration.exception.GlobalExceptionHandler
class freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder

' INHERITANCES =======

' IMPLEMENT INTERFACE =======
freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2 <|.. freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2
freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService <|.. freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService <|.. freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService <|.. freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService
freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2 <|.. freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2
freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2 <|.. freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2

' FIELDS =======
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon
freelanceplaza.fpbackendkvkintegration.controller.v1.KvkSearchController --> freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric --> freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric --> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon --> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.controller.v1.BranchProfileController --> freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder --> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric --> freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric
freelanceplaza.fpbackendkvkintegration.controller.v1.BasicProfileController --> freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 --> freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon --> freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$TimeoutConfig
freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$RetryConfig
freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2 --> freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon --> freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon
freelanceplaza.fpbackendkvkintegration.config.RestTemplateConfig --> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2 --> freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric --> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder --> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData

' USES =======
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric
freelanceplaza.fpbackendkvkintegration.controller.v1.KvkSearchController ..> freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.controller.v1.BranchProfileController ..> freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric
freelanceplaza.fpbackendkvkintegration.controller.v1.BasicProfileController ..> freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 ..> freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2 ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder
freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$TimeoutConfig
freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$RetryConfig
freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2 ..> freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon
freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon ..> freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon
freelanceplaza.fpbackendkvkintegration.config.RestTemplateConfig ..> freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.config.RestTemplateConfig ..> B
freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2 ..> freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric ..> freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData
freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder ..> freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-kvk-integration/src/main/java/
' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric$KvkSbiGenericBuilder

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric$KvkSearchResponseGenericBuilder

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData

' freelanceplaza.fpbackendkvkintegration.config.SecurityConfig

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesGeneric

' freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon
freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersCommon ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon

' freelanceplaza.fpbackendkvkintegration.FpBackendKvkIntegrationApplication

' freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.KvkSearchServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon$KvkSearchResponseCommonBuilder

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchAddressCommon ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchForeignAddressCommon ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric

' freelanceplaza.fpbackendkvkintegration.controller.v1.KvkSearchController
freelanceplaza.fpbackendkvkintegration.controller.v1.KvkSearchController ..o freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResponseGeneric

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon$KvkBranchProfileCommonBuilder

' freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric$KvkBranchProfileGenericBuilder

' freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$RetryConfig

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiGeneric

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon

' freelanceplaza.fpbackendkvkintegration.config.DutchUtils

' freelanceplaza.fpbackendkvkintegration.controller.v1.BranchProfileController
freelanceplaza.fpbackendkvkintegration.controller.v1.BranchProfileController ..o freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService

' freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBranchProfileService ..o freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric$KvkAddressGenericBuilder

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedGeneric

' freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2 ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchForeignAddressGeneric

' freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties$TimeoutConfig

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchDomesticAddressCommon ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchDomesticAddressGeneric

' freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2 ..o freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon

' freelanceplaza.fpbackendkvkintegration.controller.v1.BasicProfileController
freelanceplaza.fpbackendkvkintegration.controller.v1.BasicProfileController ..o freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService

' freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService ..o freelanceplaza.fpbackendkvkintegration.service.v1.BasicProfileService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpBasicProfileService ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkGeoData$KvkGeoDataBuilder

' freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResponseCommon
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2
freelanceplaza.fpbackendkvkintegration.controller.v2.KvkSearchControllerV2 ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.PageRequest

' freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v1.impl.FpKvkSearchService ..o freelanceplaza.fpbackendkvkintegration.service.v1.KvkSearchService

' freelanceplaza.fpbackendkvkintegration.service.v2.KvkSearchServiceV2

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon$KvkSearchResultCommonBuilder

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon

' freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileGeneric
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BranchProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon

' freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties

' freelanceplaza.fpbackendkvkintegration.service.v1.BranchProfileService

' freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2
freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
freelanceplaza.fpbackendkvkintegration.controller.v2.BasicProfileControllerV2 ..o freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric
freelanceplaza.fpbackendkvkintegration.model.basic_profile.HeadquartersGeneric ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressGeneric

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric$KvkSearchResultGenericBuilder

' freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.BasicProfileServiceV2
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.config.KvkApiProperties
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileCommon
freelanceplaza.fpbackendkvkintegration.service.v2.impl.BasicProfileServiceImplV2 ..o freelanceplaza.fpbackendkvkintegration.model.basic_profile.KvkBasicProfileGeneric

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.TradeNamesCommon

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkSbiCommon$KvkSbiCommonBuilder

' freelanceplaza.fpbackendkvkintegration.model.basic_profile.EmbeddedCommon

' freelanceplaza.fpbackendkvkintegration.config.RestTemplateConfig

' freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2
freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2 ..o freelanceplaza.fpbackendkvkintegration.service.v2.BranchProfileServiceV2
freelanceplaza.fpbackendkvkintegration.controller.v2.BranchProfileControllerV2 ..o freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkBranchProfileCommon

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon
freelanceplaza.fpbackendkvkintegration.model.kvk_search.common.KvkSearchResultCommon ..o freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchResultGeneric

' freelanceplaza.fpbackendkvkintegration.model.kvk_search.generic.KvkSearchAddressGeneric

' freelanceplaza.fpbackendkvkintegration.exception.GlobalExceptionHandler

' freelanceplaza.fpbackendkvkintegration.model.branch_profile.KvkAddressCommon$KvkAddressCommonBuilder



@enduml
