@startuml
'https://plantuml.com/class-diagram

' GENERATE CLASS DIAGRAM ===========
' Generator       : it.brunasti.java.diagrammer.ClassDiagrammer
' Path            : [/Users/paolo/Work/Tadaah/fp-backend-hiring-service/build/classes/java/main/com/freelanceplaza/hiringservice/entities]
' Java Files Path : [/Users/paolo/Work/Tadaah/fp-backend-hiring-service/src/main/java/com/freelanceplaza/hiringservice/entities/]
' Configuration   : [/Users/paolo/IdeaProjects/mine/java-diagrammer/temp/tadaah/config.json]
' Generated at    : Thu Feb 20 18:12:52 CET 2025
'
'   Stat infos    :
'       Files : [58]
'       Lines : [1085]
'     Classes : [58]
'     Methods : [666]
'      Fields : [525]



' CLASSES =======
class com.freelanceplaza.hiringservice.entities.QDocumentTypeEntity
class com.freelanceplaza.hiringservice.entities.FreelancerProposal
class com.freelanceplaza.hiringservice.entities.QShift
class com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder
class com.freelanceplaza.hiringservice.entities.QFavoriteLocationFreelancer
class com.freelanceplaza.hiringservice.entities.PrkRecord
class com.freelanceplaza.hiringservice.entities.QDocument
class com.freelanceplaza.hiringservice.entities.QM2MToken
class com.freelanceplaza.hiringservice.entities.QFreelancerLocationExclusions
class com.freelanceplaza.hiringservice.entities.Config
class com.freelanceplaza.hiringservice.entities.ShiftCancellationReason
class com.freelanceplaza.hiringservice.entities.QFreelancerProposal
class com.freelanceplaza.hiringservice.entities.HireCancellation
class com.freelanceplaza.hiringservice.entities.HireCancellationReason
class com.freelanceplaza.hiringservice.entities.Organization
class com.freelanceplaza.hiringservice.entities.Invoice
class com.freelanceplaza.hiringservice.entities.QHireApproval
class com.freelanceplaza.hiringservice.entities.DocumentTypeEntity
class com.freelanceplaza.hiringservice.entities.QApplication
class com.freelanceplaza.hiringservice.entities.QInvoiceFile
class com.freelanceplaza.hiringservice.entities.HireApproval
class com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder
class com.freelanceplaza.hiringservice.entities.User
class com.freelanceplaza.hiringservice.entities.M2MToken
class com.freelanceplaza.hiringservice.entities.LocationGroup
class com.freelanceplaza.hiringservice.entities.AssignmentAgreement
class com.freelanceplaza.hiringservice.entities.Shift
class com.freelanceplaza.hiringservice.entities.ApplicationRejection
class com.freelanceplaza.hiringservice.entities.Application
class com.freelanceplaza.hiringservice.entities.QLocation
class com.freelanceplaza.hiringservice.entities.Hire$HireBuilder
class com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder
class com.freelanceplaza.hiringservice.entities.QApplicationRejection
class com.freelanceplaza.hiringservice.entities.QShiftCancellation
class com.freelanceplaza.hiringservice.entities.QUser
class com.freelanceplaza.hiringservice.entities.Function
class com.freelanceplaza.hiringservice.entities.QInvoice
class com.freelanceplaza.hiringservice.entities.ShiftCancellation
class com.freelanceplaza.hiringservice.entities.QPrkRecord
class com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions
class com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer
class com.freelanceplaza.hiringservice.entities.InvoiceFile
class com.freelanceplaza.hiringservice.entities.QFunction
class com.freelanceplaza.hiringservice.entities.QHireCancellationReason
class com.freelanceplaza.hiringservice.entities.Compensation
class com.freelanceplaza.hiringservice.entities.QAssignmentAgreement
class com.freelanceplaza.hiringservice.entities.QShiftCancellationReason
class com.freelanceplaza.hiringservice.entities.QHire
class com.freelanceplaza.hiringservice.entities.QCompensation
class com.freelanceplaza.hiringservice.entities.Hire
class com.freelanceplaza.hiringservice.entities.QOrganization
class com.freelanceplaza.hiringservice.entities.PrkRecordHistory
class com.freelanceplaza.hiringservice.entities.Document
class com.freelanceplaza.hiringservice.entities.QPrkRecordHistory
class com.freelanceplaza.hiringservice.entities.Location
class com.freelanceplaza.hiringservice.entities.QConfig
class com.freelanceplaza.hiringservice.entities.QHireCancellation
class com.freelanceplaza.hiringservice.entities.QLocationGroup

' INHERITANCES =======

' IMPLEMENT INTERFACE =======

' FIELDS =======
com.freelanceplaza.hiringservice.entities.FreelancerProposal --> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.enums.ShiftStatus
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.enums.HiringRule
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.enums.SelectionRule
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.entities.ShiftCancellation
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.entities.Function
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder --> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.PrkRecord --> com.freelanceplaza.hiringservice.entities.User
com.freelanceplaza.hiringservice.entities.PrkRecord --> com.freelanceplaza.hiringservice.entities.Organization
com.freelanceplaza.hiringservice.entities.Config --> com.freelanceplaza.hiringservice.enums.ConfigCodes
com.freelanceplaza.hiringservice.entities.HireCancellation --> com.freelanceplaza.hiringservice.enums.CancellationType
com.freelanceplaza.hiringservice.entities.HireCancellation --> com.freelanceplaza.hiringservice.entities.HireCancellationReason
com.freelanceplaza.hiringservice.entities.HireCancellation --> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.HireCancellationReason --> com.freelanceplaza.hiringservice.enums.HireCancellationReasonType
com.freelanceplaza.hiringservice.entities.Invoice --> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.hiringservice.entities.DocumentTypeEntity --> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.hiringservice.entities.HireApproval --> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.HireApproval --> com.freelanceplaza.hiringservice.enums.HireApprovalSource
com.freelanceplaza.hiringservice.entities.HireApproval --> com.freelanceplaza.hiringservice.enums.HireApprovalStatus
com.freelanceplaza.hiringservice.entities.HireApproval --> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.User --> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.hiringservice.entities.User --> com.freelanceplaza.commons.fpcommons.sync.users.Status
com.freelanceplaza.hiringservice.entities.User --> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.hiringservice.entities.LocationGroup --> com.freelanceplaza.hiringservice.entities.Location
com.freelanceplaza.hiringservice.entities.AssignmentAgreement --> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.enums.ShiftStatus
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.enums.HiringRule
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.enums.SelectionRule
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.entities.ShiftCancellation
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.entities.Function
com.freelanceplaza.hiringservice.entities.Shift --> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.ApplicationRejection --> com.freelanceplaza.hiringservice.enums.ApplicationRejectionReason
com.freelanceplaza.hiringservice.entities.ApplicationRejection --> com.freelanceplaza.hiringservice.entities.Application
com.freelanceplaza.hiringservice.entities.Application --> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Application --> com.freelanceplaza.hiringservice.enums.ApplicationStatus
com.freelanceplaza.hiringservice.entities.Application --> com.freelanceplaza.hiringservice.entities.ApplicationRejection
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.enums.HireStatus
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.FreelancerProposal
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.HireApproval
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.HireCancellation
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.AssignmentAgreement
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder --> com.freelanceplaza.hiringservice.entities.Invoice
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder --> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder --> com.freelanceplaza.hiringservice.enums.ApplicationStatus
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder --> com.freelanceplaza.hiringservice.entities.ApplicationRejection
com.freelanceplaza.hiringservice.entities.ShiftCancellation --> com.freelanceplaza.hiringservice.enums.CancellationType
com.freelanceplaza.hiringservice.entities.ShiftCancellation --> com.freelanceplaza.hiringservice.entities.ShiftCancellationReason
com.freelanceplaza.hiringservice.entities.ShiftCancellation --> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions --> com.freelanceplaza.hiringservice.dtos.common.LocationFreelancerId
com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer --> com.freelanceplaza.hiringservice.dtos.common.LocationFreelancerId
com.freelanceplaza.hiringservice.entities.InvoiceFile --> com.freelanceplaza.invoices.enums.InvoiceBucketReference
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.enums.HireStatus
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.FreelancerProposal
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.HireApproval
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.HireCancellation
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.AssignmentAgreement
com.freelanceplaza.hiringservice.entities.Hire --> com.freelanceplaza.hiringservice.entities.Invoice
com.freelanceplaza.hiringservice.entities.PrkRecordHistory --> com.freelanceplaza.hiringservice.enums.Action
com.freelanceplaza.hiringservice.entities.Document --> com.freelanceplaza.hiringservice.entities.DocumentTypeEntity
com.freelanceplaza.hiringservice.entities.Location --> com.freelanceplaza.hiringservice.entities.Organization
com.freelanceplaza.hiringservice.entities.Location --> com.freelanceplaza.commons.fpcommons.sync.locations.LocationStatus

' USES =======
com.freelanceplaza.hiringservice.entities.FreelancerProposal ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.FreelancerProposal ..> com.freelanceplaza.hiringservice.entities.FreelancerProposal
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.enums.ShiftStatus
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.enums.HiringRule
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.enums.SelectionRule
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.entities.ShiftCancellation
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.entities.Function
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.PrkRecord ..> com.freelanceplaza.hiringservice.entities.User
com.freelanceplaza.hiringservice.entities.PrkRecord ..> com.freelanceplaza.hiringservice.entities.Organization
com.freelanceplaza.hiringservice.entities.PrkRecord ..> com.freelanceplaza.hiringservice.entities.PrkRecord
com.freelanceplaza.hiringservice.entities.Config ..> com.freelanceplaza.hiringservice.enums.ConfigCodes
com.freelanceplaza.hiringservice.entities.Config ..> com.freelanceplaza.hiringservice.entities.Config
com.freelanceplaza.hiringservice.entities.ShiftCancellationReason ..> com.freelanceplaza.hiringservice.entities.ShiftCancellationReason
com.freelanceplaza.hiringservice.entities.HireCancellation ..> com.freelanceplaza.hiringservice.enums.CancellationType
com.freelanceplaza.hiringservice.entities.HireCancellation ..> com.freelanceplaza.hiringservice.entities.HireCancellationReason
com.freelanceplaza.hiringservice.entities.HireCancellation ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.HireCancellation ..> com.freelanceplaza.hiringservice.entities.HireCancellation
com.freelanceplaza.hiringservice.entities.HireCancellationReason ..> com.freelanceplaza.hiringservice.enums.HireCancellationReasonType
com.freelanceplaza.hiringservice.entities.HireCancellationReason ..> com.freelanceplaza.hiringservice.entities.HireCancellationReason
com.freelanceplaza.hiringservice.entities.Organization ..> com.freelanceplaza.hiringservice.entities.Organization
com.freelanceplaza.hiringservice.entities.Invoice ..> com.freelanceplaza.commons.fpcommons.enums.Currency
com.freelanceplaza.hiringservice.entities.Invoice ..> com.freelanceplaza.hiringservice.entities.Invoice
com.freelanceplaza.hiringservice.entities.DocumentTypeEntity ..> com.freelanceplaza.commons.fpcommons.sync.documents.DocumentType
com.freelanceplaza.hiringservice.entities.DocumentTypeEntity ..> com.freelanceplaza.hiringservice.entities.DocumentTypeEntity
com.freelanceplaza.hiringservice.entities.HireApproval ..> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.HireApproval ..> com.freelanceplaza.hiringservice.enums.HireApprovalSource
com.freelanceplaza.hiringservice.entities.HireApproval ..> com.freelanceplaza.hiringservice.enums.HireApprovalStatus
com.freelanceplaza.hiringservice.entities.HireApproval ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.HireApproval ..> com.freelanceplaza.hiringservice.entities.HireApproval
com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder ..> com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder
com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder ..> com.freelanceplaza.hiringservice.entities.M2MToken
com.freelanceplaza.hiringservice.entities.User ..> com.freelanceplaza.commons.fpcommons.sync.users.UserType
com.freelanceplaza.hiringservice.entities.User ..> com.freelanceplaza.commons.fpcommons.sync.users.Status
com.freelanceplaza.hiringservice.entities.User ..> com.freelanceplaza.commons.fpcommons.sync.organizations.OnboardingStatus
com.freelanceplaza.hiringservice.entities.User ..> com.freelanceplaza.hiringservice.entities.User
com.freelanceplaza.hiringservice.entities.M2MToken ..> com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder
com.freelanceplaza.hiringservice.entities.M2MToken ..> com.freelanceplaza.hiringservice.entities.M2MToken
com.freelanceplaza.hiringservice.entities.LocationGroup ..> com.freelanceplaza.hiringservice.entities.Location
com.freelanceplaza.hiringservice.entities.LocationGroup ..> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.AssignmentAgreement ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.AssignmentAgreement ..> com.freelanceplaza.hiringservice.entities.AssignmentAgreement
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.enums.ShiftStatus
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.enums.HiringRule
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.enums.SelectionRule
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.entities.ShiftCancellation
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.entities.Function
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.entities.LocationGroup
com.freelanceplaza.hiringservice.entities.Shift ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.ApplicationRejection ..> com.freelanceplaza.hiringservice.enums.ApplicationRejectionReason
com.freelanceplaza.hiringservice.entities.ApplicationRejection ..> com.freelanceplaza.hiringservice.entities.Application
com.freelanceplaza.hiringservice.entities.ApplicationRejection ..> com.freelanceplaza.hiringservice.entities.ApplicationRejection
com.freelanceplaza.hiringservice.entities.Application ..> com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder
com.freelanceplaza.hiringservice.entities.Application ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Application ..> com.freelanceplaza.hiringservice.enums.ApplicationStatus
com.freelanceplaza.hiringservice.entities.Application ..> com.freelanceplaza.hiringservice.entities.ApplicationRejection
com.freelanceplaza.hiringservice.entities.Application ..> com.freelanceplaza.hiringservice.entities.Application
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.Hire$HireBuilder
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.enums.HireStatus
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.FreelancerProposal
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.HireApproval
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.HireCancellation
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.AssignmentAgreement
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.Invoice
com.freelanceplaza.hiringservice.entities.Hire$HireBuilder ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder ..> com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder ..> com.freelanceplaza.hiringservice.enums.ApplicationStatus
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder ..> com.freelanceplaza.hiringservice.entities.ApplicationRejection
com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder ..> com.freelanceplaza.hiringservice.entities.Application
com.freelanceplaza.hiringservice.entities.Function ..> com.freelanceplaza.hiringservice.entities.Function
com.freelanceplaza.hiringservice.entities.ShiftCancellation ..> com.freelanceplaza.hiringservice.enums.CancellationType
com.freelanceplaza.hiringservice.entities.ShiftCancellation ..> com.freelanceplaza.hiringservice.entities.ShiftCancellationReason
com.freelanceplaza.hiringservice.entities.ShiftCancellation ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.ShiftCancellation ..> com.freelanceplaza.hiringservice.entities.ShiftCancellation
com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions ..> com.freelanceplaza.hiringservice.dtos.common.LocationFreelancerId
com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions ..> com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions
com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer ..> com.freelanceplaza.hiringservice.dtos.common.LocationFreelancerId
com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer ..> com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer
com.freelanceplaza.hiringservice.entities.InvoiceFile ..> com.freelanceplaza.invoices.enums.InvoiceBucketReference
com.freelanceplaza.hiringservice.entities.InvoiceFile ..> com.freelanceplaza.hiringservice.entities.InvoiceFile
com.freelanceplaza.hiringservice.entities.Compensation ..> com.freelanceplaza.hiringservice.entities.Compensation
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.Hire$HireBuilder
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.Shift
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.enums.HireStatus
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.FreelancerProposal
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.HireApproval
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.HireCancellation
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.AssignmentAgreement
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.Invoice
com.freelanceplaza.hiringservice.entities.Hire ..> com.freelanceplaza.hiringservice.entities.Hire
com.freelanceplaza.hiringservice.entities.PrkRecordHistory ..> com.freelanceplaza.hiringservice.enums.Action
com.freelanceplaza.hiringservice.entities.PrkRecordHistory ..> com.freelanceplaza.hiringservice.entities.PrkRecordHistory
com.freelanceplaza.hiringservice.entities.Document ..> com.freelanceplaza.hiringservice.entities.DocumentTypeEntity
com.freelanceplaza.hiringservice.entities.Document ..> com.freelanceplaza.hiringservice.entities.Document
com.freelanceplaza.hiringservice.entities.Location ..> com.freelanceplaza.hiringservice.entities.Organization
com.freelanceplaza.hiringservice.entities.Location ..> com.freelanceplaza.commons.fpcommons.sync.locations.LocationStatus
com.freelanceplaza.hiringservice.entities.Location ..> com.freelanceplaza.hiringservice.entities.Location

' IMPORTS =======
' Java Files Path : /Users/paolo/Work/Tadaah/fp-backend-hiring-service/src/main/java/com/freelanceplaza/hiringservice/entities/
' com.freelanceplaza.hiringservice.entities.QDocumentTypeEntity

' com.freelanceplaza.hiringservice.entities.FreelancerProposal

' com.freelanceplaza.hiringservice.entities.QShift

' com.freelanceplaza.hiringservice.entities.Shift$ShiftBuilder

' com.freelanceplaza.hiringservice.entities.QFavoriteLocationFreelancer

' com.freelanceplaza.hiringservice.entities.PrkRecord

' com.freelanceplaza.hiringservice.entities.QDocument

' com.freelanceplaza.hiringservice.entities.QM2MToken

' com.freelanceplaza.hiringservice.entities.QFreelancerLocationExclusions

' com.freelanceplaza.hiringservice.entities.Config

' com.freelanceplaza.hiringservice.entities.ShiftCancellationReason

' com.freelanceplaza.hiringservice.entities.QFreelancerProposal

' com.freelanceplaza.hiringservice.entities.HireCancellation

' com.freelanceplaza.hiringservice.entities.HireCancellationReason

' com.freelanceplaza.hiringservice.entities.Organization

' com.freelanceplaza.hiringservice.entities.Invoice

' com.freelanceplaza.hiringservice.entities.QHireApproval

' com.freelanceplaza.hiringservice.entities.DocumentTypeEntity

' com.freelanceplaza.hiringservice.entities.QApplication

' com.freelanceplaza.hiringservice.entities.QInvoiceFile

' com.freelanceplaza.hiringservice.entities.HireApproval

' com.freelanceplaza.hiringservice.entities.M2MToken$M2MTokenBuilder

' com.freelanceplaza.hiringservice.entities.User

' com.freelanceplaza.hiringservice.entities.M2MToken

' com.freelanceplaza.hiringservice.entities.LocationGroup

' com.freelanceplaza.hiringservice.entities.AssignmentAgreement

' com.freelanceplaza.hiringservice.entities.Shift

' com.freelanceplaza.hiringservice.entities.ApplicationRejection

' com.freelanceplaza.hiringservice.entities.Application

' com.freelanceplaza.hiringservice.entities.QLocation

' com.freelanceplaza.hiringservice.entities.Hire$HireBuilder

' com.freelanceplaza.hiringservice.entities.Application$ApplicationBuilder

' com.freelanceplaza.hiringservice.entities.QApplicationRejection

' com.freelanceplaza.hiringservice.entities.QShiftCancellation

' com.freelanceplaza.hiringservice.entities.QUser

' com.freelanceplaza.hiringservice.entities.Function

' com.freelanceplaza.hiringservice.entities.QInvoice

' com.freelanceplaza.hiringservice.entities.ShiftCancellation

' com.freelanceplaza.hiringservice.entities.QPrkRecord

' com.freelanceplaza.hiringservice.entities.FreelancerLocationExclusions

' com.freelanceplaza.hiringservice.entities.FavoriteLocationFreelancer

' com.freelanceplaza.hiringservice.entities.InvoiceFile

' com.freelanceplaza.hiringservice.entities.QFunction

' com.freelanceplaza.hiringservice.entities.QHireCancellationReason

' com.freelanceplaza.hiringservice.entities.Compensation

' com.freelanceplaza.hiringservice.entities.QAssignmentAgreement

' com.freelanceplaza.hiringservice.entities.QShiftCancellationReason

' com.freelanceplaza.hiringservice.entities.QHire

' com.freelanceplaza.hiringservice.entities.QCompensation

' com.freelanceplaza.hiringservice.entities.Hire

' com.freelanceplaza.hiringservice.entities.QOrganization

' com.freelanceplaza.hiringservice.entities.PrkRecordHistory

' com.freelanceplaza.hiringservice.entities.Document

' com.freelanceplaza.hiringservice.entities.QPrkRecordHistory

' com.freelanceplaza.hiringservice.entities.Location

' com.freelanceplaza.hiringservice.entities.QConfig

' com.freelanceplaza.hiringservice.entities.QHireCancellation

' com.freelanceplaza.hiringservice.entities.QLocationGroup



@enduml
